<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Norsk";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Generelt',
    'TCKLARNA_CONFIGURATION'                            => 'Konfigurasjon',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfigurasjon for Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Designinnstillinger',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Eksterne betalingsmåter',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ytterligere forhandleropplysninger',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Grunninnstillinger',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Rabatt',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'I denne modusen finnes det ingen innstillinger.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Alle innstillinger er lagret.',

    'TCKLARNA_EASY'                                     => 'Det er så enkelt å aktivere Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-post',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Åpningstider',
    'TCKLARNA_MONDAY'                                   => 'mandag',
    'TCKLARNA_TUESDAY'                                  => 'Tirsdag',
    'TCKLARNA_WEDNESDAY'                                => 'onsdag',
    'TCKLARNA_THURSDAY'                                 => 'Torsdag',
    'TCKLARNA_FRIDAY'                                   => 'fredag',
    'TCKLARNA_SATURDAY'                                 => 'Lørdag',
    'TCKLARNA_SUNDAY'                                   => 'Søndag',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Dine landsspesifikke påloggingsopplysninger',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Legg til landsspesifikke påloggingsopplysninger',
    'TCKLARNA_COUNTRY'                                  => 'Land',
    'TCKLARNA_MERCHANT_ID'                              => 'API-brukernavn',
    'TCKLARNA_PASSWORD'                                 => 'API-passord',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Forhandler-ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Standardland for nettbutikken',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Logging aktiv',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Sende utvidede produktdata til Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Produkt-URL-er',
    'TCKLARNA_IMAGE_URLS'                               => 'Bilde-URL-er',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymisere',
    'TCKLARNA_ADD'                                      => 'Legg til',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-betalinger',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Velg Klarna-modul og modus',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Med Klarna kan sluttkunder betale på tre måter: Sofortüberweisung, senere eller i avdrag. Dette gjør det mulig for sluttkunder å prøve varene først og bare betale for det de ønsker å beholde, finansiere produkter i nettbutikken eller betale umiddelbart. Faktura, avbetalingskjøp, umiddelbar bankoverføring eller direkte belastning kan du aktivere med en integrasjon, og takket være Klarnas iFrame-løsning er disse alternativene alltid oppdatert både juridisk og innholdsmessig.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'De mest populære betalingsmåtene. Sikre og enkle å integrere.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Hjertelig velkommen til konfigurasjonsinnstillingene for Klarna Payments. Her finner du alt du trenger for å aktivere tjenesten. Velg undermenyene for Klarna i menyen til venstre for å fullføre moduloppsettet.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Opprette en kundekonto i OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Påmelding til nyhetsbrev',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Opprett kundekonto OG meld deg på nyhetsbrevet',
    'TCKLARNA_NO_CHECKBOX'                              => 'Ikke vis avkrysningsrute',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Vise på butikkens startside?',
    'TCKLARNA_BANNER_SRC'                               => 'Kilde til Klarna-banner',
    'TCKLARNA_FOOTER'                                   => 'Bunntekst',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Hva skal vises i bunnteksten?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visning av betalingsmåter',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna-logoen',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Lang versjon:',
    'TCKLARNA_SHORT_VERSION'                            => 'Kortversjon:',
    'TCKLARNA_WHITE'                                    => 'Hvitt:',
    'TCKLARNA_BLACK'                                    => 'Svart:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Artikkeloversikt og handlekurv',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Vise Klarna-betalingsmetode-widgeten?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'På artikkelens detaljsiden',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'På handlekurv-siden',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Vise «Kjøp nå»-knappen?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Klarna-betalingsdesignalternativer',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Fargeinnstillinger:',
    'TCKLARNA_BORDER'                                   => 'Grense:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Valgt grense:',
    'TCKLARNA_BUTTON'                                   => 'Knapp:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Tekst på knappen:',
    'TCKLARNA_CHECKBOX'                                 => 'Avkryssingsrute:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Avkryssingsrute:',
    'TCKLARNA_DETAILS'                                  => 'Detaljer:',
    'TCKLARNA_HEADER'                                   => 'Overskrift:',
    'TCKLARNA_LINK'                                     => 'Lenke:',
    'TCKLARNA_TEXT'                                     => 'Tekst:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Ytterligere tekst:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Innstilling av radius:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Kantradius:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Leveringsadressen kan avvike fra fakturaadressen',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefonnummer er et obligatorisk felt',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Fødselsdato er et obligatorisk felt',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktiver levering til DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktiver forhåndsfylling',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktiver varsel om forhåndsfylling',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Tittel er et obligatorisk felt',
    'TCKLARNA_SET_TAC_URI'                              => 'URL til bruksvilkårene dine',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL om angreretten',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Fraktdetaljer',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Ingen validering',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Gjennomfør validering, men ignorér tidsavbrudd',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Vellykket validering er nødvendig',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Bekreftelse av bestilling',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vennligst velg de Klarna-betalingsalternativene du ønsker å tilby kundene dine:',
    'TCKLARNA_PAY_LATER'                                => 'Faktura',
    'TCKLARNA_PAY_LATER.'                               => 'Faktura.',
    'TCKLARNA_PAY_LATER_START'                          => 'For kunder som ønsker å kjøpe nå og betale senere. Helt enkelt innen 14, 21 eller 28 dager, avhengig av marked.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Alternativet «Faktura» gjør betalingsprosessen enkel og rask for kundene, uten at de trenger å oppgi personopplysninger eller kompliserte numre. Kunden kan velge mellom faktura og betaling i måned X.',
    'TCKLARNA_SLICE_IT'                                 => 'Avbetalingskjøp.',
    'TCKLARNA_SLICE_IT.'                                => 'Betale i avdrag.',
    'TCKLARNA_SLICE_IT_START'                           => 'Øk kundenes kjøpekraft ved å tilby avbetaling. Kundene kan betale for kjøpene sine i faste månedlige avdrag over en periode på 6 til 36 måneder.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Gjennom «avbetalingskjøp» kan kundene dele opp kjøpesummen i mindre delbetalinger til lav rente. Dette øker investeringsrammen og kjøpekraften. Klarnas unike kredittbehandling tar bare noen få øyeblikk og krever minimalt med datainnlegging.',
    'TCKLARNA_PAY_NOW'                                  => 'Betal nå',
    'TCKLARNA_PAY_NOW.'                                 => 'Betal med en gang.',
    'TCKLARNA_PAY_NOW_START'                            => 'Enkel og rask direktebetaling med Klarnas «Sofort bezahlen». I Tyskland bør Sofortüberweisung, kredittkort og direktebelastning være en del av tilbudet.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Kunder som ønsker å betale hele beløpet umiddelbart ved bestillingsavslutningen, kan benytte seg av alternativet «Betal umiddelbart». Her kan man velge mellom kredittkort, direkte belastning og Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Veiledning i hvordan du <br />aktiverer Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Klikk på det nye menypunktet «Klarna» i OXID-backend, deretter på underkategorien «Generelt», og velg deretter det ønskede Klarna-produktet.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Skriv inn påloggingsopplysningene dine (brukernavn og passord), og foreta de vanlige OXID-tilordningene for betalingsmåter under «Butikkinnstillinger» &gt; «Betalingsmåter» samt &gt; «Fraktmåter».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Lagre endringene.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Du er nå online og kan begynne å selge med Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Støtte for forhandlere',
    'TCKLARNA_DEVICE_IMG'                               => 'enhet.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Her kan du angi om eventuelle ekstra forhandleropplysninger skal overføres til Klarna. 
For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les brukerhåndboken 
eller ta kontakt med Klarnas integrasjonssupport.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Her kan du konfigurere designinnstillingene for bruk med Klarna-modulen for OXID eShop. 
For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les <a class="cl-pink" href="%s" target="_blank">brukerhåndb</a>oken 
eller ta kontakt med Klarna Integration Support.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Her kan du velge innstillinger for Klarna Payments og foreta generelle innstillinger. 
For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les <a class="cl-pink" href="%s" target="_blank">bruk</a>erh<a class="cl-pink" href="%s" target="_blank">åndb</a>oken 
eller ta kontakt med Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'På denne siden velger du hvilke Klarna-betalingsmåter du ønsker å tilby. 
For en detaljert beskrivelse av de ulike innstillingene, se verktøytipsene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, les <a class="cl-pink" href="%s" target="_blank">bruksanvisningen</a> 
eller ta kontakt med Klarnas integrasjonssupport.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Betalingsmåte',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Ekstern betalingsmåte',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Bilde-URI for ekstern betalingsmetode',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Bildestørrelse: 69x24 piksler',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Bildestørrelse: 276x48 piksler',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Du kan lese brukerhåndboken for Klarna-modulen til OXID eShop her.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Brukerhåndbok',

    'TCKLARNA_CHOOSE'                                   => 'Velg',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informasjon om kundekontoen',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Fullstendig betalingshistorikk',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Gjennomføringsfelt',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Tilordne betalingsmåte:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Hvilke bestillinger skal inkluderes i «Payment history full»?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Alle bestillinger skal betraktes som betalt, uavhengig av oxpaid-datoen',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Send kun bestillinger med angitt oxpaid-dato; ignorér ubetalte bestillinger',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorer alle bestillinger som er gjennomført med denne betalingsmåten',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Andre betalingsalternativer',
    'TCKLARNA_DIRECT_BANKING'                           => 'Direkteoverføring',
    'TCKLARNA_CARD'                                     => 'Kart',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Velg mellom «Playground» (testdrift) og «Live» (produksjonsdrift). Aktiver produksjonsdriften først etter at integrasjonstestene er gjennomført med godt resultat og etter avtale med din Klarna-integrasjonsansvarlig.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Vennligst oppgi dine Klarna API-påloggingsopplysninger her. Du har mottatt disse i velkomst-e-posten fra Klarna. Dette brukernavnet og passordet gjelder globalt for alle land. Kun dersom du har mottatt forskjellige påloggingsopplysninger for ulike land, kan du legge disse til lenger ned.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Skriv inn passordet ditt her, som skal stemme overens med API-brukernavnet du bruker. Du har mottatt dette passordet i velkomst-e-posten fra Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Vennligst oppgi din Klarna-forhandler-ID her. Du har mottatt denne i velkomst-e-posten fra Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Velg det landet du har mottatt landsspesifikke påloggingsopplysninger fra Klarna for, fra listen til venstre.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Vennligst skriv inn brukernavnet for dette landet her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Vennligst skriv inn passordet for dette landet her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Vennligst oppgi den tilhørende forhandler-ID-en for dette landet her.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktiverer loggfunksjonen, slik at all API-kommunikasjon med Klarna blir loggført i MySQL-tabellen tcklarna_logs. Dette kan være nyttig ved analyse eller feilsøking. I produksjonsdrift bør funksjonen være deaktivert, da det ellers kan oppstå store mengder loggdata og sensitive opplysninger kan bli lagret.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Send URL-adressene til produktdetaljsidene for varene som ligger i kundenes handlekurv til Klarna, slik at Klarna senere kan lenke til produktene dine fra Klarna-portalen.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Send URL-adressene til produktbildene for varene som ligger i kundenes handlekurv til Klarna, slik at Klarna kan vise dem i Klarna-portalen.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktiver anonymiseringen for å skjule produktbetegnelsene på varene som ligger i kundenes handlekurv for Klarna. Dette anbefales for eksempel for nettapotek, men bør kun gjøres etter avtale med Klarna Integration Manager.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Hvis levering til en annen leveringsadresse skal være mulig, må du aktivere denne bryteren.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Hvis du ønsker å gjøre det obligatorisk å oppgi et telefonnummer, må du aktivere denne bryteren. Normalt er telefonnummeret ikke et obligatorisk felt for Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Hvis du ønsker å gjøre det obligatorisk å oppgi fødselsdato, må du aktivere denne bryteren. Normalt er fødselsdato ikke et obligatorisk felt hos Klarna. Opplysningen er imidlertid nødvendig for å kunne gjennomføre kjøp på faktura eller avbetaling.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Foreløpig ikke implementert',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Oppgi her nettadressen til nettsiden din med informasjon om angreretten. Nettadressen må begynne med https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Disse leveringsopplysningene vises for kunden på takkesiden etter at bestillingen er fullført.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Tilordne denne eksterne betalingsmåten til en av de forhåndsdefinerte betalingsmåtene',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Vennligst oppgi en URL for alle språk',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Vennligst oppgi en gyldig URL som begynner med https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Denne bryteren aktiverer overføring av tilleggsdata til Klarna, i dette tilfellet kundekontoinformasjonen, som inneholder datoen for registrering av kundekontoen og datoen for den siste endringen.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Denne bryteren aktiverer overføring av tilleggsdata til Klarna, i dette tilfellet «Payment History Full», som inneholder kundens tidligere kjøp.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Vennligst velg hvilken type betalingsmåte denne betalingsmetoden tilhører.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Angi her om, og i så fall hvilke, bestillinger med denne betalingsmåten som skal inkluderes når kundens bestillingshistorikk overføres. Avhengigheten til feltet OXORDER.OXPAID angir om kun betalte bestillinger eller alle bestillinger skal tas med.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Det er mulig å overføre ytterligere data til Klarna ved hjelp av et «pass-through»-felt. For å kunne bruke denne funksjonen må du installere en passende modul i OXID eShop som skriver de ønskede dataene inn i «pass-through»-feltet. Du finner en veiledning om dette i utviklerdokumentasjonen.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Med denne bryteren aktiverer du et Klarna-banner på startsiden til nettbutikken din i standardtemaet Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Her kan du legge inn script-taggen for å integrere banneret. I Klarnas bannerportal finner du eventuelt flere bannere å velge mellom.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Med denne bryteren aktiverer du Klarna-betalingsmetodevisningen i bunnteksten på nettbutikken din i standardtemaet Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Med denne bryteren kan du legge inn Klarna-logoen i bunnteksten på nettbutikken din i standardtemaet Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Denne bryteren legger til en «Kjøp nå»-knapp på varedetaljsidene i nettbutikken din i standardtemaet Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Fargen på rammen som vises i nettbutikkens brukergrensesnitt når man velger Klarna som betalingsmåte, avhengig av hvilke underalternativer som er tilgjengelige.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Fargen på rammen som vises i nettbutikkens frontend når man velger Klarna som betalingsmåte, dersom det finnes ulike underalternativer. Denne fargen brukes til å markere det underalternativet som for øyeblikket er aktivt valgt.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Bakgrunnsfargen på radioknappene som vises i butikkens frontend når man velger betalingsmåten Klarna, dersom det finnes flere underalternativer',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Fargen på opptellingstegnene når betalingsdetaljene vises på siden for valg av betalingsmåte.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Denne innstillingen har ingen virkning på tidspunktet for utgivelsen av dette modulen.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Fargen på lenkene i detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Tekstfarge for detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternativ tekstfarge for detaljbeskrivelsen av betalingsmåtene på siden for valg av betalingsmåte.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Med denne innstillingen kan du angi hvor avrundet rammen skal være, som vises i butikkens brukergrensesnitt når du velger betalingsmåten Klarna, avhengig av de ulike underalternativene som er tilgjengelige.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Denne fanen gjelder kun bestillinger via Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Registrere hele bestillingen',
    'KLARNA_CAPTURE_ID'                                 => 'Trekk-ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-referanse',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Beløp som trekkes',
    'KLARNA_CAPTURE_DATE'                               => 'Belastet den',
    'KLARNA_REFUND_AMOUNT'                              => 'Refusjonsbeløp',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Refusjon – Forklaring',
    'KLARNA_REFUND_DATE'                                => 'Erstattet am',
    'KLARNA_CAPTURES'                                   => 'Trekk',
    'KLARNA_REFUNDS'                                    => 'Refusjoner',
    'KLARNA_CANCEL_ORDER'                               => 'Avbestille bestillingen',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Bestillingen ble kansellert. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Åpne denne bestillingen i Klarna-portalen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Oppmerksomhet!</strong> Opplysningene i denne bestillingen avviker fra opplysningene som er lagret hos Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Oppmerksomhet! På grunn av den nåværende bestillingsstatusen kan denne endringen ikke sendes til Klarna. Utfør eventuelt den aktuelle endringen manuelt direkte i Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Oppmerksomhet! Klarna har ikke kunnet behandle de siste endringene du har gjort i denne bestillingen (årsak: %s). Vennligst tilbakekall de siste endringene i OXID eShop, eller foreta den nødvendige justeringen manuelt i Klarna Merchant Portal om nødvendig.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Ugyldig forespørsel. Kontroller innstillingene for Klarna-modulen, Merchant-ID-en og det tilhørende passordet',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Denne bestillingen ble ikke funnet i Klarnas system. Endringer i bestillingsopplysningene vil derfor ikke bli overført til Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Feil påloggingsopplysninger!</strong> Denne bestillingen ble lagt inn med forhandler-ID-en <strong>%s</strong>. Den forhandler-ID-en som for øyeblikket er konfigurert for <strong>%s</strong>, er <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Produktnavn',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymisert produkttittel:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Betalingen håndteres av vår samarbeidspartner Klarna. Vennligst følg betalingsinformasjonen du har mottatt fra Klarna. Du kan administrere alle kjøpene dine via Klarna.com eller Klarna-appen, og til og med betale med bare ett klikk.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Rabattkupong',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Gaveinnpakning',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Gratulasjonskort',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Alvorlig feil: Det er obligatorisk å oppgi en gyldig SSL-beskyttet (https) $this-&gt;sSSLShopURL i config.inc.php-filen til nettbutikken din hvis du ønsker å aktivere %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Feil påloggingsopplysninger!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Beløpet er trukket fra kontoen.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Betalingen for bestillingen kunne ikke trekkes, siden den allerede var kansellert.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Skriv inn tekststrengen her som skal sendes til Klarna i stedet for den faktiske produkttittelen.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Endringene du gjør i denne bestillingen blir ikke overført til Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Brukerhåndbok',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrer deg',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Les mer',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Støttede kundetyper',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Her kan du angi om nettbutikken skal akseptere utelukkende B2C-transaksjoner (standardinnstilling), kun B2B-transaksjoner eller både B2C- og B2B-transaksjoner.<br />  Merk: Etter at kundetypene er endret, må nettleserens sesjonscache tømmes for at betalingen skal kunne testes.',
    'TCKLARNA_B2C'                                      => 'Kun B2C-kunder',
    'TCKLARNA_B2B'                                      => 'Kun B2B-kunder',
    'TCKLARNA_B2B_B2C'                                  => 'Hovedsakelig B2B-kunder, men også B2C-kunder',
    'TCKLARNA_B2C_B2B'                                  => 'Hovedsakelig B2C-kunder, men også B2B-kunder',
    'TCKLARNA_NEED_SUPPORT'                             => 'Trenger du hjelp med integrasjonen?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Ta kontakt med Klarnas kundestøtte for forhandlere',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Meldinger på stedet',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Her kan du konfigurere On-Site Messaging for bruk sammen med Klarna-modulen for OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Manus',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion – Produktdetaljsiden',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Kredittkampanje Handlekurv',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Kampanje på toppstripen',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Kampanje i bunnteksten',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Banner-kampanje',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Vennligst sett inn JavaScript-bibliotekets kodebit her, som er nødvendig for On-Site Messaging, og som du finner i Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Vennligst sett inn plasseringskoden her for å markedsføre finansiering og avbetalingskjøp gjennom Credit Promotions på produktdetaljsiden',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Vennligst sett inn «Placement Tag» her for å markedsføre finansiering og avbetalingskjøp gjennom Credit Promotions på oversikten over handlekurven',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Vennligst sett inn plasseringskoden her for å fremheve generell informasjon og informasjon om betalingsmåter på nettbutikkens startside',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Vennligst sett inn Placement-taggen her for å vise de tilgjengelige Klarna-betalingsmåtene i bunnteksten på nettbutikken',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Vennligst sett inn plasseringskoden her for å legge inn et banner på butikkens startside',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Hva er On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Kundene er ikke alltid klar over de ulike kreditt- og finansieringsmulighetene som står til rådighet før de kommer til kassen. Finansieringsmuligheter som presenteres tidlig, påvirker kjøpsbeslutningen. 

On-Site Messaging er enkelt og problemfritt å integrere og tilbyr skreddersydd informasjon, alt fra generelle bannere som fremhever samarbeidet med Klarna og muligheten for avbetaling, til personlige kredittilbud på produkt- eller handlekurvsider.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Du finner</a> mer informasjon om hvordan du kommer i gang <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">her</a>:<br /><br /> 
Logg inn på <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">forhandlerportalen</a> for å generere din personlige JavaScript- og plasseringskode. On-Site-Messaging aktiveres i nettbutikken din så snart JavaScript-koden er lagret og minst én plasseringskode er lagt inn.<br /> 
Du kan når som helst deaktivere funksjonen ved å fjerne kodene.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Forhandlerportal',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktiver Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktiv',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Skifte ut knappen «Key»',
    'TCKLARNA_IS_REPLACE'                               => 'Opprett en ny knapp «Key»',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Du kan oppdatere Button Key hvis konfigurasjons- eller identifikasjonsdataene fra Klarnas side krever en endring. Normalt kan du bruke en Button Key så lenge du ønsker, etter at den er opprettet.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Aktiver Klarna Instant Shopping her. Da opprettes det automatisk en knapp som kan brukes i nettbutikkens frontend.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Innstillinger for utforming av knapper',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vennligst velg mellom en knapp som er fullstendig merket med Klarna-designet og en mer nøytral «Light»-variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Vennligst velg om skriftfargen på slagordet under knappen skal være lys eller mørk.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vennligst velg ønsket tekst på knappen.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Forhåndsvisning av knappen',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Vis på artikkeloversikten',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Aktiver denne funksjonen for at Klarna Instant Shopping-knappen skal vises på alle varedetaljsidene i nettbutikken din.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Vis i handlekurven',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Aktiver denne funksjonen for at Klarna Instant Shopping-knappen skal vises i handlekurvoversikten i nettbutikken din.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Flere innstillinger for Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Leveringsadressen kan avvike fra fakturaadressen',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Hvis levering til en annen leveringsadresse skal være mulig, må du aktivere denne bryteren.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Fødselsdato som obligatorisk felt',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Hvis du ønsker å gjøre det obligatorisk å oppgi fødselsdato, må du aktivere denne bryteren. Normalt er fødselsdato ikke et obligatorisk felt hos Klarna. Opplysningen er imidlertid nødvendig for å kunne tilby kjøp på faktura eller avbetaling.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Nasjonalt ID-nummer som obligatorisk felt',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Vennligst velg om det nasjonale identifikasjonsnummeret skal være et obligatorisk felt.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variasjon',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slagord',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefonnummer er et obligatorisk felt',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Vennligst velg om telefonnummeret skal være et obligatorisk felt.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Vennligst velg fra listen hvilket land som skal være standardvalg når Klarna Instant Shopping åpnes, så lenge kunden ikke har oppgitt sitt land ennå.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Oppgi URL-adressen til dine generelle forretningsvilkår her. Det vil bli lagt inn en lenke til disse i Klarna Instant Shopping-popup-vinduet. Du må oppgi en gyldig URL-adresse som begynner med https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Fraktalternativer',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Krediter hele bestillingen',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Det ble ikke funnet noen aktive leveringsmåter',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Brukt betalingsmåte: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kredittkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Direktebelastning',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Direkteoverføring',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rentefrie avdrag',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finansiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Kortbetaling innen 30 dager',
];
