<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Italiano";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Inizio',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'In generale',
    'TCKLARNA_CONFIGURATION'                            => 'Configurazione',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configurazione per i pagamenti Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Impostazioni di design',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Metodi di pagamento esterni',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ulteriori informazioni sul rivenditore',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Impostazioni di base',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Sconto',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'In questa modalità non sono disponibili impostazioni.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Tutte le impostazioni sono state salvate.',

    'TCKLARNA_EASY'                                     => 'Attivare Klarna è semplicissimo',
    'TCKLARNA_PHONE'                                    => 'Telefono',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Orari di apertura',
    'TCKLARNA_MONDAY'                                   => 'Lunedì',
    'TCKLARNA_TUESDAY'                                  => 'martedì',
    'TCKLARNA_WEDNESDAY'                                => 'mercoledì',
    'TCKLARNA_THURSDAY'                                 => 'Giovedì',
    'TCKLARNA_FRIDAY'                                   => 'Venerdì',
    'TCKLARNA_SATURDAY'                                 => 'Sabato',
    'TCKLARNA_SUNDAY'                                   => 'Domenica',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Le vostre credenziali di accesso specifiche per paese',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Aggiungere le credenziali di accesso specifiche per paese',
    'TCKLARNA_COUNTRY'                                  => 'Paese',
    'TCKLARNA_MERCHANT_ID'                              => 'Nome utente API',
    'TCKLARNA_PASSWORD'                                 => 'Password API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID commerciante',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Paese predefinito del negozio',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Registrazione attiva',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Inviare dati aggiuntivi sul prodotto a Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL dei prodotti',
    'TCKLARNA_IMAGE_URLS'                               => 'URL delle immagini',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Rendere anonimo',
    'TCKLARNA_ADD'                                      => 'Aggiungi',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Pagamenti Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Selezionare la modalità del modulo Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Con Klarna i clienti finali possono pagare in tre modi: bonifico immediato, in un secondo momento o a rate. Ciò consente ai clienti finali di provare prima la merce e pagare solo ciò che desiderano tenere, di finanziare i prodotti acquistati nel negozio o di pagare immediatamente. Fattura, acquisto rateale, bonifico immediato o addebito diretto possono essere attivati tramite un’integrazione e, grazie alla soluzione iFrame di Klarna, sono sempre aggiornati dal punto di vista legale e dei contenuti.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'I metodi di pagamento più diffusi. Sicuri e facili da integrare.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Benvenuti nelle impostazioni di configurazione di Klarna Payments. Qui troverete tutto il necessario per l\'attivazione. Selezionate le voci del sottomenu Klarna nella barra a sinistra per completare la configurazione del modulo.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Creare un account cliente nell\'OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Iscrizione alla newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Crea un account cliente E iscriviti alla newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Non visualizzare la casella di selezione',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Mostrare nella pagina iniziale dello shop?',
    'TCKLARNA_BANNER_SRC'                               => 'Fonte del banner Klarna',
    'TCKLARNA_FOOTER'                                   => 'Piè di pagina',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Cosa deve essere visualizzato nel piè di pagina?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visualizzazione dei metodi di pagamento',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo Klarna',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Versione lunga:',
    'TCKLARNA_SHORT_VERSION'                            => 'Versione breve:',
    'TCKLARNA_WHITE'                                    => 'Bianco:',
    'TCKLARNA_BLACK'                                    => 'Nero:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Pagina dei dettagli dell\'articolo e carrello',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Visualizzare il widget del metodo di pagamento Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Nella pagina dei dettagli dell\'articolo',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Nella pagina del carrello',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Mostrare il pulsante "Acquista ora"?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opzioni di design per i pagamenti Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Impostazioni colore:',
    'TCKLARNA_BORDER'                                   => 'Confine:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Confine selezionato:',
    'TCKLARNA_BUTTON'                                   => 'Pulsante:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Testo del pulsante:',
    'TCKLARNA_CHECKBOX'                                 => 'Casella di selezione:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Casella di selezione spuntata:',
    'TCKLARNA_DETAILS'                                  => 'Dettagli:',
    'TCKLARNA_HEADER'                                   => 'Intestazione:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Testo:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Testo aggiuntivo:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Regolazione del raggio:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Raggio del bordo:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'L\'indirizzo di consegna può essere diverso dall\'indirizzo di fatturazione',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Il numero di telefono è un campo obbligatorio',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'La data di nascita è un campo obbligatorio',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Attivare la consegna presso un punto di ritiro DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Attiva il pre-riempimento',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Attiva l\'avviso di precompilazione',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Il campo "Titolo" è obbligatorio',
    'TCKLARNA_SET_TAC_URI'                              => 'URL delle vostre condizioni generali di contratto',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL relativo al diritto di recesso',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Dettagli sulla spedizione',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Nessuna convalida',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Eseguire la convalida, ma ignorare i timeout',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'È necessaria una validazione riuscita',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Conferma dell\'ordine',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Selezionate le opzioni di pagamento Klarna che desiderate offrire ai vostri clienti:',
    'TCKLARNA_PAY_LATER'                                => 'Fattura',
    'TCKLARNA_PAY_LATER.'                               => 'Fattura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Per i clienti che desiderano acquistare ora e pagare in un secondo momento. In tutta comodità entro 14, 21 o 28 giorni, a seconda del mercato.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'L\'opzione “Fattura” rende la procedura di pagamento semplice e veloce per i clienti, senza che questi debbano inserire dati personali o codici complicati. Il cliente può scegliere tra la fattura e il pagamento nel mese X.',
    'TCKLARNA_SLICE_IT'                                 => 'Acquisto a rate.',
    'TCKLARNA_SLICE_IT.'                                => 'Pagare a rate.',
    'TCKLARNA_SLICE_IT_START'                           => 'Aumentate il potere d\'acquisto dei vostri clienti grazie al pagamento a rate. I clienti possono saldare i propri acquisti con rate mensili fisse in un periodo compreso tra 6 e 36 mesi.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Grazie all’“acquisto rateale”, i clienti possono suddividere l’importo dell’acquisto in rate a tassi di interesse contenuti. Ciò aumenta il margine di investimento e il potere d’acquisto. L’esclusiva procedura di concessione del credito di Klarna richiede solo pochi istanti e l’inserimento di un numero minimo di dati.',
    'TCKLARNA_PAY_NOW'                                  => 'Paga subito',
    'TCKLARNA_PAY_NOW.'                                 => 'Paga subito.',
    'TCKLARNA_PAY_NOW_START'                            => 'Pagamenti diretti semplici e veloci con la funzione “Paga subito” di Klarna. In Germania, il portafoglio di opzioni di pagamento non dovrebbe tralasciare il bonifico immediato, la carta di credito e l’addebito diretto.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'I clienti che desiderano pagare l\'intero importo immediatamente al momento del completamento dell\'ordine possono utilizzare l\'opzione "Paga subito". È possibile scegliere tra carta di credito, addebito diretto e bonifico immediato.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Guida su come<br /> attivare Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Nel backend di OXID, clicca sulla nuova voce di menu "Klarna", poi sulla sottocategoria "Generale" e infine seleziona il prodotto Klarna desiderato.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Inserisci le tue credenziali di accesso (nome utente e password) e configura le impostazioni tipiche di OXID relative ai metodi di pagamento nelle sezioni Impostazioni negozio &gt; Metodi di pagamento e &gt; Metodi di spedizione.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Salvare le modifiche.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Ora sei online e puoi iniziare a vendere con Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Assistenza ai commercianti',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Qui è possibile configurare se, se necessario, i dati aggiuntivi del commerciante debbano essere trasmessi a Klarna. 
Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leggere il <a class="cl-pink" href="%s" target="_blank">manuale</a> 
oppure contattare l\'assistenza per l\'integrazione con Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Qui è possibile configurare le impostazioni di design da utilizzare con il modulo Klarna per l\'eShop OXID. 
Per una descrizione dettagliata delle diverse impostazioni, si prega di consultare i suggerimenti 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leggere il <a class="cl-pink" href="%s" target="_blank">manuale</a> 
oppure contattare l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Qui potete effettuare la selezione relativa a Klarna Payments e configurare le impostazioni generali. 
Per una descrizione dettagliata delle diverse impostazioni, consultate i suggerimenti 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leggete il <a class="cl-pink" href="%s" target="_blank">manuale</a> 
oppure contattate l\'assistenza per l\'integrazione di Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'In questa pagina è possibile selezionare quali metodi di pagamento Klarna si desidera offrire. 
Per una descrizione dettagliata delle diverse impostazioni, consultare i suggerimenti 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leggere il <a class="cl-pink" href="%s" target="_blank">manuale</a> 
oppure contattare l\'assistenza per l\'integrazione di Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Modalità di pagamento',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Metodo di pagamento esterno',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI dell\'immagine per il metodo di pagamento esterno',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Dimensioni dell\'immagine: 69x24 pixel',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Dimensioni dell\'immagine: 276x48 pixel',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'È possibile consultare qui il manuale d\'uso del modulo Klarna per OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manuale d\'uso',

    'TCKLARNA_CHOOSE'                                   => 'Selezionare',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informazioni sull\'account cliente',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Cronologia completa dei pagamenti',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Campo di passaggio',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Assegnare il tipo di pagamento:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Quali ordini devono essere inclusi nella cronologia dei pagamenti completa?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Considerare tutti gli ordini come pagati, indipendentemente dalla data di Oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Inviare solo gli ordini con data oxpaid impostata; ignorare gli ordini non pagati',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignora tutti gli ordini effettuati con questa modalità di pagamento',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Altra opzione di pagamento',
    'TCKLARNA_DIRECT_BANKING'                           => 'Bonifico immediato',
    'TCKLARNA_CARD'                                     => 'Mappa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Scegliere tra Playground (ambiente di test) e Live (ambiente di produzione). Attivare l\'ambiente di produzione solo dopo aver eseguito con successo i test di integrazione e previa consultazione con il proprio Integration Manager di Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Inserisci qui le tue credenziali di accesso all\'API di Klarna. Le hai ricevute nell\'e-mail di benvenuto inviata da Klarna. Questo nome utente e questa password sono validi a livello globale per tutti i paesi. Solo nel caso in cui tu abbia ricevuto credenziali di accesso diverse per paesi diversi, puoi aggiungerle più in basso.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Inserisci qui la password corrispondente al nome utente API che stai utilizzando. Hai ricevuto questa password nell\'e-mail di benvenuto inviata da Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Inserisci qui il tuo ID commerciante Klarna. Lo hai ricevuto nell\'e-mail di benvenuto inviata da Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Selezionare dalla lista a sinistra il Paese per il quale ha ricevuto le credenziali di accesso specifiche di Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Si prega di inserire qui il nome utente corrispondente a questo Paese.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Inserisca qui la password corrispondente a questo Paese.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Si prega di inserire qui l\'ID commerciante corrispondente a questo Paese.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Attiva la funzione di log in modo che tutte le comunicazioni API con Klarna vengano registrate nella tabella MySQL tcklarna_logs. Ciò può risultare utile per l\'analisi o la ricerca degli errori. In ambiente di produzione, la funzione dovrebbe essere disattivata, poiché altrimenti potrebbero accumularsi grandi quantità di log e venire memorizzati dati sensibili.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Inviate a Klarna gli URL delle pagine di dettaglio dei prodotti presenti nel carrello dei vostri clienti, in modo che Klarna possa successivamente inserire i link ai vostri articoli dal portale Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Inviate a Klarna gli URL delle immagini degli articoli presenti nel carrello dei vostri clienti, in modo che Klarna possa visualizzarle sul portale Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Attiva l\'anonimizzazione per nascondere a Klarna i nomi degli articoli presenti nel carrello dei tuoi clienti. Questa operazione è consigliata, ad esempio, per le farmacie online, ma deve essere effettuata solo previa consultazione con il responsabile dell\'integrazione di Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Se si desidera consentire la consegna a un indirizzo di consegna diverso, attivare questo pulsante.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Se desiderate rendere obbligatorio l\'inserimento di un numero di telefono, attivate questo pulsante. Normalmente, per Klarna il numero di telefono non è un campo obbligatorio.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Se desiderate rendere obbligatoria l\'indicazione della data di nascita, attivate questo pulsante. Normalmente, per Klarna la data di nascita non è un campo obbligatorio. Tuttavia, tale informazione è necessaria per consentire l\'acquisto con pagamento tramite fattura o a rate.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Al momento non implementato',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Inserisci qui l\'URL della tua pagina web contenente l\'informativa sul diritto di recesso. L\'URL deve iniziare con https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Queste informazioni sulla spedizione vengono mostrate al cliente nella pagina di conferma al termine dell\'ordine.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Assegnare questo metodo di pagamento esterno a uno dei metodi di pagamento predefiniti',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Si prega di indicare un URL per tutte le lingue',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Si prega di inserire un URL valido che inizi con https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Questo pulsante attiva la trasmissione di dati aggiuntivi a Klarna; in questo caso si tratta delle informazioni relative all\'account del cliente, che includono la data di registrazione dell\'account e quella dell\'ultima modifica.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Questo pulsante attiva l\'invio di dati aggiuntivi a Klarna, in questo caso la "Payment History Full", che contiene gli acquisti effettuati finora dal cliente.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Si prega di indicare a quale tipo di pagamento corrisponde questo metodo di pagamento.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Si prega di specificare qui se e, eventualmente, quali ordini effettuati con questa modalità di pagamento debbano essere inclusi nel trasferimento della cronologia degli ordini del cliente. La dipendenza del campo OXORDER.OXPAID indica se debbano essere considerati solo gli ordini pagati o tutti gli ordini.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'È possibile trasmettere a Klarna ulteriori dati a propria scelta tramite un campo "pass-through". Per utilizzare questa funzione, è necessario installare nell\'OXID eShop un modulo apposito che inserisca i dati desiderati nel campo "pass-through". Le istruzioni relative sono disponibili nella documentazione per sviluppatori.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Con questo pulsante è possibile attivare un banner Klarna sulla pagina iniziale del negozio nel tema predefinito Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Qui è possibile inserire il tag script per l\'integrazione del banner. Nel portale dei banner di Klarna potrete trovare, se necessario, altri banner tra cui scegliere.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Con questo pulsante è possibile attivare la visualizzazione del metodo di pagamento Klarna nel piè di pagina del proprio negozio nel tema predefinito Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Con questo pulsante è possibile inserire il logo Klarna nel piè di pagina del proprio negozio nel tema predefinito Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Questo interruttore inserisce un pulsante "Acquista ora" nelle pagine di dettaglio degli articoli del tuo negozio nel tema predefinito Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Colore della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse opzioni secondarie.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Colore della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse sotto-opzioni. Questo valore di colore viene utilizzato per evidenziare la sotto-opzione attualmente selezionata.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Colore di sfondo dei pulsanti di opzione che compaiono nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, nel caso in cui siano disponibili diverse opzioni secondarie',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Colore dei simboli di elenco nella visualizzazione dei dettagli di pagamento nella pagina di selezione dei metodi di pagamento.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Al momento della pubblicazione di questo modulo, questa impostazione non ha ancora alcun effetto.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Colore dei link nella descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Colore del testo della descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Colore alternativo del testo della descrizione dettagliata delle modalità di pagamento nella pagina di selezione delle modalità di pagamento.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Con questa impostazione è possibile definire il grado di arrotondamento della cornice che appare nel frontend del negozio dopo aver selezionato il metodo di pagamento Klarna, a seconda delle diverse sotto-opzioni disponibili.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Questa scheda riguarda solo gli ordini effettuati tramite Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Acquisizione dell\'ordine completo',
    'KLARNA_CAPTURE_ID'                                 => 'ID addebito',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Riferimento Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Importo dell\'addebito',
    'KLARNA_CAPTURE_DATE'                               => 'Addebitato il',
    'KLARNA_REFUND_AMOUNT'                              => 'Importo del rimborso',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Rimborso - Spiegazione',
    'KLARNA_REFUND_DATE'                                => 'Sostituito da',
    'KLARNA_CAPTURES'                                   => 'Addebiti',
    'KLARNA_REFUNDS'                                    => 'Rimborsi',
    'KLARNA_CANCEL_ORDER'                               => 'Annulla l\'ordine',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'L\'ordine è stato annullato. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Visualizza questo ordine sul portale Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Attenzione!</strong> I dati di questo ordine non corrispondono a quelli registrati presso Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Attenzione! A causa dello stato attuale dell\'ordine, questa modifica non può essere trasmessa a Klarna. Se necessario, effettua manualmente la modifica corrispondente direttamente nel Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Attenzione! Klarna non è riuscita a elaborare le ultime modifiche apportate a questo ordine (motivo: %s). Si prega di annullare le modifiche recenti nell\'eShop OXID oppure, se necessario, di apportare manualmente le modifiche del caso nel Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Richiesta non autorizzata. Verificare le impostazioni del modulo Klarna, l\'ID commerciante e la relativa password',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Questo ordine non è stato trovato nel sistema di Klarna. Pertanto, le modifiche apportate ai dati dell\'ordine non verranno trasmesse a Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Dati di accesso errati!</strong> Questo ordine è stato effettuato utilizzando l\'ID rivenditore <strong>%s</strong>. L\'ID rivenditore attualmente configurato per <strong>%s</strong> è <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nome del prodotto',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Titolo del prodotto in forma anonima:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Il pagamento viene gestito dal nostro partner Klarna. Si prega di prendere visione delle informazioni di pagamento inviate da Klarna. È possibile gestire tutti i propri acquisti su Klarna.com o tramite l\'app Klarna e persino effettuare il pagamento con un solo clic.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Buono sconto',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Confezione regalo',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Biglietto di auguri',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Errore fatale: è obbligatorio specificare un URL $this-&gt;sSSLShopURL valido e protetto da SSL (https) nel file config.inc.php del vostro negozio se desiderate attivare l\'%s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Dati di accesso errati!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'L\'importo è stato addebitato con successo.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Non è stato possibile addebitare l\'ordine, poiché era già stato annullato.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Inserisci qui la stringa di testo che deve essere inviata a Klarna al posto del titolo effettivo del prodotto.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Le modifiche apportate a questo ordine non verranno trasmesse a Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manuale d\'uso',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrati',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Per saperne di più',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tipi di clienti supportati',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Qui è possibile impostare se il negozio debba accettare esclusivamente transazioni B2C (impostazione predefinita), solo transazioni B2B oppure sia transazioni B2C che B2B.<br />  Nota: dopo aver modificato i tipi di cliente, è necessario svuotare la cache della sessione del browser per poter testare il pagamento.',
    'TCKLARNA_B2C'                                      => 'Solo clienti B2C',
    'TCKLARNA_B2B'                                      => 'Solo clienti B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Principalmente clienti B2B, ma anche clienti B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Principalmente clienti B2C, ma anche clienti B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Avete bisogno di aiuto per l\'integrazione?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contatta l\'assistenza commercianti di Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Messaggistica in loco',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Qui è possibile configurare la funzione di messaggistica in-site da utilizzare con il modulo Klarna per l\'OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Copione',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Pagina dei dettagli del prodotto "Credit Promotion"',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Promozione crediti Carrello',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promozione "Top-strip"',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promozione a piè di pagina',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promozione con banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Si prega di inserire qui il frammento di codice della libreria JavaScript necessario per la funzione di messaggistica sul sito, che è possibile ottenere dal Portale commercianti di Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Si prega di inserire qui il tag di posizionamento per promuovere il finanziamento e l\'acquisto rateale tramite Credit Promotions nella pagina dei dettagli dell\'articolo',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Si prega di inserire qui il tag di posizionamento per promuovere il finanziamento e l\'acquisto rateale tramite Credit Promotions nella pagina di riepilogo del carrello',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Si prega di inserire qui il tag di posizionamento per promuovere informazioni generiche e specifiche relative ai metodi di pagamento sulla pagina iniziale del negozio',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Inserisci qui il tag di posizionamento per visualizzare i metodi di pagamento Klarna disponibili nel piè di pagina del negozio',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Inserisci qui il tag di posizionamento per inserire un banner sulla pagina iniziale del tuo negozio',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Che cos\'è l\'On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'I clienti non sono sempre a conoscenza delle diverse opzioni di credito e finanziamento a loro disposizione prima di arrivare alla cassa. Le opzioni di finanziamento disponibili in anticipo influenzano la decisione di acquisto. 

L\'On-Site Messaging è semplice e facile da integrare e offre informazioni su misura, che vanno dai banner generici alla promozione della vostra partnership con Klarna e alla disponibilità del pagamento rateale, fino alle promozioni di credito personalizzate sulle pagine dei prodotti o del carrello.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Per</a> ulteriori informazioni su come iniziare, <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">clicca qui</a><br /><br /> 
Accedi al <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">portale</a> <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">per i rivenditori</a> per generare il tuo codice JavaScript e il codice di posizionamento personali. La funzione di messaggistica sul sito verrà attivata nel tuo negozio non appena il codice JavaScript sarà stato salvato e sarà stato inserito almeno un codice di posizionamento.<br /> 
Puoi disattivarla in qualsiasi momento rimuovendo i codici.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portale per i rivenditori',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Attiva Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Attivo',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Sostituire il tasto',
    'TCKLARNA_IS_REPLACE'                               => 'Creare un nuovo pulsante "Key"',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'È possibile aggiornare il Button Key qualora i dati di configurazione o di identificazione da parte di Klarna richiedano una modifica. Di norma, una volta generato, il Button Key può essere utilizzato per tutto il tempo che si desidera.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Attiva qui Klarna Instant Shopping. In questo modo verrà generato automaticamente un pulsante da utilizzare nel frontend del negozio.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Impostazioni di stile dei pulsanti',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Si prega di scegliere tra un pulsante con il marchio Klarna in versione completa e una variante "Light" più neutra.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Selezionare se il colore del testo dello slogan sotto il pulsante deve essere chiaro o scuro.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Selezionare la dicitura desiderata per il pulsante.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Anteprima del pulsante',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Visualizza nella pagina dei dettagli dell\'articolo',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Attiva questa funzione affinché il pulsante Klarna Instant Shopping venga visualizzato su tutte le pagine di dettaglio degli articoli del tuo negozio.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Visualizza nella panoramica del carrello',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Attiva questa funzione affinché il pulsante Klarna Instant Shopping venga visualizzato nella pagina di riepilogo del carrello del tuo negozio.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Altre impostazioni di Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'L\'indirizzo di consegna può essere diverso dall\'indirizzo di fatturazione',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Se si desidera consentire la consegna a un indirizzo di consegna diverso, attivare questo pulsante.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Data di nascita come campo obbligatorio',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Se desiderate rendere obbligatoria l\'indicazione della data di nascita, attivate questo pulsante. Normalmente, per Klarna la data di nascita non è un campo obbligatorio. Tuttavia, tale informazione è necessaria per consentire l\'acquisto con pagamento tramite fattura o a rate.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Il numero di identificazione nazionale è un campo obbligatorio',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Si prega di specificare se il numero di identificazione nazionale deve essere un campo obbligatorio.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variazione',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tipo',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Il numero di telefono è un campo obbligatorio',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Selezionare se il numero di telefono deve essere un campo obbligatorio.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Selezionare dall\'elenco il Paese che deve essere impostato come predefinito all\'apertura di Klarna Instant Shopping, fintanto che il cliente non abbia ancora specificato il proprio Paese.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Inserisci qui l\'URL delle tue Condizioni generali di contratto. Queste saranno collegate tramite link nel pop-up di Klarna Instant Shopping. È necessario inserire un URL valido che inizi con https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Modalità di spedizione',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Accreditare l\'intero importo dell\'ordine',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Non sono state trovate modalità di spedizione attive',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Metodo di pagamento utilizzato: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Carta di credito',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Addebito diretto',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Bonifico immediato',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rate senza interessi',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finanziamento',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Fattura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Fattura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Pagamento con carta entro 30 giorni',
];
