<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Magyar";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Kezdés',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Általános információk',
    'TCKLARNA_CONFIGURATION'                            => 'Konfiguráció',
    'TCKLARNA_CONFIGURATION_KP'                         => 'A Klarna Payments beállítása',
    'TCKLARNA_KLARNADESIGN'                             => 'Tervezési beállítások',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Külső fizetési módok',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'További kereskedői adatok',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Alapbeállítások',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Kedvezmény',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'Ebben a módban nincsenek beállítások.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Minden beállítást elmentettünk.',

    'TCKLARNA_EASY'                                     => 'Ennyire egyszerű a Klarna aktiválása',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Nyitvatartási idő',
    'TCKLARNA_MONDAY'                                   => 'Hétfő',
    'TCKLARNA_TUESDAY'                                  => 'kedd',
    'TCKLARNA_WEDNESDAY'                                => 'szerda',
    'TCKLARNA_THURSDAY'                                 => 'csütörtök',
    'TCKLARNA_FRIDAY'                                   => 'péntek',
    'TCKLARNA_SATURDAY'                                 => 'Szombat',
    'TCKLARNA_SUNDAY'                                   => 'Vasárnap',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Az Ön országára vonatkozó bejelentkezési adatai',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Országspecifikus bejelentkezési adatok hozzáadása',
    'TCKLARNA_COUNTRY'                                  => 'Ország',
    'TCKLARNA_MERCHANT_ID'                              => 'API-felhasználónév',
    'TCKLARNA_PASSWORD'                                 => 'API-jelszó',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Kereskedői azonosító',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Az üzlet alapértelmezett országa',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Naplózás aktív',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Kiegészítő termékadatokat küldjön a Klarnának?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Termék-URL-ek',
    'TCKLARNA_IMAGE_URLS'                               => 'Képek URL-jei',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimizálás',
    'TCKLARNA_ADD'                                      => 'Hozzáadás',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna fizetési módok',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Klarna modul: üzemmód kiválasztása',

    'TCKLARNA_PAYMENTS_DESC'                            => 'A Klarna segítségével a végfelhasználók háromféle módon fizethetnek: azonnali átutalással, későbbi fizetéssel vagy részletfizetéssel. Ez lehetővé teszi számukra, hogy először kipróbálják az árut, és csak azt fizessék ki, amit megtartanak, illetve hogy a termékeket az üzletben részletfizetéssel vagy azonnali fizetéssel szerezhessék be. A számla, a részletfizetés, az azonnali átutalás vagy a beszedési megbízás egy integrációval aktiválható, és a Klarna iFrame-megoldásának köszönhetően jogi és tartalmi szempontból mindig naprakészek.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'A legnépszerűbb fizetési módok. Biztonságosak és könnyen integrálhatók.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Üdvözöljük a Klarna Payments konfigurációs beállításaiban! Itt megtalálja mindazt, ami az aktiváláshoz szükséges. A bal oldali sávban válassza ki a Klarna almenüpontokat a modul beállításának befejezéséhez.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Fiók létrehozása az OXID eShopban',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Hírlevél-feliratkozás',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Felhasználói fiók létrehozása ÉS hírlevélre való feliratkozás',
    'TCKLARNA_NO_CHECKBOX'                              => 'Ne jelenítse meg a jelölőnégyzetet',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Megjelenítse a bolt kezdőlapján?',
    'TCKLARNA_BANNER_SRC'                               => 'Klarna-banner forrása',
    'TCKLARNA_FOOTER'                                   => 'Lábléc',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Mit kell megjeleníteni a láblécben?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'A fizetési módok megjelenítése',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna logó',
    'TCKLARNA_DESIGN'                                   => 'Tervezés',
    'TCKLARNA_LONG_VERSION'                             => 'Hosszú változat:',
    'TCKLARNA_SHORT_VERSION'                            => 'Rövid változat:',
    'TCKLARNA_WHITE'                                    => 'Fehér:',
    'TCKLARNA_BLACK'                                    => 'Fekete:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Termékleírás és kosár',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Megjelenítse a Klarna fizetési mód widgetjét?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'A termék részletes leírásának oldalán',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'A kosár oldalon',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Megjelenítse a „Most vásárol” gombot?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'A Klarna fizetési megoldásainak tervezési lehetőségei',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Színbeállítások:',
    'TCKLARNA_BORDER'                                   => 'Határ:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Kijelölt határ:',
    'TCKLARNA_BUTTON'                                   => 'Gomb:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Gomb szövege:',
    'TCKLARNA_CHECKBOX'                                 => 'Jelölőnégyzet:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Jelölőnégyzet bejelölése:',
    'TCKLARNA_DETAILS'                                  => 'Részletek:',
    'TCKLARNA_HEADER'                                   => 'Fejléc:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Szöveg:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'További szöveg:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Sugár beállítása:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Szélső sugár:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'A szállítási cím eltérhet a számlázási címtől',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'A telefonszám kitöltése kötelező',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'A születési dátum kitöltése kötelező',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'A DHL Packstation-ba történő kézbesítés engedélyezése',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Az előtöltés engedélyezése',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Az előtöltésre vonatkozó figyelmeztetés engedélyezése',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'A megszólítás kitöltése kötelező',
    'TCKLARNA_SET_TAC_URI'                              => 'Az ÁSZF-re mutató URL',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Az elállási jogról szóló URL-cím',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Szállítási részletek',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Nincs érvényesítés',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Végezze el az érvényesítést, de hagyja figyelmen kívül az időtúllépéseket',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Sikeres validálás szükséges',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Rendelés-ellenőrzés',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Kérjük, válassza ki azokat a Klarna fizetési lehetőségeket, amelyeket ügyfeleinek kínálni szeretne:',
    'TCKLARNA_PAY_LATER'                                => 'Számla',
    'TCKLARNA_PAY_LATER.'                               => 'Számla.',
    'TCKLARNA_PAY_LATER_START'                          => 'Azoknak az ügyfeleknek, akik most vásárolnak, de később szeretnének fizetni. Teljesen kényelmesen 14, 21 vagy 28 napon belül, piactól függően.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'A „Számla” opcióval az ügyfelek egyszerűen és gyorsan elintézhetik a fizetést, anélkül, hogy személyes adataikat vagy bonyolult számokat kellene megadniuk. Az ügyfél választhat a számla és az „X hónapban fizet” lehetőségek között.',
    'TCKLARNA_SLICE_IT'                                 => 'Részletfizetés.',
    'TCKLARNA_SLICE_IT.'                                => 'Részletekben fizetni.',
    'TCKLARNA_SLICE_IT_START'                           => 'Növelje ügyfelei vásárlóerejét a részletfizetés lehetőségével. Az ügyfelek 6–36 hónapos időszak alatt, rögzített havi részletekben fizethetik ki vásárlásaikat.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'A „részletfizetés” segítségével az ügyfelek alacsony kamat mellett apránként fizethetik ki a vásárlási összeget. Ez növeli a befektetési keretet és a vásárlóerőt. A Klarna egyedülálló hitelbírálati folyamata csupán néhány pillanatig tart, és minimális adatbevitelt igényel.',
    'TCKLARNA_PAY_NOW'                                  => 'Azonnali fizetés',
    'TCKLARNA_PAY_NOW.'                                 => 'Azonnali fizetés.',
    'TCKLARNA_PAY_NOW_START'                            => 'Egyszerű és gyors közvetlen fizetés a Klarna „Sofort bezahlen” szolgáltatásával. Németországban a Sofortüberweisung, a hitelkártya és a csoportos beszedés nem hiányozhat a fizetési lehetőségek közül.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Azok az ügyfelek, akik a megrendelés lezárásakor azonnal teljes összegben szeretnének fizetni, igénybe vehetik az „Azonnali fizetés” opciót. Ehhez a következő fizetési módok közül választhatnak: hitelkártya, csoportos beszedés és azonnali átutalás.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Útmutató a Klarna<br /> aktiválásához.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Az OXID admin felületén kattintson az új „Klarna” menüpontra, majd az „Általános” alkategóriára, és végül válassza ki a kívánt Klarna-terméket.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Adja meg a bejelentkezési adatait (felhasználónév és jelszó), majd a „Shopeinstellungen” &gt; „Zahlungsarten” és &gt; „Versandarten” menüpontok alatt állítsa be az OXID-ra jellemző fizetési módok hozzárendeléseit.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Mentse el a módosításokat.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Most már online állapotban vannak, és elkezdhetik az értékesítést a Klarna segítségével.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Kereskedői támogatás',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Itt beállíthatja, hogy szükség esetén további kereskedői adatokat (Extra Merchant Data) továbbítson-e a Klarna felé. 
A különböző beállítások részletes leírásához kérjük, olvassa el a segítő szövegeket 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, tanulmányozza át a <a class="cl-pink" href="%s" target="_blank">kézikönyvet</a>, 
vagy forduljon a Klarna integrációs ügyfélszolgálathoz.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Itt konfigurálhatja az OXID eShop Klarna-moduljához tartozó megjelenési beállításokat. 
A különböző beállítások részletes leírásához kérjük, olvassa el a segítő szövegeket 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, tanulmányozza át a <a class="cl-pink" href="%s" target="_blank">kézikönyvet</a>, 
vagy forduljon a Klarna integrációs ügyfélszolgálathoz.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Itt állíthatja be a Klarna Payments beállításait, és végezheti el az általános beállításokat. 
A különböző beállítások részletes leírásához kérjük, olvassa el a segítő szövegeket 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, tanulmányozza át a <a class="cl-pink" href="%s" target="_blank">kézikönyvet</a>, 
vagy forduljon a Klarna integrációs ügyfélszolgálathoz.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Ezen az oldalon kiválaszthatja, mely Klarna fizetési módokat szeretné kínálni. 
A különböző beállítások részletes leírásához kérjük, olvassa el a segítő szövegeket 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, tanulmányozza át a <a class="cl-pink" href="%s" target="_blank">kézikönyvet</a>, 
vagy vegye fel a kapcsolatot a Klarna integrációs ügyfélszolgálattal.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Fizetési mód',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Külső fizetési mód',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Külső fizetési módhoz tartozó kép-URI',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Képméret: 69x24 képpont',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Képméret: 276x48 képpont',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Az OXID eShop Klarna-moduljának felhasználói kézikönyvét itt tekintheti meg.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Felhasználói kézikönyv',

    'TCKLARNA_CHOOSE'                                   => 'Választás',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Ügyfélfiók-adatok',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Teljes fizetési előzmények',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Átadási mező',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'A fizetési mód típusának hozzárendelése:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Mely megrendeléseket kell teljes mértékben figyelembe venni a fizetési előzmények között?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Minden megrendelést kifizetettnek kell tekinteni, függetlenül az Oxpaid dátumtól',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Csak azokat a megrendeléseket küldd el, amelyeknél az oxpaid dátum be van állítva; a ki nem fizetett megrendeléseket hagyd figyelmen kívül',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Az ezzel a fizetési móddal leadott összes megrendelést figyelmen kívül hagyja',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Egyéb fizetési lehetőség',
    'TCKLARNA_DIRECT_BANKING'                           => 'Azonnali átutalás',
    'TCKLARNA_CARD'                                     => 'Térkép',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Válasszon a „Playground” (tesztüzem) és a „Live” (éles üzem) között. Az éles üzemet csak az integrációs tesztek sikeres elvégzése után, valamint a Klarna integrációs menedzserével való egyeztetés után kapcsolja be.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Kérjük, adja meg itt a Klarna API-hozzáférési adatait. Ezeket a Klarna üdvözlő e-mailjében kapta meg. Ez a felhasználónév és jelszó globálisan érvényes minden országra. Csak abban az esetben adhatja hozzá az alábbiakban a különböző országokra vonatkozó hozzáférési adatokat, ha azokat külön kapta meg.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Írja be ide a használt API-felhasználónévhez tartozó jelszavát. Ezt a jelszót a Klarna üdvözlő e-mailjében kapta meg.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Kérjük, adja meg itt a Klarna kereskedői azonosítóját. Ezt a Klarna üdvözlő e-mailjében kapta meg.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Válassza ki a bal oldali listából azt az országot, amelyre vonatkozóan országspecifikus hozzáférési adatokat kapott a Klarnától.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Kérjük, írja be ide az adott országhoz tartozó felhasználónevet.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Kérjük, írja be ide az adott országhoz tartozó jelszót.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Kérjük, írja be ide az adott országhoz tartozó kereskedői azonosítót.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktiválja a naplózási funkciót, hogy a Klarnával folytatott összes API-kommunikációt a mysql tcklarna_logs táblában rögzítsék. Ez hasznos lehet elemzés vagy hibaelhárítás során. Éles üzemmódban a funkciót ki kell kapcsolni, mivel ellenkező esetben nagy mennyiségű naplóadat halmozódhat fel, és érzékeny adatok is tárolódhatnak.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Küldje el a Klarnának azoknak a termékeknek a cikk-részletoldalainak URL-jeit, amelyek az ügyfelei kosarában találhatók, hogy a Klarna később a Klarna portálról hivatkozhasson az Ön termékeire.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Kérjük, küldje el a Klarna számára azoknak a termékeknek a cikkképeinek URL-jeit, amelyek az ügyfelei kosarában találhatók, hogy a Klarna ezeket megjelenítse a Klarna portálon.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Kapcsolja be az anonimizálást, hogy elrejtse a Klarna elől az ügyfelei kosarában található termékek nevét. Ez például online gyógyszertárak esetében ajánlott, de csak a Klarna integrációs menedzserrel való egyeztetés után szabad végrehajtani.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Ha a szállítást egy másik szállítási címre is lehetővé kívánja tenni, jelölje be ezt a jelölőnégyzetet.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Ha feltétlenül megköveteli a telefonszám megadását, kapcsolja be ezt a kapcsolót. Általában a Klarna esetében a telefonszám nem kötelező mező.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Ha feltétlenül megköveteli a születési dátum megadását, jelölje be ezt a jelölőnégyzetet. Általában a Klarna esetében a születési dátum nem kötelező mező. Ugyanakkor ennek megadása szükséges ahhoz, hogy számlás vásárlás vagy részletfizetés lehetséges legyen.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Jelenleg nincs megvalósítva',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Itt adja meg a weboldalának URL-címét, amelyen az elállási jogról szóló tájékoztatás található. Az URL-címnek https://-val kell kezdődnie.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Ezeket a szállítási információkat a megrendelés lezárását követően az „Köszönöm” oldalon jelenítik meg az ügyfél számára.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Rendelje hozzá ezt a külső fizetési módot az előre definiált fizetési módok egyikéhez',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Kérjük, adja meg az összes nyelvhez egy-egy URL-címet',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Kérjük, adjon meg egy érvényes URL-címet, amely https://-val kezdődik',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Ez a kapcsoló engedélyezi a kiegészítő adatok továbbítását a Klarna felé; ebben az esetben az ügyfélfiók-adatokról van szó, amelyek tartalmazzák az ügyfélfiók regisztrációjának dátumát és annak utolsó módosítását.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Ez a kapcsoló engedélyezi a kiegészítő adatok továbbítását a Klarna felé; ebben az esetben a „Payment History Full” adatait, amelyek tartalmazzák az ügyfél eddigi vásárlásait.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Kérjük, jelölje meg, hogy ez a fizetési mód milyen típusú fizetési módnak felel meg.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Kérjük, itt állítsa be, hogy az ügyfél rendelési előzményeinek átvitelekor szerepeljenek-e az ezzel a fizetési móddal teljesített megrendelések, és ha igen, melyek. Az OXORDER.OXPAID mező beállítása határozza meg, hogy csak a kifizetett megrendeléseket, vagy az összes megrendelést vegyék-e figyelembe.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Lehetőség van egy „pass-through” mező segítségével tetszőleges további adatokat továbbítani a Klarna felé. A funkció használatához telepítenie kell az OXID eShopba egy megfelelő modult, amely a kívánt adatokat beírja a „pass-through” mezőbe. A vonatkozó útmutatást a fejlesztői dokumentációban találja meg.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Ezzel a kapcsolóval aktiválhatja a Klarna-bannert az Apex alapértelmezett témában az online áruház kezdőlapján.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Itt adhatja meg a banner beágyazásához szükséges script-címkét. A Klarna banner-portálján szükség esetén további bannerek közül is választhat.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Ezzel a kapcsolóval aktiválhatja a Klarna fizetési mód megjelenítését az Apex alapértelmezett témában az online áruház láblécében.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Ezzel a kapcsolóval beillesztheti a Klarna logót az Apex alapértelmezett témában az online áruház láblécébe.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Ez a kapcsoló egy „Most vásárol” gombot helyez el az Apex alapértelmezett témában az Ön webáruházának termékrészletes oldalain.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'A keret színe, amely – amennyiben különböző alopciók állnak rendelkezésre – a Klarna fizetési mód kiválasztása után jelenik meg a webáruház felületén.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'A keret színe, amely a Klarna fizetési mód kiválasztását követően jelenik meg a webáruház felületén, amennyiben különböző alopciók állnak rendelkezésre. Ezt a színértéket az éppen aktívan kiválasztott alopció kiemelésére használják.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Ez a beállítás a modul közzétételének időpontjában még nem jár semmilyen hatással.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Ez a beállítás a modul közzétételének időpontjában még nem jár semmilyen hatással.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'A rádiógombok háttérszíne, amelyek akkor jelennek meg a webáruház felületén, ha a Klarna fizetési mód kiválasztása után különböző alopciók közül lehet választani',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Ez a beállítás a modul közzétételének időpontjában még nem jár semmilyen hatással.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'A fizetési módok kiválasztási oldalon a fizetési részletek megjelenítésekor a felsorolási jelek színe.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Ez a beállítás a modul közzétételének időpontjában még nem jár semmilyen hatással.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'A fizetési módok kiválasztási oldalon található fizetési módok részletes leírásában szereplő linkek színe.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'A fizetési módok kiválasztási oldalon található fizetési módok részletes leírásának szövegszíne.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'A fizetési módok kiválasztási oldalon található fizetési módok részletes leírásának alternatív szövegszíne.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Ezzel a beállítással megadhatja a keret lekerekítésének mértékét, amely a Klarna fizetési mód kiválasztása után a webáruház felületén megjelenő különböző alopciók esetén látható.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Ez a fül kizárólag a Klarna-n keresztül leadott megrendelésekre vonatkozik',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'A teljes megrendelés rögzítése',
    'KLARNA_CAPTURE_ID'                                 => 'Terhelési azonosító',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna hivatkozás',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Terhelési összeg',
    'KLARNA_CAPTURE_DATE'                               => 'Terhelés dátuma:',
    'KLARNA_REFUND_AMOUNT'                              => 'Visszatérítés összege',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Visszatérítés – Magyarázat',
    'KLARNA_REFUND_DATE'                                => 'Helyettesítve:',
    'KLARNA_CAPTURES'                                   => 'Terhelések',
    'KLARNA_REFUNDS'                                    => 'Visszatérítések',
    'KLARNA_CANCEL_ORDER'                               => 'Megrendelés törlése',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'A megrendelést törölték. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Ezt a megrendelést a Klarna portálon megtekinteni</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Figyelem!</strong> A megrendelés adatai eltérnek a Klarna rendszerében tárolt adatoktól. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Figyelem! A megrendelés jelenlegi állapota miatt ezt a módosítást nem lehet továbbítani a Klarna felé. Szükség esetén kérjük, végezze el a megfelelő módosítást kézzel közvetlenül a Klarna Merchant Portal felületén.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Figyelem! A Klarna nem tudta feldolgozni a megrendelésen végzett legutóbbi módosításait (ok: %s). Kérjük, vonja vissza a legutóbbi módosításait az OXID eShopban, vagy szükség esetén végezze el a megfelelő módosítást manuálisan a Klarna Merchant Portálon.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Nem engedélyezett kérés. Ellenőrizze a Klarna modul beállításait, a kereskedői azonosítót (Merchant ID) és a hozzá tartozó jelszót.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Ezt a megrendelést nem sikerült megtalálni a Klarna rendszerében. A megrendelési adatok módosításai ezért nem kerülnek továbbításra a Klarna felé.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Helytelen bejelentkezési adatok!</strong> Ezt a megrendelést a <strong>%s</strong> kereskedői azonosítóval adták le. A <strong>%s</strong> weboldalra jelenleg beállított kereskedői azonosító a <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Terméknév',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonimizált termékcím:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'A fizetést partnerünk, a Klarna bonyolítja le. Kérjük, vegye figyelembe a Klarna által elküldött fizetési információkat. A Klarna.com oldalon vagy a Klarna alkalmazásban kezelheti az összes vásárlását, sőt, akár egyetlen kattintással is fizethet.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Kedvezményes utalvány',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Ajándékcsomagolás',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Üdvözlőkártya',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Kritikus hiba: Az %s oldal aktiválásához kötelező megadni egy érvényes, SSL-titkosítású (https) $this-&gt;sSSLShopURL értéket az áruház config.inc.php fájljában!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Helytelen bejelentkezési adatok!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Az összeg sikeresen levonásra került.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' A megrendelés összegét nem lehetett levonni, mivel azt már törölték.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Írja be ide azt a karakterláncot, amelyet a tényleges termékcím helyett a Klarna felé kell elküldeni.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'A megrendelésen végzett módosításai nem kerülnek továbbításra a Klarna felé.',
    'TCKLARNA_USER_GUIDE'                               => 'Felhasználói kézikönyv',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Regisztráció',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'További információk',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Támogatott ügyféltípusok',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Itt beállíthatja, hogy az áruház kizárólag B2C tranzakciókat (alapértelmezett beállítás), csak B2B tranzakciókat, vagy mind B2C, mind B2B tranzakciókat fogadjon-e el.<br />  Megjegyzés: Az ügyféltípusok átállítása után törölni kell a böngésző munkamemóriáját, hogy a fizetési folyamatot tesztelni lehessen.',
    'TCKLARNA_B2C'                                      => 'Kizárólag B2C-ügyfelek',
    'TCKLARNA_B2B'                                      => 'Kizárólag B2B-ügyfelek',
    'TCKLARNA_B2B_B2C'                                  => 'Főként B2B-ügyfelek, de B2C-ügyfelek is',
    'TCKLARNA_B2C_B2B'                                  => 'Főként B2C-ügyfelek, de B2B-ügyfelek is',
    'TCKLARNA_NEED_SUPPORT'                             => 'Segítségre van szüksége az integrációval kapcsolatban?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Vegye fel a kapcsolatot a Klarna kereskedői ügyfélszolgálatával',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Helyszíni üzenetküldés',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Itt konfigurálhatja az OXID eShop Klarna-moduljához használható helyszíni üzenetküldést.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Forgatókönyv',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion termékleírás oldala',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Hitelpromóciós kosár',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Top-strip promóció',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Láblécen megjelenő promóció',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Banner-promóció',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Kérjük, illessze be ide az On-Site Messaginghez szükséges JavaScript-könyvtár kódrészletét, amelyet a Klarna Merchant Portálon talál.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Kérjük, illessze be ide a Placement-címkét, hogy a termékrészletek oldalon népszerűsítse a Credit Promotions által kínált finanszírozási lehetőségeket és részletfizetési lehetőségeket.',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Kérjük, illessze be ide a Placement-címkét, hogy a kosár áttekintésén népszerűsítse a Credit Promotions által kínált finanszírozási lehetőségeket és részletfizetési lehetőségeket.',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Kérjük, illessze be ide a Placement-címkét, hogy az áruház kezdőlapján hirdethesse az általános és a fizetési módokra vonatkozó információkat',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Kérjük, illessze be ide a Placement-címkét, hogy az áruház láblécében megjelenjenek a rendelkezésre álló Klarna fizetési módok',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Kérjük, illessze be ide a Placement-címkét, hogy egy banner jelenjen meg az online áruház kezdőlapján',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Mi az az on-site üzenetküldés?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Az ügyfelek nem mindig ismerik a rendelkezésükre álló különböző hitel- és finanszírozási lehetőségeket, mielőtt a pénztárhoz érnek. A vásárlás során korán felkínált finanszírozási lehetőségek befolyásolják a vásárlási döntést. 

Az On-Site Messaging egyszerűen és problémamentesen integrálható, és személyre szabott információkat nyújt, amelyek az általános bannerektől kezdve a Klarna-val való partnerség népszerűsítésén és a részletfizetés lehetőségén át egészen a termék- vagy kosároldalakon megjelenő személyre szabott hitelakciókig terjednek.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'További információkat az első lépésekről <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">itt talál</a><br /><br /><a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">:</a> 
Jelentkezzen be a <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">kereskedői portál</a>ra, hogy létrehozza a személyes JavaScript- és elhelyezési kódját. Az On-Site-Messaging funkció akkor aktiválódik az Ön webáruházában, amint a JavaScript-kódot elmentette, és legalább egy elhelyezési kódot megadott.<br /> 
A funkciót bármikor kikapcsolhatja, ha eltávolítja a kódokat.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Kereskedői portál',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'A Klarna Instant Shopping aktiválása',
    'TCKLARNA_IS_ENABLED'                               => 'Aktív',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'A „Button Key” gomb cseréje',
    'TCKLARNA_IS_REPLACE'                               => 'Új „Button Key” létrehozása',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Frissítheti a Button Key-t, ha a Klarna oldalán változás miatt módosítani kell a konfigurációs vagy azonosítási adatokat. Általában az egyszer létrehozott Button Key-t addig használhatja, ameddig csak szeretné.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Itt kapcsolja be a Klarna Instant Shopping szolgáltatást. Ezzel automatikusan létrehozódik egy gombkód, amelyet a webáruház felhasználói felületén használhat.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Gombok stílusbeállításai',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Kérjük, válasszon a teljes mértékben a Klarna arculatát tükröző gomb és egy semlegesebb, „Light” változat között.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Kérjük, válassza ki, hogy a gomb alatti szlogen betűszíne világos vagy sötét legyen.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Kérjük, válassza ki a gomb kívánt feliratát.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'A gomb előnézete',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Megjelenítés a termék részletes oldalán',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Kapcsolja be ezt a funkciót, hogy a Klarna Instant Shopping gomb megjelenjen az Ön webáruházának minden termékleírási oldalán.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Megjelenítés a kosár áttekintésén',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Kapcsolja be ezt a funkciót, hogy a Klarna Instant Shopping gomb megjelenjen az Ön webáruházának kosáráttekintő oldalán.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'További „Instant Shopping” beállítások',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'A szállítási cím eltérhet a számlázási címtől',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Ha a szállítást egy másik szállítási címre is lehetővé kívánja tenni, jelölje be ezt a jelölőnégyzetet.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'A születési dátum kötelező mező',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Ha feltétlenül megköveteli a születési dátum megadását, kapcsolja be ezt a kapcsolót. Általában a Klarna esetében a születési dátum nem kötelező mező. Ugyanakkor a megadás szükséges ahhoz, hogy számlás vásárlás vagy részletfizetés lehetséges legyen.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'A nemzeti azonosítószám kötelező mező',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Kérjük, válassza ki, hogy a nemzeti azonosítószám kötelező mező legyen-e.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Változat',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Szlogen',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Típus',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'A telefonszám kitöltése kötelező',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Kérjük, válassza ki, hogy a telefonszám kötelező mező legyen-e.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Kérjük, válassza ki a listából, hogy melyik ország legyen alapértelmezettként beállítva a Klarna Instant Shopping megnyitásakor, amíg az ügyfél még nem adta meg az országát.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Itt adja meg az Általános Szerződési Feltételeinek URL-címét. Ezekre a Klarna Instant Shopping felugró ablakban hivatkozás jelenik meg. Érvényes, https://-vel kezdődő URL-címet kell megadni.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Szállítási módok',
    'TCKLARNA_COMPLETE_REFUND'                          => 'A teljes megrendelés összegét jóváírni',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Nem találtunk aktív szállítási módokat',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Használt fizetési mód: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Hitelkártya',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'csoportos beszedés',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Azonnali átutalás',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 kamatmentes részlet',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finanszírozás',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B számla (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Számla',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Kártyás fizetés 30 napos fizetési határidővel',
];
