<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Português";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Início',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Geral',
    'TCKLARNA_CONFIGURATION'                            => 'Configuração',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configuração para pagamentos Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Definições de design',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Formas de pagamento externas',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Dados adicionais do revendedor',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Configurações básicas',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Desconto',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'Neste modo, não há configurações.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Todas as definições foram guardadas.',

    'TCKLARNA_EASY'                                     => 'É assim tão fácil ativar o Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefone',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Horário de funcionamento',
    'TCKLARNA_MONDAY'                                   => 'Segunda-feira',
    'TCKLARNA_TUESDAY'                                  => 'Terça-feira',
    'TCKLARNA_WEDNESDAY'                                => 'Quarta-feira',
    'TCKLARNA_THURSDAY'                                 => 'Quinta-feira',
    'TCKLARNA_FRIDAY'                                   => 'Sexta-feira',
    'TCKLARNA_SATURDAY'                                 => 'Sábado',
    'TCKLARNA_SUNDAY'                                   => 'Domingo',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Os seus dados de acesso específicos para cada país',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Adicionar dados de acesso específicos por país',
    'TCKLARNA_COUNTRY'                                  => 'País',
    'TCKLARNA_MERCHANT_ID'                              => 'Nome de utilizador da API',
    'TCKLARNA_PASSWORD'                                 => 'Palavra-passe da API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID do comerciante',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'País predefinido da loja',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Registo ativo',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Enviar dados adicionais do produto à Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URLs dos produtos',
    'TCKLARNA_IMAGE_URLS'                               => 'URLs das imagens',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimizar',
    'TCKLARNA_ADD'                                      => 'Adicionar',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Pagamentos Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Selecionar o modo do módulo Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Com a Klarna, os clientes finais podem efetuar o pagamento de três formas: transferência imediata, mais tarde ou a prestações. Isto permite aos clientes finais experimentar primeiro os produtos e pagar apenas o que pretendem ficar, financiar os produtos na loja ou pagar imediatamente. Pode ativar a fatura, a compra a prestações, a transferência bancária imediata ou o débito direto através de uma integração e, graças à solução iFrame da Klarna, estas opções estão sempre atualizadas, tanto do ponto de vista jurídico como em termos de conteúdo.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Os métodos de pagamento mais populares. Seguros e fáceis de integrar.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Seja muito bem-vindo às definições de configuração do Klarna Payments. Aqui encontrará tudo o que é necessário para a ativação. Selecione as subopções do Klarna na barra à esquerda para concluir a configuração do módulo.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Criar uma conta de cliente na OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Inscrição na newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Criar conta de cliente E subscrever a newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Não apresentar a caixa de seleção',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Mostrar na página inicial da loja?',
    'TCKLARNA_BANNER_SRC'                               => 'Fonte do banner da Klarna',
    'TCKLARNA_FOOTER'                                   => 'Rodapé',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'O que deve ser apresentado no rodapé?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Exibição das formas de pagamento',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logótipo da Klarna',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Versão longa:',
    'TCKLARNA_SHORT_VERSION'                            => 'Versão resumida:',
    'TCKLARNA_WHITE'                                    => 'Branco:',
    'TCKLARNA_BLACK'                                    => 'Preto:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Página de detalhes do artigo e cesto de compras',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Mostrar o widget do método de pagamento Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Na página de detalhes do artigo',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Na página do cesto de compras',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Mostrar o botão «Comprar agora»?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opções de design de pagamento da Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Definições de cor:',
    'TCKLARNA_BORDER'                                   => 'Borda:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Borda selecionada:',
    'TCKLARNA_BUTTON'                                   => 'Botão:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Texto do botão:',
    'TCKLARNA_CHECKBOX'                                 => 'Caixa de seleção:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Caixa de seleção marcada:',
    'TCKLARNA_DETAILS'                                  => 'Detalhes:',
    'TCKLARNA_HEADER'                                   => 'Título:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Texto:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Texto adicional:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Ajuste do raio:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Raio da borda:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'A morada de entrega pode ser diferente da morada de faturação',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'O número de telefone é um campo obrigatório',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'A data de nascimento é um campo obrigatório',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Ativar a entrega na DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Ativar o pré-preenchimento',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Ativar aviso de pré-preenchimento',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'O tratamento é um campo obrigatório',
    'TCKLARNA_SET_TAC_URI'                              => 'URL para os seus Termos e Condições Gerais',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL sobre o direito de rescisão',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Detalhes do envio',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Sem validação',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Realizar a validação, mas ignorar os tempos limite',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'É necessária uma validação bem-sucedida',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Validação da encomenda',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Por favor, selecione as opções de pagamento da Klarna que pretende disponibilizar aos seus clientes:',
    'TCKLARNA_PAY_LATER'                                => 'Fatura',
    'TCKLARNA_PAY_LATER.'                               => 'Fatura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Para os clientes que pretendem comprar agora e pagar mais tarde. De forma muito prática, em 14, 21 ou 28 dias, consoante o mercado.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'A opção «Fatura» torna o processo de pagamento simples e rápido para os clientes, sem que estes tenham de introduzir dados pessoais ou números complicados. O cliente pode escolher entre a fatura e o pagamento no mês X.',
    'TCKLARNA_SLICE_IT'                                 => 'Compra a prestações.',
    'TCKLARNA_SLICE_IT.'                                => 'Pagar em prestações.',
    'TCKLARNA_SLICE_IT_START'                           => 'Aumente o poder de compra dos seus clientes através do pagamento a prestações. Os clientes podem liquidar as suas compras em prestações mensais fixas, ao longo de um período de 6 a 36 meses.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Através do «pagamento a prestações», os clientes podem dividir o valor da compra em prestações, com juros baixos. Isto aumenta o limite de investimento e o poder de compra. O processo de aprovação de crédito exclusivo da Klarna demora apenas alguns instantes e requer a introdução de um mínimo de dados.',
    'TCKLARNA_PAY_NOW'                                  => 'Pagar agora',
    'TCKLARNA_PAY_NOW.'                                 => 'Pagar agora.',
    'TCKLARNA_PAY_NOW_START'                            => 'Pagamento direto, simples e rápido, com a opção «Pagar agora» da Klarna. Na Alemanha, o Sofortüberweisung, o cartão de crédito e o débito direto não podem faltar no portfólio.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Os clientes que pretendam pagar o montante total imediatamente ao concluir a encomenda podem utilizar a opção «Pagar agora». As formas de pagamento disponíveis são cartão de crédito, débito direto e transferência bancária instantânea.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Guia sobre como<br /> ativar o Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'No backend do OXID, clique na nova opção de menu «Klarna», na subcategoria «Geral» e, em seguida, selecione o produto Klarna pretendido.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Introduza os seus dados de acesso (nome de utilizador e palavra-passe) e, em «Definições da loja» &gt; «Formas de pagamento» e «Formas de envio», defina as atribuições típicas do OXID para as formas de pagamento.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Guarde as alterações.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Já está online e pode começar a vender com a Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Apoio aos comerciantes',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Aqui pode configurar se, caso seja necessário, devem ser transmitidos dados adicionais do comerciante à Klarna. 
Para uma descrição detalhada das várias definições, consulte as dicas de ajuda 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leia o <a class="cl-pink" href="%s" target="_blank">manual</a> 
ou contacte o Apoio à Integração da Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Aqui pode configurar as definições de design para utilização com o módulo Klarna para a OXID eShop. 
Para uma descrição detalhada das várias definições, consulte as dicas de ajuda em 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leia o <a class="cl-pink" href="%s" target="_blank">manual</a> em 
ou contacte o Apoio à Integração da Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Aqui pode definir as opções para os pagamentos Klarna e efetuar configurações gerais. 
Para uma descrição detalhada das várias configurações, consulte as dicas de ajuda em 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leia o <a class="cl-pink" href="%s" target="_blank">manual</a> em 
ou contacte o Apoio à Integração da Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Nesta página, pode selecionar quais as opções de pagamento da Klarna que pretende disponibilizar. 
Para uma descrição detalhada das várias configurações, consulte as dicas de ajuda 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, leia o <a class="cl-pink" href="%s" target="_blank">manual</a> 
ou contacte o Apoio à Integração da Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Forma de pagamento',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Forma de pagamento externa',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI da imagem para o método de pagamento externo',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Dimensões da imagem: 69x24 píxeis',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Dimensões da imagem: 276x48 píxeis',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Pode consultar aqui o manual do utilizador do módulo Klarna para a OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manual do utilizador',

    'TCKLARNA_CHOOSE'                                   => 'Votar',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informações sobre a conta do cliente',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Histórico completo de pagamentos',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Campo de repasse',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Atribuir o tipo de forma de pagamento:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Que encomendas devem ser incluídas no «Histórico de pagamentos completo»?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Considerar todas as encomendas como pagas, independentemente da data do Oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Enviar apenas as encomendas com data «oxpaid» definida; ignorar as encomendas não pagas',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorar todas as encomendas efetuadas com este método de pagamento',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Outra opção de pagamento',
    'TCKLARNA_DIRECT_BANKING'                           => 'Transferência imediata',
    'TCKLARNA_CARD'                                     => 'Mapa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Escolha entre «Playground» (modo de teste) e «Live» (modo de produção). Ative o modo de produção apenas após a realização bem-sucedida dos testes de integração e após consulta com o seu Gestor de Integração da Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Por favor, introduza aqui os seus dados de acesso à API da Klarna. Recebeu-os no e-mail de boas-vindas da Klarna. Este nome de utilizador e palavra-passe são válidos globalmente para todos os países. Apenas caso tenha recebido dados de acesso diferentes para países distintos, poderá adicioná-los mais abaixo.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Introduza aqui a sua palavra-passe correspondente ao nome de utilizador da API que está a utilizar. Recebeu esta palavra-passe no e-mail de boas-vindas da Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Por favor, introduza aqui o seu ID de comerciante da Klarna. Recebeu-o no e-mail de boas-vindas da Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Selecione, na lista à esquerda, o país para o qual recebeu os dados de acesso específicos da Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Por favor, introduza aqui o nome de utilizador correspondente a este país.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Por favor, introduza aqui a palavra-passe correspondente a este país.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Por favor, introduza aqui o Merchant ID correspondente a este país.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Ativa a função de registo para que toda a comunicação via API com a Klarna seja registada na tabela tcklarna_logs do MySQL. Isto pode ser útil na análise ou na resolução de problemas. Em ambiente de produção, esta função deve estar desativada, pois, caso contrário, poderão acumular-se grandes quantidades de registos e ser armazenados dados sensíveis.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Envie à Klarna os URLs das páginas de detalhes dos produtos que se encontram no carrinho de compras dos seus clientes, para que a Klarna possa, posteriormente, criar ligações para os seus artigos a partir do Portal da Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Envie à Klarna os URLs das imagens dos artigos que se encontram no cesto de compras dos seus clientes, para que a Klarna possa exibi-las no Portal da Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Ative a anonimização para ocultar da Klarna as designações dos artigos que se encontram no cesto de compras dos seus clientes. Esta medida é recomendada, por exemplo, para farmácias online, mas só deve ser implementada após consulta com o Gestor de Integração da Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Se pretender que a entrega seja efetuada numa morada de entrega diferente, ative este botão.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Caso pretenda tornar obrigatória a indicação de um número de telefone, ative este botão. Normalmente, para a Klarna, o número de telefone não é um campo obrigatório.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Se pretender tornar obrigatória a indicação da data de nascimento, ative este botão. Normalmente, para a Klarna, a data de nascimento não é um campo obrigatório. No entanto, essa informação é necessária para permitir a compra a crédito ou o pagamento em prestações.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'De momento, não está implementado',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Indique aqui o URL do seu site com a informação sobre o direito de rescisão. O URL deve começar por https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Estas informações sobre o envio são apresentadas ao cliente na página de agradecimento após a conclusão da encomenda.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Atribua este método de pagamento externo a um dos métodos de pagamento predefinidos',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Por favor, indique um URL para todas as línguas',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Indique, por favor, um URL válido que comece por https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Este botão ativa o envio de dados adicionais à Klarna; neste caso, as informações da conta do cliente, que incluem a data de registo da conta do cliente e a data da sua última alteração.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Este botão ativa a transmissão de dados adicionais à Klarna; neste caso, trata-se do «Payment History Full», que inclui as compras efetuadas até ao momento pelo cliente.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Por favor, indique a que tipo de forma de pagamento corresponde este método de pagamento.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Por favor, indique aqui se, e em caso afirmativo, quais as encomendas com este método de pagamento devem ser incluídas na transferência do histórico de encomendas do cliente. A dependência do campo OXORDER.OXPAID determina se devem ser consideradas apenas as encomendas pagas ou todas as encomendas.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'É possível enviar quaisquer outros dados à Klarna através de um campo «pass-through». Para utilizar esta função, terá de instalar um módulo adequado na OXID eShop, que insira os dados pretendidos no campo «pass-through». Encontrará as instruções correspondentes na documentação para programadores.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Com este botão, pode ativar um banner da Klarna na página inicial da sua loja, no tema padrão Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Aqui pode inserir a tag de script para a integração do banner. No portal de banners da Klarna, poderá encontrar, se for o caso, outros banners à sua escolha.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Com este botão, pode ativar a exibição do método de pagamento Klarna no rodapé da sua loja, no tema padrão Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Com este botão, pode inserir o logótipo da Klarna no rodapé da sua loja, no tema padrão Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Este botão insere um botão «Comprar agora» nas páginas de detalhes dos artigos da sua loja, no tema padrão Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Cor da moldura que aparece no front-end da loja após a seleção do método de pagamento Klarna, caso existam várias subopções disponíveis.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Cor da moldura que aparece no front-end da loja após a seleção do método de pagamento Klarna, caso existam várias subopções disponíveis. Este valor de cor é utilizado para destacar a subopção atualmente selecionada.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Esta configuração ainda não tem qualquer efeito à data de publicação deste módulo.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Esta configuração ainda não tem qualquer efeito à data de publicação deste módulo.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Cor de fundo dos botões de opção que aparecem no front-end da loja após a seleção do método de pagamento Klarna, caso existam várias subopções disponíveis',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Esta configuração ainda não tem qualquer efeito à data de publicação deste módulo.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Cor dos marcadores na apresentação dos detalhes de pagamento na página de seleção de formas de pagamento.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Esta configuração ainda não tem qualquer efeito à data de publicação deste módulo.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Cor dos links na descrição detalhada das formas de pagamento na página de seleção das formas de pagamento.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Cor do texto da descrição detalhada das formas de pagamento na página de seleção das formas de pagamento.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Cor alternativa do texto da descrição detalhada das formas de pagamento na página de seleção das formas de pagamento.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Com esta configuração, pode definir o grau de arredondamento da moldura que aparece no front-end da loja, consoante as diferentes subopções disponíveis, após a seleção do método de pagamento Klarna.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Este separador aplica-se apenas às encomendas da Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Registar a encomenda na íntegra',
    'KLARNA_CAPTURE_ID'                                 => 'ID da transação',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Referência Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Montante da débito',
    'KLARNA_CAPTURE_DATE'                               => 'Debitado em',
    'KLARNA_REFUND_AMOUNT'                              => 'Montante do reembolso',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Reembolso - Explicação',
    'KLARNA_REFUND_DATE'                                => 'Substituído em',
    'KLARNA_CAPTURES'                                   => 'Débitos',
    'KLARNA_REFUNDS'                                    => 'Reembolsos',
    'KLARNA_CANCEL_ORDER'                               => 'Cancelar encomenda',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'A encomenda foi cancelada. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Aceder a esta encomenda no portal da Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Atenção!</strong> Os dados desta encomenda diferem dos dados registados na Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Atenção! Devido ao estado atual da encomenda, esta alteração não pode ser enviada à Klarna. Se for necessário, efetue manualmente a alteração correspondente diretamente no Portal do Comerciante da Klarna.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Atenção! A Klarna não conseguiu processar as suas últimas alterações a esta encomenda (motivo: %s). Por favor, anule as alterações recentes na OXID eShop ou, se necessário, efetue manualmente a correção correspondente no Portal do Comerciante da Klarna.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Pedido não autorizado. Verifique as definições do módulo Klarna, bem como o Merchant ID e a palavra-passe correspondente',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Esta encomenda não foi encontrada no sistema da Klarna. Por conseguinte, as alterações aos dados da encomenda não serão transmitidas à Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Dados de acesso incorretos!</strong> Esta encomenda foi efetuada utilizando o ID de comerciante <strong>%s</strong>. O ID de comerciante atualmente configurado para <strong>%s</strong> é <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nome do produto',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Título do produto anonimizado:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'O pagamento é processado pelo nosso parceiro Klarna. Por favor, tenha em atenção as informações de pagamento enviadas pela Klarna. Pode gerir todas as suas compras através do site Klarna.com ou da aplicação da Klarna e até pagar com apenas um clique.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Cupão de desconto',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Embalagem de presente',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Cartão de felicitações',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Erro grave: É obrigatório indicar um $this-&gt;sSSLShopURL válido e protegido por SSL (https) no ficheiro config.inc.php da sua loja, caso pretenda ativar o %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Dados de acesso incorretos!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'O montante foi debitado com sucesso.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Não foi possível debitar o valor da encomenda, uma vez que esta já tinha sido cancelada.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Introduza aqui a sequência de caracteres que deve ser enviada à Klarna em vez do título real do produto.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'As alterações que efetuar a esta encomenda não serão transmitidas à Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manual do utilizador',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registar-se',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Saiba mais',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tipos de clientes suportados',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Aqui pode definir se a loja deve aceitar exclusivamente transações B2C (configuração padrão), apenas transações B2B ou tanto transações B2C como B2B.<br />  Nota: Após alterar os tipos de cliente, é necessário limpar a cache de sessão do navegador para que o pagamento possa ser testado.',
    'TCKLARNA_B2C'                                      => 'Apenas clientes B2C',
    'TCKLARNA_B2B'                                      => 'Apenas clientes B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Principalmente clientes B2B, mas também clientes B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Principalmente clientes B2C, mas também clientes B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Precisa de ajuda com a integração?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contacte o Apoio ao Comerciante da Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Mensagens no local',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Aqui pode configurar o sistema de mensagens no site para utilização com o módulo Klarna para a OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Guião',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Página de detalhes do artigo «Credit Promotion»',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Cesto de compras da Credit Promotion',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promoção na faixa superior',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promoção no rodapé',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promoção com banners',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Por favor, insira aqui o fragmento de código da biblioteca JavaScript necessário para o sistema de mensagens no site, que pode obter no Portal do Comerciante da Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Por favor, insira aqui a etiqueta de colocação para promover o financiamento e a compra a prestações através da Credit Promotions na página de detalhes do artigo',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Por favor, insira aqui a etiqueta de colocação para promover o financiamento e a compra a prestações através da Credit Promotions na página de resumo do carrinho de compras',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Por favor, insira aqui a etiqueta de colocação para promover informações genéricas e específicas sobre os métodos de pagamento na página inicial da loja',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Por favor, insira aqui a etiqueta de colocação para apresentar as formas de pagamento Klarna disponíveis no rodapé da loja',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Por favor, insira aqui a etiqueta de colocação para inserir um banner na página inicial da sua loja',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'O que é a «On-Site Messaging»?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Os clientes nem sempre têm conhecimento das diversas opções de crédito e financiamento à sua disposição antes de chegarem à caixa. As opções de financiamento disponibilizadas atempadamente influenciam a decisão de compra. 

O On-Site Messaging é fácil e simples de integrar e oferece informações personalizadas, que vão desde banners gerais sobre a promoção da sua parceria com a Klarna e a disponibilidade de pagamento a prestações até a promoções de crédito personalizadas nas páginas de produtos ou do carrinho de compras.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Encontre aqui</a> mais informações <br /><br />sobre os primeiros passos<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">:</a> 
Inicie sessão no <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">portal do comerciante</a> para gerar o seu código JavaScript e o seu código de colocação pessoais. A funcionalidade «On-Site-Messaging» será ativada na sua loja assim que o código JavaScript for guardado e tiver sido introduzido, pelo menos, um código de colocação.<br /> 
Pode desativá-la a qualquer momento, removendo os códigos.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portal do revendedor',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Ativar o Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Ativo',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Substituir a tecla do botão',
    'TCKLARNA_IS_REPLACE'                               => 'Criar um novo botão «Key»',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Pode atualizar a «Button Key» caso seja necessário alterar os dados de configuração ou de identificação por parte da Klarna. Normalmente, pode utilizar uma «Button Key» gerada uma vez durante o tempo que desejar.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Ative aqui o Klarna Instant Shopping. Isto irá gerar automaticamente um botão para utilização no front-end da loja.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Definições de estilo dos botões',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Por favor, escolha entre um botão com a imagem de marca completa da Klarna e uma versão «Light» mais neutra.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Por favor, escolha se a cor da letra do slogan abaixo do botão deve ser clara ou escura.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Por favor, selecione o texto que pretende para o botão.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Pré-visualização do botão',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Mostrar na página de detalhes do artigo',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Ative esta função para que o botão «Klarna Instant Shopping» seja exibido em todas as páginas de detalhes dos artigos na sua loja.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Mostrar na página de resumo do cesto de compras',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Ative esta função para que o botão «Klarna Instant Shopping» seja exibido na página de resumo do carrinho de compras da sua loja.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Outras definições do Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'A morada de entrega pode ser diferente da morada de faturação',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Se pretender que a entrega seja efetuada numa morada diferente, ative este botão.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Data de nascimento como campo obrigatório',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Se pretender tornar obrigatória a indicação da data de nascimento, ative este botão. Normalmente, para a Klarna, a data de nascimento não é um campo obrigatório. No entanto, essa informação é necessária para permitir a compra a conta ou o pagamento a prestações.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Número de identificação nacional como campo obrigatório',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Por favor, indique se o número de identificação nacional deve ser um campo obrigatório.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variação',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tipo',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'O número de telefone é um campo obrigatório',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Por favor, indique se o número de telefone deve ser um campo obrigatório.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Por favor, selecione na lista o país que deve ser predefinido por predefinição ao aceder ao Klarna Instant Shopping, enquanto o cliente ainda não tiver indicado o seu país.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Indique aqui o URL dos seus Termos e Condições Gerais. Estes serão apresentados com um link na janela pop-up do Klarna Instant Shopping. É necessário indicar um URL válido que comece por https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Modos de envio',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Creditar a encomenda na totalidade',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Não foram encontradas formas de envio ativas',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Forma de pagamento utilizada: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Cartão de crédito',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Débito direto',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Transferência imediata',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 prestações sem juros',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financiamento',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Fatura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Fatura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Pagamento com cartão em 30 dias',
];
