<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Čeština";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Začátek',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Obecně',
    'TCKLARNA_CONFIGURATION'                            => 'Konfigurace',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfigurace pro platby přes Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Nastavení vzhledu',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Externí způsoby platby',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Další údaje o prodejci',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Základní nastavení',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Sleva',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'V tomto režimu nejsou k dispozici žádná nastavení.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Všechna nastavení byla uložena.',

    'TCKLARNA_EASY'                                     => 'Aktivace služby Klarna je tak jednoduchá',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Otevírací doba',
    'TCKLARNA_MONDAY'                                   => 'pondělí',
    'TCKLARNA_TUESDAY'                                  => 'úterý',
    'TCKLARNA_WEDNESDAY'                                => 'středa',
    'TCKLARNA_THURSDAY'                                 => 'čtvrtek',
    'TCKLARNA_FRIDAY'                                   => 'pátek',
    'TCKLARNA_SATURDAY'                                 => 'sobota',
    'TCKLARNA_SUNDAY'                                   => 'neděle',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Vaše přihlašovací údaje pro jednotlivé země',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Přidat přístupové údaje pro jednotlivé země',
    'TCKLARNA_COUNTRY'                                  => 'Země',
    'TCKLARNA_MERCHANT_ID'                              => 'Uživatelské jméno API',
    'TCKLARNA_PASSWORD'                                 => 'Heslo k API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID obchodníka',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Výchozí země obchodu',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Záznam je aktivní',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Odeslat rozšířené údaje o produktu společnosti Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL adresy produktů',
    'TCKLARNA_IMAGE_URLS'                               => 'URL obrázků',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymizovat',
    'TCKLARNA_ADD'                                      => 'Přidat',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Platby přes Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Výběr režimu modulu Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'S Klarnou mohou koncoví zákazníci platit třemi způsoby: okamžitým převodem, později nebo na splátky. To koncovým zákazníkům umožňuje nejprve si zboží vyzkoušet a zaplatit pouze to, co si chtějí nechat, financovat produkty v obchodě nebo zaplatit okamžitě. Fakturu, nákup na splátky, okamžitý převod nebo inkasní příkaz můžete aktivovat pomocí integrace a díky řešení iFrame od společnosti Klarna jsou tyto možnosti z právního i obsahového hlediska vždy aktuální.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Nejoblíbenější způsoby platby. Bezpečné a snadno integrovatelné.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Srdečně vás vítáme v konfiguračních nastaveních služby Klarna Payments. Zde najdete vše, co je k aktivaci potřeba. Vyberte v levém panelu podnabídky služby Klarna, abyste dokončili nastavení modulu.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Vytvoření zákaznického účtu v e-shopu OXID',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Přihlášení k odběru zpravodaje',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Vytvoření zákaznického účtu A přihlášení k odběru newsletteru',
    'TCKLARNA_NO_CHECKBOX'                              => 'Nezobrazovat zaškrtávací políčko',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Zobrazit na úvodní stránce obchodu?',
    'TCKLARNA_BANNER_SRC'                               => 'Zdroj banneru Klarna',
    'TCKLARNA_FOOTER'                                   => 'Zápatí',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Co se má zobrazit v zápatí?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Zobrazení způsobů platby',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo společnosti Klarna',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Dlouhá verze:',
    'TCKLARNA_SHORT_VERSION'                            => 'Krátká verze:',
    'TCKLARNA_WHITE'                                    => 'Bílá:',
    'TCKLARNA_BLACK'                                    => 'Černá:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Stránka s podrobnostmi o produktu a nákupní košík',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Zobrazit widget platební metody Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Na stránce s podrobnostmi o produktu',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Na stránce s nákupním košíkem',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Zobrazit tlačítko „Koupit nyní“?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Možnosti designu platebního systému Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Nastavení barev:',
    'TCKLARNA_BORDER'                                   => 'Hranice:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Vybraná hranice:',
    'TCKLARNA_BUTTON'                                   => 'Tlačítko:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Text tlačítka:',
    'TCKLARNA_CHECKBOX'                                 => 'Zaškrtávací políčko:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Zaškrtávací políčko:',
    'TCKLARNA_DETAILS'                                  => 'Podrobnosti:',
    'TCKLARNA_HEADER'                                   => 'Záhlaví:',
    'TCKLARNA_LINK'                                     => 'Odkaz:',
    'TCKLARNA_TEXT'                                     => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Další text:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Nastavení poloměru:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Zaoblení hran:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Dodací adresa se může lišit od fakturační adresy',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefonní číslo je povinné pole',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Datum narození je povinné pole',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktivovat doručení do balíkové schránky DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktivovat předvyplnění',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktivovat upozornění na předplnění',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Oslovení je povinné pole',
    'TCKLARNA_SET_TAC_URI'                              => 'URL vašich obchodních podmínek',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL týkající se práva na odstoupení od smlouvy',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Podrobnosti o doručení',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Žádná validace',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Provést validaci, ale ignorovat časové limity',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Je nutná úspěšná validace',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Ověření objednávky',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vyberte prosím platební možnosti Klarna, které chcete svým zákazníkům nabídnout:',
    'TCKLARNA_PAY_LATER'                                => 'Faktura',
    'TCKLARNA_PAY_LATER.'                               => 'Faktura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Pro zákazníky, kteří chtějí nakoupit hned a zaplatit později. Velmi pohodlně za 14, 21 nebo 28 dní, v závislosti na trhu.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Díky možnosti „Faktura“ mohou zákazníci provést platbu snadno a rychle, aniž by museli zadávat osobní údaje nebo složité kódy. Zákazník si může vybrat mezi fakturou a platbou v měsíci X.',
    'TCKLARNA_SLICE_IT'                                 => 'Nákup na splátky.',
    'TCKLARNA_SLICE_IT.'                                => 'Platit na splátky.',
    'TCKLARNA_SLICE_IT_START'                           => 'Zvyšte kupní sílu svých zákazníků díky možnosti splátek. Zákazníci mohou své nákupy splácet v pevných měsíčních splátkách po dobu 6 až 36 měsíců.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Díky „splátkovému nákupu“ mohou zákazníci rozdělit částku za nákup na menší splátky s nízkým úrokem. To zvyšuje investiční rámec a kupní sílu. Jedinečný proces vyřizování úvěru společnosti Klarna trvá jen několik okamžiků a vyžaduje zadání minimálního množství údajů.',
    'TCKLARNA_PAY_NOW'                                  => 'Zaplatit ihned',
    'TCKLARNA_PAY_NOW.'                                 => 'Zaplatit ihned.',
    'TCKLARNA_PAY_NOW_START'                            => 'Jednoduchá a rychlá přímá platba pomocí služby „Sofort bezahlen“ od společnosti Klarna. V Německu by v nabídce neměly chybět služby Sofortüberweisung, platba kreditní kartou a inkaso.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Zákazníci, kteří chtějí uhradit celou částku ihned při dokončení objednávky, mohou využít možnost „Zaplatit ihned“. Na výběr mají kreditní kartu, inkasní příkaz a okamžitý bankovní převod.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Návod k <br />aktivaci služby Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'V administraci OXID klikněte na novou položku menu „Klarna“, podkategorii „Obecné“ a poté vyberte požadovaný produkt Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Zadejte své přihlašovací údaje (uživatelské jméno a heslo) a v části Nastavení obchodu &gt; Způsoby platby a &gt; Způsoby dopravy proveďte typické přiřazení způsobů platby v systému OXID.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Uložte změny.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Nyní jste online a můžete začít prodávat přes Klarnu.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Podpora pro obchodníky',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Zde můžete nastavit, zda mají být případně předána společnost Klarna dodatečná data obchodníka. 
Podrobný popis jednotlivých nastavení najdete v popiscích nástrojů 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">příručce</a> 
nebo se obraťte na podporu integrace Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Zde můžete nakonfigurovat nastavení vzhledu pro použití s modulem Klarna pro OXID eShop. 
Podrobný popis jednotlivých nastavení najdete v popiscích 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">příručce</a> 
nebo se obraťte na podporu integrace Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Zde proveďte výběr pro platby Klarna a nastavte obecné parametry. 
Podrobný popis jednotlivých nastavení najdete v popiscích 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">příručce</a> 
nebo se obraťte na podporu pro integraci Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Na této stránce si vyberete, které platební služby Klarna chcete nabízet. 
Podrobný popis jednotlivých nastavení najdete v popiscích 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">příručce</a> 
nebo se obraťte na podporu pro integraci Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Způsob platby',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Externí způsob platby',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI obrázku pro externí platební metodu',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Velikost obrázku: 69 × 24 pixelů',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Velikost obrázku: 276 × 48 pixelů',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Uživatelskou příručku k modulu Klarna pro OXID eShop si můžete prohlédnout zde.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Uživatelská příručka',

    'TCKLARNA_CHOOSE'                                   => 'Vybrat',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informace o zákaznickém účtu',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Kompletní přehled plateb',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Přenosové pole',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Přiřadit typ platební metody:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Které objednávky mají být zahrnuty do úplné historie plateb?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Všechny objednávky se považují za zaplacené bez ohledu na datum oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Odesílat pouze objednávky s nastaveným datem oxpaid; neuhrazené objednávky ignorovat',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Všechny objednávky provedené tímto způsobem platby ignorovat',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Jiná možnost platby',
    'TCKLARNA_DIRECT_BANKING'                           => 'Okamžitý převod',
    'TCKLARNA_CARD'                                     => 'Mapa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Vyberte si mezi režimem „Playground“ (testovací provoz) a „Live“ (produkční provoz). Produkční provoz aktivujte až po úspěšném provedení integračních testů a po konzultaci s vaším integračním manažerem společnosti Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Zadejte sem prosím své přihlašovací údaje k API služby Klarna. Tyto údaje jste obdrželi v uvítacím e-mailu od společnosti Klarna. Toto uživatelské jméno a heslo platí globálně pro všechny země. Pouze v případě, že jste obdrželi odlišné přihlašovací údaje pro různé země, můžete je přidat níže.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Zadejte zde heslo odpovídající použitému uživatelskému jménu pro API. Toto heslo jste obdrželi v uvítacím e-mailu od společnosti Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Zadejte sem prosím své identifikační číslo obchodníka Klarna. To jste obdrželi v uvítacím e-mailu od společnosti Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Z nabídky vlevo vyberte zemi, pro kterou jste od společnosti Klarna obdrželi přístupové údaje specifické pro danou zemi.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Zadejte prosím zde příslušné uživatelské jméno pro tuto zemi.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Zadejte prosím zde příslušné heslo pro tuto zemi.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Zde prosím zadejte příslušné ID obchodníka pro tuto zemi.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktivuje funkci protokolování, aby byla veškerá komunikace přes API se společností Klarna zaznamenána do tabulky tcklarna_logs v databázi MySQL. To může být užitečné při analýze nebo při hledání chyb. V produkčním prostředí by měla být tato funkce vypnutá, protože jinak by se mohly hromadit velké objemy protokolů a ukládat citlivé údaje.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Zašlete společnosti Klarna adresy URL stránek s podrobnostmi o produktech, které se nacházejí v nákupním košíku vašich zákazníků, aby mohla společnost Klarna později z portálu Klarna odkazovat na vaše produkty.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Zašlete společnosti Klarna adresy URL obrázků produktů, které se nacházejí v nákupním košíku vašich zákazníků, aby je mohla společnost Klarna zobrazit na portálu Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktivujte anonymizaci, abyste před společností Klarna skryli názvy produktů, které se nacházejí v nákupním košíku vašich zákazníků. Toto opatření se doporučuje například pro internetové lékárny, mělo by se však provést pouze po konzultaci s manažerem integrace společnosti Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Pokud má být umožněna dodávka na jinou dodací adresu, zaškrtněte toto políčko.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Pokud chcete, aby bylo zadání telefonního čísla povinné, zapněte tento přepínač. Obvykle není telefonní číslo u služby Klarna povinným polem.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Pokud chcete, aby bylo zadání data narození povinné, zaškrtněte toto políčko. Obvykle není datum narození pro Klarnu povinným polem. Jeho zadání je však nezbytné k tomu, aby bylo možné provést nákup na fakturu nebo splátkový prodej.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'V současné době není implementováno',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Zde uveďte adresu URL své webové stránky s informacemi o právu na odstoupení od smlouvy. Adresa URL musí začínat https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Tyto informace o dopravě se zákazníkovi zobrazí na stránce s poděkováním po dokončení objednávky.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Přiřaďte tento externí způsob platby k jednomu z předdefinovaných způsobů platby',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Uveďte prosím URL pro všechny jazyky',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Zadejte prosím platnou adresu URL, která začíná https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Tento přepínač aktivuje přenos dalších údajů do systému Klarna, v tomto případě informací o zákaznickém účtu, které obsahují datum registrace zákaznického účtu a datum jeho poslední změny.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Tento přepínač aktivuje přenos dalších údajů do systému Klarna, v tomto případě „Payment History Full“, který obsahuje dosavadní nákupy zákazníka.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Prosím, určete, o jaký způsob platby se v tomto případě jedná.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Zde prosím určete, zda a případně které objednávky s tímto způsobem platby mají být zahrnuty při přenosu historie objednávek zákazníka. Závislost pole OXORDER.OXPAID určuje, zda mají být zohledněny pouze zaplacené objednávky, nebo všechny objednávky.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Pomocí pole „Pass-through“ je možné předat společnosti Klarna další libovolné údaje. Chcete-li tuto funkci využít, musíte do e-shopu OXID nainstalovat příslušný modul, který požadované údaje zapíše do pole „Pass-through“. Příslušný návod najdete v dokumentaci pro vývojáře.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Pomocí tohoto přepínače aktivujete banner Klarna na úvodní stránce vašeho obchodu ve standardním šabloně Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Zde můžete zadat skriptový tag pro vložení banneru. V portálu bannerů společnosti Klarna případně najdete další bannery, ze kterých si můžete vybrat.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Pomocí tohoto přepínače aktivujete zobrazení platební metody Klarna v zápatí vašeho obchodu ve výchozím šabloně Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Pomocí tohoto přepínače vložíte logo Klarna do zápatí vašeho obchodu ve výchozím šabloně Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Tento přepínač vloží tlačítko „Koupit nyní“ na stránky s podrobnostmi o produktech ve vašem obchodě ve výchozím šabloně Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Barva rámečku, který se v případě různých dostupných podmožností zobrazí v uživatelském rozhraní obchodu po výběru platební metody Klarna.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Barva rámečku, který se v případě různých dostupných podmožností zobrazí v uživatelském rozhraní obchodu po výběru platební metody Klarna. Tato barva slouží k zvýraznění aktuálně vybrané podmožnosti.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Toto nastavení nemá v době zveřejnění tohoto modulu zatím žádný vliv.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Toto nastavení nemá v době zveřejnění tohoto modulu zatím žádný vliv.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Barva pozadí přepínačů, které se v případě různých dostupných podmožností zobrazí v uživatelském rozhraní obchodu po výběru platební metody Klarna',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Toto nastavení nemá v době zveřejnění tohoto modulu zatím žádný vliv.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Barva odrážek při zobrazení podrobností o platbě na stránce pro výběr způsobu platby.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Toto nastavení nemá v době zveřejnění tohoto modulu zatím žádný vliv.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Barva odkazů v podrobném popisu způsobů platby na stránce pro výběr způsobu platby.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Barva textu podrobného popisu způsobů platby na stránce pro výběr způsobu platby.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternativní barva textu v podrobném popisu platebních metod na stránce pro výběr platebních metod.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Pomocí tohoto nastavení můžete určit míru zaoblení rámečku, který se v případě různých dostupných podmožností zobrazí v uživatelském rozhraní obchodu po výběru platební metody Klarna.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Tato záložka se týká pouze objednávek přes Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Zachytit celou objednávku',
    'KLARNA_CAPTURE_ID'                                 => 'ID transakce',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Referenční číslo Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Částka odečtu',
    'KLARNA_CAPTURE_DATE'                               => 'Odečteno dne',
    'KLARNA_REFUND_AMOUNT'                              => 'Částka k vrácení',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Vrácení peněz – vysvětlení',
    'KLARNA_REFUND_DATE'                                => 'Nahrazeno dne',
    'KLARNA_CAPTURES'                                   => 'Odpisy',
    'KLARNA_REFUNDS'                                    => 'Vrácení peněz',
    'KLARNA_CANCEL_ORDER'                               => 'Zrušit objednávku',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Objednávka byla zrušena. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Zobrazit tuto objednávku na portálu Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Pozor!</strong> Údaje v této objednávce se liší od údajů uložených u společnosti Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Pozor! Vzhledem k aktuálnímu stavu objednávky nelze tuto úpravu předat společnosti Klarna. V případě potřeby proveďte příslušnou úpravu ručně přímo v portálu Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Pozor! Společnost Klarna nemohla zpracovat vaše poslední změny v této objednávce (důvod: %s). Zrušte prosím své nedávné změny v e-shopu OXID nebo v případě potřeby proveďte příslušnou úpravu ručně v portálu Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Nepovolený dotaz. Zkontrolujte nastavení modulu Klarna, ID obchodníka a příslušné heslo.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Tuto objednávku se v systému společnosti Klarna nepodařilo najít. Změny v údajích o objednávce proto nebudou společnosti Klarna předány.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Nesprávné přihlašovací údaje!</strong> Tato objednávka byla zadána s použitím ID prodejce <strong>%s</strong>. ID prodejce aktuálně nakonfigurované pro <strong>%s</strong> je <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Název produktu',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymizovaný název produktu:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Platbu zpracovává náš partner, společnost Klarna. Vezměte prosím na vědomí platební údaje zaslané společností Klarna. Všechny své nákupy můžete spravovat na webu Klarna.com nebo v aplikaci Klarna a dokonce je zaplatit jediným kliknutím.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Slevový kupón',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Dárkové balení',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Přání',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Závažná chyba: Pokud chcete aktivovat funkci „%s“, je nutné v souboru config.inc.php vašeho obchodu zadat platnou adresu $this-&gt;sSSLShopURL chráněnou protokolem SSL (https)!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Nesprávné přihlašovací údaje!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Částka byla úspěšně stržena.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Částku za objednávku nebylo možné strhnout, protože byla již zrušena.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Zde zadejte řetězec, který má být odeslán společnosti Klarna namísto skutečného názvu produktu.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Vaše změny v této objednávce nebudou předány společnosti Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Uživatelská příručka',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Zaregistrovat se',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Zjistit více',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Podporované typy zákazníků',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Zde můžete nastavit, zda má obchod přijímat výhradně transakce B2C (výchozí nastavení), pouze transakce B2B, nebo jak transakce B2C, tak i B2B.<br />  Poznámka: Po změně typů zákazníků je nutné vymazat mezipaměť relace v prohlížeči, aby bylo možné otestovat platbu.',
    'TCKLARNA_B2C'                                      => 'Pouze zákazníci z segmentu B2C',
    'TCKLARNA_B2B'                                      => 'Pouze zákazníci z oblasti B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Převážně zákazníci z oblasti B2B, ale také zákazníci z oblasti B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Převážně zákazníci z oblasti B2C, ale také zákazníci z oblasti B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Potřebujete pomoc s integrací?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Obraťte se na zákaznickou podporu společnosti Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Zprávy přímo na webu',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Zde můžete nakonfigurovat funkci „On-Site Messaging“ pro použití s modulem Klarna pro e-shop OXID.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Skript',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Stránka s podrobnostmi o produktu v rámci propagace úvěrů',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Úvěrová akce – Nákupní košík',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Propagace horního pruhu',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Propagace v zápatí',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Propagační banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Zde prosím vložte úryvek kódu knihovny JavaScript potřebný pro funkci On-Site Messaging, který získáte v portálu Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Zde prosím vložte umístěcí tag, abyste na stránce s podrobnostmi o produktu propagovali financování a splátkový prodej prostřednictvím Credit Promotions',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Zde prosím vložte umístěcí tag, abyste na stránce s přehledem košíku propagovali financování a splátkový prodej prostřednictvím Credit Promotions',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Zde prosím vložte umístěcí značku, abyste na úvodní stránce obchodu mohli propagovat obecné informace a informace týkající se konkrétních platebních metod',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Zde prosím vložte umístěcí tag, aby se v zápatí obchodu zobrazily dostupné způsoby platby Klarna',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Zde prosím vložte kód pro umístění, abyste mohli na úvodní stránku svého obchodu vložit banner',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Co je to On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Zákazníci si ne vždy uvědomují různé možnosti úvěrů a financování, které mají k dispozici, než se dostanou k pokladně. Včasné informace o možnostech financování ovlivňují rozhodnutí o nákupu. 

Funkce On-Site Messaging se snadno a bezproblémově integruje a nabízí informace šité na míru, od obecných bannerů přes propagaci vašeho partnerství se společností Klarna a dostupnost splátek až po personalizované úvěrové akce na stránkách produktů nebo v košíku.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Další informace o prvních krocích <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">najdete zde:</a><br /><br /> 
Přihlaste se do <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">portálu</a> <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">pro obchodníky</a> a vygenerujte si svůj osobní kód JavaScriptu a kód umístění. Funkce On-Site-Messaging se ve vašem obchodě aktivuje, jakmile uložíte kód JavaScriptu a zadáte alespoň jeden kód umístění.<br /> 
Funkci můžete kdykoli deaktivovat odstraněním těchto kódů.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portál pro prodejce',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktivovat službu Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktivní',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Vyměnit tlačítko Key',
    'TCKLARNA_IS_REPLACE'                               => 'Vytvořit nové tlačítko Key',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Tlačítkový klíč můžete aktualizovat, pokud je to nutné z důvodu změny konfiguračních nebo identifikačních údajů ze strany společnosti Klarna. Obvykle můžete jednou vygenerovaný tlačítkový klíč používat tak dlouho, jak budete chtít.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Zde zapněte funkci Klarna Instant Shopping. Tím se automaticky vygeneruje tlačítko pro použití v uživatelském rozhraní obchodu.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Nastavení vzhledu tlačítek',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vyberte si prosím mezi tlačítkem s kompletním brandingem ve stylu Klarna a neutrálnější variantou „Light“.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Vyberte prosím, zda má být barva písma sloganu pod tlačítkem světlá nebo tmavá.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vyberte prosím požadovaný text pro tlačítko.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Náhled tlačítka',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Zobrazit na stránce s podrobnostmi o produktu',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Tuto funkci aktivujte, aby se tlačítko Klarna Instant Shopping zobrazovalo na všech stránkách s podrobnostmi o produktech ve vašem obchodě.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Zobrazit v přehledu nákupního košíku',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Tuto funkci aktivujte, aby se tlačítko Klarna Instant Shopping zobrazovalo v přehledu nákupního košíku ve vašem obchodě.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Další nastavení funkce Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Dodací adresa se může lišit od fakturační adresy',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Pokud má být umožněna dodávka na jinou dodací adresu, zaškrtněte toto políčko.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Datum narození jako povinné pole',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Pokud chcete, aby bylo zadání data narození povinné, zaškrtněte toto políčko. Obvykle není datum narození pro Klarnu povinným polem. Jeho zadání je však nezbytné pro umožnění nákupu na fakturu nebo splátek.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Národní identifikační číslo jako povinné pole',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Zvolte prosím, zda má být národní identifikační číslo povinným polem.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variace',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Typ',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefonní číslo je povinné pole',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Zvolte prosím, zda má být telefonní číslo povinným polem.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Z seznamu prosím vyberte, která země se má při spuštění služby Klarna Instant Shopping automaticky nastavit jako výchozí, dokud zákazník nezadá svou zemi.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Zde zadejte adresu URL svých všeobecných obchodních podmínek. Ty budou propojeny v okně Klarna Instant Shopping. Je nutné zadat platnou adresu URL, která začíná https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Způsoby doručení',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Připsat celou objednávku na účet',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Nebyly nalezeny žádné aktivní způsoby dopravy',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Zvolený způsob platby: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kreditní karta',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Inkaso',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Okamžitý převod',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 splátky bez úroků',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financování',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Platba kartou s 30denní splatností',
];
