<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Nederlands";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Algemeen',
    'TCKLARNA_CONFIGURATION'                            => 'Configuratie',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configuratie voor Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Ontwerpinstellingen',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Externe betaalmethoden',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Aanvullende gegevens over de dealer',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Standaardinstellingen',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Korting',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'In deze modus zijn er geen instellingen.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Alle instellingen zijn opgeslagen.',

    'TCKLARNA_EASY'                                     => 'Zo eenvoudig is het om Klarna te activeren',
    'TCKLARNA_PHONE'                                    => 'Telefoon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Openingstijden',
    'TCKLARNA_MONDAY'                                   => 'Maandag',
    'TCKLARNA_TUESDAY'                                  => 'dinsdag',
    'TCKLARNA_WEDNESDAY'                                => 'woensdag',
    'TCKLARNA_THURSDAY'                                 => 'donderdag',
    'TCKLARNA_FRIDAY'                                   => 'vrijdag',
    'TCKLARNA_SATURDAY'                                 => 'zaterdag',
    'TCKLARNA_SUNDAY'                                   => 'zondag',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Uw landspecifieke inloggegevens',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Landspecifieke inloggegevens toevoegen',
    'TCKLARNA_COUNTRY'                                  => 'Land',
    'TCKLARNA_MERCHANT_ID'                              => 'API-gebruikersnaam',
    'TCKLARNA_PASSWORD'                                 => 'API-wachtwoord',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Handelaars-ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Standaardland van de winkel',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Logging actief',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Uitgebreide productgegevens naar Klarna verzenden?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Product-URL\'s',
    'TCKLARNA_IMAGE_URLS'                               => 'Afbeeldings-URL\'s',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimiseren',
    'TCKLARNA_ADD'                                      => 'Toevoegen',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-betalingen',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Klarna-module: modus selecteren',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Met Klarna kunnen eindklanten op drie manieren betalen: directe overschrijving, later of in termijnen. Hierdoor kunnen eindklanten producten eerst uitproberen en alleen betalen voor wat ze willen houden, producten in de winkel financieren of direct betalen. Factuur, aankoop op afbetaling, directe overschrijving of automatische incasso kunt u met één integratie activeren en zijn dankzij de iFrame-oplossing van Klarna zowel juridisch als inhoudelijk altijd up-to-date.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'De populairste betaalmethoden. Veilig en eenvoudig te integreren.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Van harte welkom bij de configuratie-instellingen van Klarna Payments. Hier vindt u alles wat u nodig hebt om de module te activeren. Selecteer de submenu-items van Klarna in de balk aan de linkerkant om de installatie van de module te voltooien.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Een klantenaccount aanmaken in de OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Aanmelden voor de nieuwsbrief',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Een klantaccount aanmaken EN je aanmelden voor de nieuwsbrief',
    'TCKLARNA_NO_CHECKBOX'                              => 'Geen selectievakje weergeven',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Op de startpagina van de webshop weergeven?',
    'TCKLARNA_BANNER_SRC'                               => 'Bron van de Klarna-banner',
    'TCKLARNA_FOOTER'                                   => 'Voettekst',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Wat moet er in de voettekst worden weergegeven?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Weergave van de betaalmethoden',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna-logo',
    'TCKLARNA_DESIGN'                                   => 'Ontwerp',
    'TCKLARNA_LONG_VERSION'                             => 'Lange versie:',
    'TCKLARNA_SHORT_VERSION'                            => 'Korte versie:',
    'TCKLARNA_WHITE'                                    => 'Wit:',
    'TCKLARNA_BLACK'                                    => 'Zwart:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Pagina met artikelgegevens en winkelmandje',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'De Klarna-betaalmethode-widget weergeven?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Op de detailpagina van het artikel',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Op de pagina met het winkelmandje',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'De knop \'Nu kopen\' weergeven?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Ontwerpopties voor Klarna-betalingen',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Kleurinstellingen:',
    'TCKLARNA_BORDER'                                   => 'Rand:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Geselecteerde rand:',
    'TCKLARNA_BUTTON'                                   => 'Knop:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Tekst op de knop:',
    'TCKLARNA_CHECKBOX'                                 => 'Selectievakje:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Vinkje bij het selectievakje:',
    'TCKLARNA_DETAILS'                                  => 'Details:',
    'TCKLARNA_HEADER'                                   => 'Koptekst:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Tekst:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Vervolgtekst:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Instelling van de straal:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Randradius:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Het afleveradres mag afwijken van het factuuradres',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Het telefoonnummer is een verplicht veld',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Geboortedatum is een verplicht veld',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Levering naar DHL Packstation inschakelen',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Voorvullen inschakelen',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'De melding \'Pre-filling\' inschakelen',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'De aanhef is een verplicht veld',
    'TCKLARNA_SET_TAC_URI'                              => 'URL naar uw algemene voorwaarden',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL naar het herroepingsrecht',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Verzendgegevens',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Geen validatie',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Validatie uitvoeren, maar time-outs negeren',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Succesvolle validatie vereist',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Bevestiging van de bestelling',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Kies de Klarna-betaalopties die u aan uw klanten wilt aanbieden:',
    'TCKLARNA_PAY_LATER'                                => 'Factuur',
    'TCKLARNA_PAY_LATER.'                               => 'Factuur.',
    'TCKLARNA_PAY_LATER_START'                          => 'Voor klanten die nu willen kopen en later willen betalen. Heel gemakkelijk binnen 14, 21 of 28 dagen, afhankelijk van de markt.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Met de optie ‘Factuur’ kunnen klanten eenvoudig en snel betalen, zonder dat ze persoonlijke gegevens of ingewikkelde nummers hoeven in te voeren. De klant kan kiezen tussen betaling via factuur of betaling in maand X.',
    'TCKLARNA_SLICE_IT'                                 => 'Aankoop op afbetaling.',
    'TCKLARNA_SLICE_IT.'                                => 'In termijnen betalen.',
    'TCKLARNA_SLICE_IT_START'                           => 'Verhoog de koopkracht van uw klanten door betaling in termijnen aan te bieden. Klanten kunnen hun aankopen in vaste maandelijkse termijnen over een periode van 6 tot 36 maanden afbetalen.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Via “afbetalen” kunnen klanten het aankoopbedrag tegen een lage rente in termijnen betalen. Dit vergroot de investeringsruimte en de koopkracht. De unieke kredietafhandeling van Klarna neemt slechts enkele ogenblikken in beslag en vereist slechts een minimale gegevensinvoer.',
    'TCKLARNA_PAY_NOW'                                  => 'Direct betalen',
    'TCKLARNA_PAY_NOW.'                                 => 'Direct betalen.',
    'TCKLARNA_PAY_NOW_START'                            => 'Eenvoudig en snel direct betalen met ‘Sofort bezahlen’ van Klarna. In Duitsland mogen Sofortüberweisung, creditcard en automatische incasso niet ontbreken in het aanbod.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Klanten die het volledige bedrag direct bij het afronden van de bestelling willen betalen, kunnen gebruikmaken van de optie "Direct betalen". Hierbij kunnen ze kiezen uit creditcard, automatische incasso en Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Handleiding: hoe activeer je<br /> Klarna?',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Klik in het OXID-backend op het nieuwe menu-item Klarna, vervolgens op de subcategorie Algemeen en selecteer daarna het gewenste Klarna-product.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Voer uw inloggegevens in (gebruikersnaam en wachtwoord) en stel onder Winkelinstellingen &gt; Betaalmethoden en &gt; Verzendmethoden de voor OXID gebruikelijke toewijzingen voor betaalmethoden in.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Sla de wijzigingen op.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'U bent nu online en kunt beginnen met verkopen via Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Ondersteuning voor verkopers',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Hier kunt u instellen of er eventueel extra merchantgegevens naar Klarna moeten worden verzonden. 
Voor een gedetailleerde beschrijving van de verschillende instellingen kunt u de tooltips raadplegen op 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, de <a class="cl-pink" href="%s" target="_blank">handleiding</a> lezen op 
of contact opnemen met de Klarna-integratiesupport.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Hier kunt u de ontwerpinstellingen configureren voor gebruik met de Klarna-module voor de OXID eShop. 
Voor een gedetailleerde beschrijving van de verschillende instellingen kunt u de tooltips raadplegen op 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, de <a class="cl-pink" href="%s" target="_blank">handleiding</a> lezen op 
of contact opnemen met de Klarna-integratiesupport.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Maak hier uw keuze voor Klarna Payments en stel de algemene instellingen in. 
Voor een gedetailleerde beschrijving van de verschillende instellingen kunt u de tooltips raadplegen op 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, de <a class="cl-pink" href="%s" target="_blank">handleiding</a> lezen op 
of contact opnemen met de Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Op deze pagina kunt u kiezen welke Klarna-betaalmethoden u wilt aanbieden. 
Voor een gedetailleerde beschrijving van de verschillende instellingen kunt u de tooltips raadplegen op 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, de <a class="cl-pink" href="%s" target="_blank">handleiding</a> lezen op 
of contact opnemen met de Klarna-integratiesupport.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Betaalwijze',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Externe betaalmethode',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Afbeeldings-URI voor externe betaalmethode',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Afbeeldingsgrootte: 69x24 pixels',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Afbeeldingsgrootte: 276x48 pixels',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'De gebruikershandleiding voor de Klarna-module voor de OXID eShop kunt u hier raadplegen.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Gebruikershandleiding',

    'TCKLARNA_CHOOSE'                                   => 'Kiezen',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informatie over het klantenaccount',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Volledig betalingsoverzicht',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Doorvoerveld',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Toewijzen aan een betaalmethode:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Welke bestellingen moeten volledig worden meegenomen in de betalingsgeschiedenis?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Alle bestellingen worden als betaald beschouwd, ongeacht de oxpaid-datum',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Alleen bestellingen doorsturen waarvan de Oxpaid-datum is ingesteld; onbetaalde bestellingen negeren',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Alle bestellingen die met deze betaalmethode zijn geplaatst, negeren',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Andere betalingsmogelijkheid',
    'TCKLARNA_DIRECT_BANKING'                           => 'Directe overschrijving',
    'TCKLARNA_CARD'                                     => 'Kaart',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Kies tussen Playground (testomgeving) en Live (productieomgeving). Schakel de productieomgeving pas in nadat de integratietests met succes zijn uitgevoerd en na overleg met uw Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Voer hier alstublieft uw Klarna API-inloggegevens in. Deze heeft u ontvangen in de welkomstmail van Klarna. Deze gebruikersnaam en dit wachtwoord gelden wereldwijd voor alle landen. Alleen als u verschillende inloggegevens voor verschillende landen hebt ontvangen, kunt u deze hieronder toevoegen.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Voer hier het wachtwoord in dat bij de gebruikte API-gebruikersnaam hoort. Dit wachtwoord hebt u ontvangen in de welkomstmail van Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Vul hier alstublieft uw Klarna Merchant ID in. Deze heeft u ontvangen in de welkomstmail van Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Kies uit de lijst aan de linkerkant het land waarvoor u landspecifieke inloggegevens van Klarna hebt ontvangen.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Voer hier de bijbehorende gebruikersnaam voor dit land in.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Voer hier het bijbehorende wachtwoord voor dit land in.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Voer hier de bijbehorende Merchant ID voor dit land in.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Schakelt de logfunctie in, zodat alle API-communicatie met Klarna wordt vastgelegd in de MySQL-tabel tcklarna_logs. Dit kan nuttig zijn bij analyses of het opsporen van fouten. In de productieve omgeving moet de functie worden uitgeschakeld, omdat er anders mogelijk grote hoeveelheden loggegevens worden opgestapeld en gevoelige gegevens worden opgeslagen.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Stuur de URL\'s van de productdetailpagina\'s van de producten die in het winkelmandje van uw klanten staan naar Klarna, zodat Klarna later vanuit het Klarna-portaal naar uw artikelen kan linken.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Stuur de URL\'s van de productafbeeldingen die in het winkelmandje van uw klanten staan naar Klarna, zodat Klarna deze in het Klarna-portaal kan weergeven.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Schakel de anonimisering in om de productnamen van de artikelen in het winkelmandje van uw klanten voor Klarna te verbergen. Dit wordt bijvoorbeeld aanbevolen voor online apotheken, maar mag alleen gebeuren na overleg met de Klarna Integration Manager.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Als de levering naar een ander afleveradres mogelijk moet zijn, schakel je deze optie in.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Als u het opgeven van een telefoonnummer verplicht wilt stellen, schakelt u deze optie in. Normaal gesproken is het telefoonnummer bij Klarna geen verplicht veld.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Als u het opgeven van een geboortedatum verplicht wilt stellen, schakelt u deze optie in. Normaal gesproken is de geboortedatum bij Klarna geen verplicht veld. Het opgeven ervan is echter wel nodig om aankoop op rekening of betaling in termijnen mogelijk te maken.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Momenteel niet geïmplementeerd',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Vermeld hier de URL van uw website met de uitleg over het herroepingsrecht. De URL moet beginnen met https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Deze verzendinformatie wordt aan de klant getoond op de bedankpagina nadat de bestelling is afgerond.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Wijs deze externe betaalmethode toe aan een van de vooraf gedefinieerde betaalmethoden',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Geef voor alle talen een URL op',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Geef een geldige URL op die begint met https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Deze schakelaar activeert de overdracht van aanvullende gegevens naar Klarna, in dit geval de klantaccountgegevens, waarin de datum van registratie van het klantaccount en de datum van de laatste wijziging zijn opgenomen.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Met deze schakelaar wordt de overdracht van aanvullende gegevens naar Klarna geactiveerd, in dit geval de ‘Payment History Full’, waarin de eerdere aankopen van de klant zijn opgenomen.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Geef alstublieft aan om welke betaalmethode het hier gaat.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Geef hier aan of, en zo ja welke, bestellingen met deze betaalmethode moeten worden opgenomen bij het overzetten van de bestelgeschiedenis van de klant. De afhankelijkheid van het veld OXORDER.OXPAID bepaalt of daarbij alleen betaalde bestellingen of alle bestellingen in aanmerking moeten worden genomen.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Het is mogelijk om met behulp van een pass-through-veld willekeurige gegevens naar Klarna door te sturen. Om deze functie te gebruiken, moet u een geschikte module in de OXID eShop installeren die de gewenste gegevens in het pass-through-veld schrijft. Een bijbehorende handleiding vindt u in de documentatie voor ontwikkelaars.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Met deze schakelaar activeert u een Klarna-banner op de startpagina van uw webshop in het standaardthema Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Hier kunt u de script-tag voor het invoegen van de banner invoeren. In het bannerportaal van Klarna vindt u eventueel nog meer banners waaruit u kunt kiezen.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Met deze schakelaar schakelt u de weergave van de Klarna-betaalmethode in de voettekst van uw webshop in het standaardthema Apex in.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Met deze schakelaar voeg je het Klarna-logo toe aan de voettekst van je webshop in het standaardthema Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Deze schakelaar voegt een \'Nu kopen\'-knop toe aan de productdetailpagina\'s van uw winkel in het standaardthema Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Kleur van het kader dat, indien er verschillende subopties beschikbaar zijn, in de winkel-frontend verschijnt nadat de betaalmethode Klarna is geselecteerd.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Kleur van het kader dat in de winkelinterface verschijnt wanneer er verschillende subopties beschikbaar zijn, nadat de betaalmethode Klarna is geselecteerd. Deze kleurwaarde wordt gebruikt om de momenteel geselecteerde suboptie te markeren.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Deze instelling heeft op het moment van publicatie van deze module nog geen effect.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Deze instelling heeft op het moment van publicatie van deze module nog geen effect.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Achtergrondkleur van de keuzeknoppen die in de winkel-frontend verschijnen wanneer er verschillende subopties beschikbaar zijn na selectie van de betaalmethode ‘Klarna’',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Deze instelling heeft op het moment van publicatie van deze module nog geen effect.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Kleur van de opsommingstekens bij de weergave van de betalingsgegevens op de pagina voor het selecteren van de betaalmethode.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Deze instelling heeft op het moment van publicatie van deze module nog geen effect.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Kleur van de links in de gedetailleerde beschrijving van de betaalmethoden op de pagina voor het selecteren van betaalmethoden.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Tekstkleur van de gedetailleerde beschrijving van de betaalmethoden op de pagina voor het selecteren van betaalmethoden.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternatieve tekstkleur voor de gedetailleerde beschrijving van de betaalmethoden op de pagina voor het selecteren van betaalmethoden.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Met deze instelling kunt u de mate van afronding van het kader bepalen dat, afhankelijk van de verschillende beschikbare subopties, wordt weergegeven in de winkelinterface nadat de betaalmethode Klarna is geselecteerd.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Dit tabblad geldt alleen voor bestellingen via Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'De volledige bestelling vastleggen',
    'KLARNA_CAPTURE_ID'                                 => 'Afschrijvings-ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-referentie',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Afschrijvingsbedrag',
    'KLARNA_CAPTURE_DATE'                               => 'Afgeschreven op',
    'KLARNA_REFUND_AMOUNT'                              => 'Terug te betalen bedrag',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Terugbetaling Toelichting',
    'KLARNA_REFUND_DATE'                                => 'Vervangen op',
    'KLARNA_CAPTURES'                                   => 'Afschrijvingen',
    'KLARNA_REFUNDS'                                    => 'Terugbetalingen',
    'KLARNA_CANCEL_ORDER'                               => 'Bestelling annuleren',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'De bestelling is geannuleerd. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Deze bestelling bekijken in het Klarna-portaal</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Let op!</strong> De gegevens van deze bestelling wijken af van de gegevens die bij Klarna zijn opgeslagen. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Let op! Vanwege de huidige bestelstatus kan deze aanpassing niet naar Klarna worden doorgegeven. Voer de betreffende aanpassing indien nodig handmatig door in het Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Let op! Uw laatste wijzigingen aan deze bestelling konden niet door Klarna worden verwerkt (reden: %s). Maak uw recente wijzigingen in de OXID eShop ongedaan of breng de betreffende aanpassing indien nodig handmatig aan in het Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Ongeautoriseerd verzoek. Controleer de instellingen van de Klarna-module, de Merchant ID en het bijbehorende wachtwoord',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Deze bestelling kon niet in het systeem van Klarna worden gevonden. Wijzigingen in de bestelgegevens worden daarom niet doorgegeven aan Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Onjuiste inloggegevens!</strong> Deze bestelling is geplaatst met de handelaars-ID <strong>%s</strong>. De handelaars-ID die momenteel is geconfigureerd voor <strong>%s</strong> is <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Productnaam',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Geanonimiseerde producttitel:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'De betaling wordt afgehandeld door onze partner Klarna. Houd rekening met de betalingsinformatie die Klarna u heeft toegestuurd. U kunt al uw aankopen beheren via Klarna.com of de Klarna-app en zelfs met slechts één klik betalen.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Kortingsbon',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Cadeauverpakking',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Wenskaart',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Fatale fout: Het is verplicht om een geldige, met SSL beveiligde (https) $this-&gt;sSSLShopURL op te geven in het bestand config.inc.php van uw webshop als u de %s wilt activeren!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Verkeerde inloggegevens!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Het bedrag is succesvol afgeschreven.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Het bedrag van de bestelling kon niet worden afgeschreven, omdat deze al was geannuleerd.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Voer hier de tekenreeks in die naar Klarna moet worden verzonden in plaats van de daadwerkelijke producttitel.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Uw wijzigingen aan deze bestelling worden niet doorgegeven aan Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Gebruikershandleiding',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registreren',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Meer informatie',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Ondersteunde soorten klanten',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Hier kunt u instellen of de webshop uitsluitend B2C-transacties (standaardinstelling), alleen B2B-transacties of zowel B2C- als B2B-transacties moet accepteren.<br />  Opmerking: Nadat u de klanttypes hebt aangepast, moet de sessiecache van de browser worden gewist, zodat de betaling kan worden getest.',
    'TCKLARNA_B2C'                                      => 'Alleen B2C-klanten',
    'TCKLARNA_B2B'                                      => 'Alleen B2B-klanten',
    'TCKLARNA_B2B_B2C'                                  => 'Voornamelijk B2B-klanten, maar ook B2C-klanten',
    'TCKLARNA_B2C_B2B'                                  => 'Voornamelijk B2C-klanten, maar ook B2B-klanten',
    'TCKLARNA_NEED_SUPPORT'                             => 'Heeft u hulp nodig bij de integratie?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Neem contact op met de klantenservice van Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Berichten op locatie',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Hier kunt u de on-site messaging configureren voor gebruik met de Klarna-module voor de OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Script',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion: productdetailpagina',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Credit Promotion-winkelwagen',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Top-strip-actie',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promotie in de voettekst',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Bannerpromotie',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Voeg hier alstublieft het JavaScript-bibliotheekcodefragment in dat nodig is voor On-Site Messaging en dat u in het Klarna Merchant Portal kunt vinden.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Voeg hier de placement-tag in om financiering en afbetaling via Credit Promotions op de productdetailpagina te promoten',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Voeg hier de placement-tag in om financiering en afbetaling via Credit Promotions op het winkelmandje-overzicht te promoten',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Voeg hier de placement-tag in om algemene en betaalmethode-specifieke informatie op de startpagina van de webshop onder de aandacht te brengen',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Voeg hier de placement-tag in om uw beschikbare Klarna-betaalmethoden in de voettekst van de webshop weer te geven',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Voeg hier de placement-tag in om een banner op de startpagina van uw winkel te plaatsen',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Wat is on-site messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Klanten zijn zich niet altijd bewust van de verschillende krediet- en financieringsmogelijkheden die voor hen beschikbaar zijn voordat ze bij de kassa komen. Financieringsmogelijkheden die al in een vroeg stadium beschikbaar zijn, beïnvloeden de aankoopbeslissing. 

On-Site Messaging is eenvoudig en probleemloos te integreren en biedt informatie op maat, variërend van algemene banners over het promoten van uw samenwerking met Klarna en de mogelijkheid tot betaling in termijnen tot gepersonaliseerde kredietacties op product- of winkelmandpagina\'s.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Meer informatie over de eerste stappen <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">vindt u hier</a>:<br /><br /> 
Log in op <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">het verkopersportaal</a> om uw persoonlijke JavaScript- en plaatsingscode te genereren. On-site messaging wordt in uw webshop geactiveerd zodra de JavaScript-code is opgeslagen en er ten minste één plaatsingscode is ingevoerd.<br /> 
U kunt deze functie op elk moment uitschakelen door de codes weer te verwijderen.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Dealerportaal',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Klarna Instant Shopping inschakelen',
    'TCKLARNA_IS_ENABLED'                               => 'Actief',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Knop Key vervangen',
    'TCKLARNA_IS_REPLACE'                               => 'Een nieuwe knop ‘Key’ aanmaken',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'U kunt de Button Key bijwerken als er aanpassingen nodig zijn in de configuratie- of identificatiegegevens bij Klarna. Normaal gesproken kunt u een eenmaal gegenereerde Button Key zo lang gebruiken als u wilt.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Schakel hier Klarna Instant Shopping in. Hierdoor wordt automatisch een knop gegenereerd voor gebruik in de frontend van de webshop.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Instellingen voor de knopstijl',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Kies alstublieft tussen een knop die volledig in de Klarna-stijl is vormgegeven en een neutralere ‘Light’-variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Kies alstublieft of de tekstkleur van de slogan onder de knop licht of donker moet zijn.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Kies alstublieft de gewenste tekst voor de knop.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Voorbeeld van de knop',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Weergeven op de productdetailpagina',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Schakel deze functie in om ervoor te zorgen dat de Klarna Instant Shopping-knop op alle productdetailpagina\'s in uw winkel wordt weergegeven.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Weergeven in het winkelmandje-overzicht',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Schakel deze functie in om de Klarna Instant Shopping-knop weer te geven in het winkelmandje-overzicht van uw webshop.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Overige instellingen voor Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Het afleveradres mag afwijken van het factuuradres',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Als de levering naar een ander afleveradres mogelijk moet zijn, schakel je deze optie in.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Geboortedatum als verplicht veld',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Als u het opgeven van een geboortedatum verplicht wilt stellen, schakelt u deze optie in. Normaal gesproken is de geboortedatum bij Klarna geen verplicht veld. Het opgeven ervan is echter wel nodig om aankoop op rekening of betaling in termijnen mogelijk te maken.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Nationaal ID-nummer als verplicht veld',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Geef aan of het nationale identificatienummer een verplicht veld moet zijn.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variatie',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Het telefoonnummer is een verplicht veld',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Geef aan of het telefoonnummer een verplicht veld moet zijn.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Kies uit de lijst welk land standaard moet worden ingesteld bij het openen van Klarna Instant Shopping, zolang de klant zijn land nog niet heeft opgegeven.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Voer hier de URL naar uw algemene voorwaarden in. Deze worden in de Klarna Instant Shopping-pop-up gelinkt. U moet een geldige URL opgeven die begint met https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Verzendmethoden',
    'TCKLARNA_COMPLETE_REFUND'                          => 'De volledige bestelling crediteren',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Er zijn geen actieve verzendmethoden gevonden',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Gebruikte betaalmethode: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Creditcard',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Automatische incasso',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Directe overschrijving',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rentevrije termijnen',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-factuur (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Factuur',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Betaling met kaart binnen 30 dagen',
];
