<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Français";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Démarrer',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Généralités',
    'TCKLARNA_CONFIGURATION'                            => 'Configuration',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configuration pour les paiements Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Paramètres de mise en page',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Modes de paiement externes',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Informations supplémentaires sur le revendeur',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Paramètres par défaut',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Réduction',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'Dans ce mode, il n\'y a pas de réglages.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Tous les paramètres ont été sauvegardés.',

    'TCKLARNA_EASY'                                     => 'C\'est aussi simple que ça d\'activer Klarna',
    'TCKLARNA_PHONE'                                    => 'Téléphone',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Horaires d\'ouverture',
    'TCKLARNA_MONDAY'                                   => 'lundi',
    'TCKLARNA_TUESDAY'                                  => 'mardi',
    'TCKLARNA_WEDNESDAY'                                => 'mercredi',
    'TCKLARNA_THURSDAY'                                 => 'jeudi',
    'TCKLARNA_FRIDAY'                                   => 'vendredi',
    'TCKLARNA_SATURDAY'                                 => 'samedi',
    'TCKLARNA_SUNDAY'                                   => 'dimanche',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Vos identifiants spécifiques à chaque pays',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Ajouter des identifiants d\'accès spécifiques à chaque pays',
    'TCKLARNA_COUNTRY'                                  => 'Pays',
    'TCKLARNA_MERCHANT_ID'                              => 'Nom d\'utilisateur API',
    'TCKLARNA_PASSWORD'                                 => 'Mot de passe API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Identifiant du commerçant',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Pays par défaut de la boutique',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Journalisation active',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Envoyer des données produit détaillées à Klarna ?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL des produits',
    'TCKLARNA_IMAGE_URLS'                               => 'URL des images',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymiser',
    'TCKLARNA_ADD'                                      => 'Ajouter',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Paiements Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Sélectionner le mode du module Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Avec Klarna, les clients peuvent payer de trois façons différentes : virement immédiat, paiement différé ou paiement échelonné. Cela leur permet d\'essayer d\'abord les articles et de ne payer que ceux qu\'ils souhaitent conserver, de financer leurs achats dans la boutique ou de payer immédiatement. La facturation, l\'achat à crédit, le virement instantané ou le prélèvement automatique peuvent être activés via une intégration et sont toujours à jour sur le plan juridique et en termes de contenu grâce à la solution iFrame de Klarna.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Les modes de paiement les plus populaires. Sécurisés et faciles à intégrer.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Bienvenue dans les paramètres de configuration de Klarna Payments. Vous trouverez ici tout ce dont vous avez besoin pour l\'activation. Sélectionnez les sous-rubriques Klarna dans la barre de gauche pour terminer la configuration du module.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Créer un compte client dans la boutique en ligne OXID',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Inscription à la newsletter',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Créer un compte client ET s\'abonner à la newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Ne pas afficher de case à cocher',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Afficher sur la page d\'accueil de la boutique ?',
    'TCKLARNA_BANNER_SRC'                               => 'Source de la bannière Klarna',
    'TCKLARNA_FOOTER'                                   => 'Pied de page',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Que faut-il afficher dans le pied de page ?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Affichage des modes de paiement',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo Klarna',
    'TCKLARNA_DESIGN'                                   => 'Conception',
    'TCKLARNA_LONG_VERSION'                             => 'Version longue :',
    'TCKLARNA_SHORT_VERSION'                            => 'Version courte :',
    'TCKLARNA_WHITE'                                    => 'Blanc :',
    'TCKLARNA_BLACK'                                    => 'Noir :',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Page de détails de l\'article et panier',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Afficher le widget du mode de paiement Klarna ?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Sur la page de détails de l\'article',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Sur la page du panier',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Afficher le bouton « Acheter maintenant » ?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Options de conception de paiement Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Paramètres de couleur :',
    'TCKLARNA_BORDER'                                   => 'Bordure :',
    'TCKLARNA_BORDER_SELECTED'                          => 'Bordure sélectionnée :',
    'TCKLARNA_BUTTON'                                   => 'Bouton :',
    'TCKLARNA_BUTTON_TEXT'                              => 'Texte du bouton :',
    'TCKLARNA_CHECKBOX'                                 => 'Case à cocher :',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Cochez la case :',
    'TCKLARNA_DETAILS'                                  => 'Détails :',
    'TCKLARNA_HEADER'                                   => 'En-tête :',
    'TCKLARNA_LINK'                                     => 'Lien :',
    'TCKLARNA_TEXT'                                     => 'Texte :',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Texte complémentaire :',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Réglage du rayon :',
    'TCKLARNA_BORDER_RADIUS'                            => 'Rayon de la bordure :',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'L\'adresse de livraison peut être différente de l\'adresse de facturation',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Le numéro de téléphone est un champ obligatoire',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'La date de naissance est un champ obligatoire',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Activer la livraison vers une Packstation DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Activer le pré-remplissage',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Activer la notification de pré-remplissage',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Le champ « Formule de politesse » est obligatoire',
    'TCKLARNA_SET_TAC_URI'                              => 'Lien vers vos conditions générales de vente',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Lien vers la page relative au droit de rétractation',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Détails de la livraison',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Pas de validation',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Effectuer la validation, mais ignorer les délais d\'expiration',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Une validation réussie est nécessaire',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Validation de la commande',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Veuillez sélectionner les options de paiement Klarna que vous souhaitez proposer à vos clients :',
    'TCKLARNA_PAY_LATER'                                => 'facture',
    'TCKLARNA_PAY_LATER.'                               => 'Facture.',
    'TCKLARNA_PAY_LATER_START'                          => 'Pour les clients qui souhaitent acheter maintenant et payer plus tard. En toute simplicité, dans un délai de 14, 21 ou 28 jours, selon le marché.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'L\'option « Facture » permet aux clients d\'effectuer leur paiement facilement et rapidement, sans avoir à saisir de données personnelles ni de numéros compliqués. Le client a le choix entre la facture et le paiement au mois X.',
    'TCKLARNA_SLICE_IT'                                 => 'Achat à crédit.',
    'TCKLARNA_SLICE_IT.'                                => 'Payer en plusieurs fois.',
    'TCKLARNA_SLICE_IT_START'                           => 'Augmentez le pouvoir d\'achat de vos clients grâce au paiement échelonné. Les clients peuvent régler leurs achats par versements mensuels fixes sur une période de 6 à 36 mois.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Grâce au « paiement échelonné », les clients peuvent répartir le montant de leurs achats en plusieurs versements à un taux d\'intérêt faible. Cela leur permet d\'augmenter leur budget d\'investissement et leur pouvoir d\'achat. La procédure de crédit unique de Klarna ne prend que quelques instants et ne nécessite que très peu de données.',
    'TCKLARNA_PAY_NOW'                                  => 'Payer immédiatement',
    'TCKLARNA_PAY_NOW.'                                 => 'Payer immédiatement.',
    'TCKLARNA_PAY_NOW_START'                            => 'Paiement direct simple et rapide grâce à la solution « Payer immédiatement » de Klarna. En Allemagne, le virement instantané, la carte de crédit et le prélèvement automatique sont des moyens de paiement incontournables.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Les clients qui souhaitent régler la totalité du montant dès la finalisation de leur commande peuvent utiliser l\'option « Payer immédiatement ». Ils ont le choix entre la carte bancaire, le prélèvement automatique et le virement instantané.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Guide <br />d\'activation de Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Dans l\'interface d\'administration OXID, cliquez sur le nouvel élément de menu « Klarna », puis sur la sous-catégorie « Général », et sélectionnez ensuite le produit Klarna souhaité.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Saisissez vos identifiants (nom d\'utilisateur et mot de passe), puis configurez les associations de modes de paiement propres à OXID dans « Paramètres de la boutique » &gt; « Modes de paiement » et « Modes de livraison ».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Enregistrez les modifications.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Vous êtes désormais en ligne et pouvez commencer à vendre avec Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Assistance aux commerçants',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Vous pouvez ici configurer si des données supplémentaires du commerçant doivent être transmises à Klarna, le cas échéant. 
Pour une description détaillée des différents paramètres, veuillez consulter les infobulles 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lire le <a class="cl-pink" href="%s" target="_blank">manuel</a> 
ou contacter le support d\'intégration Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Vous pouvez ici configurer les paramètres de mise en page à utiliser avec le module Klarna pour la boutique en ligne OXID. 
Pour une description détaillée des différents paramètres, veuillez consulter les infobulles 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lire le <a class="cl-pink" href="%s" target="_blank">manuel</a> 
ou contacter le support d\'intégration Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Vous pouvez ici définir les options relatives aux paiements Klarna et configurer les paramètres généraux. 
Pour une description détaillée des différents paramètres, veuillez consulter les infobulles 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lire le <a class="cl-pink" href="%s" target="_blank">manuel</a> 
ou contacter le support d\'intégration Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Sur cette page, vous pouvez choisir les modes de paiement Klarna que vous souhaitez proposer. 
Pour une description détaillée des différents paramètres, veuillez consulter les infobulles 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lire le <a class="cl-pink" href="%s" target="_blank">manuel</a> 
ou contacter le support d\'intégration Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Mode de paiement',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Mode de paiement externe',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI de l\'image pour le mode de paiement externe',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Dimensions de l\'image : 69 x 24 pixels',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Dimensions de l\'image : 276 x 48 pixels',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Vous pouvez consulter ici le manuel d\'utilisation du module Klarna pour OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manuel d\'utilisation',

    'TCKLARNA_CHOOSE'                                   => 'Voter',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informations sur le compte client',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Historique complet des paiements',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Champ de transfert',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Attribuer un type de mode de paiement :',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Quelles commandes doivent être prises en compte dans l\'historique complet des paiements ?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Considérer toutes les commandes comme payées, quelle que soit la date d\'oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Ne transmettre que les commandes pour lesquelles une date « oxpaid » a été définie ; ignorer les commandes non payées',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorer toutes les commandes effectuées avec ce mode de paiement',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Autre mode de paiement',
    'TCKLARNA_DIRECT_BANKING'                           => 'Virement instantané',
    'TCKLARNA_CARD'                                     => 'Carte',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Choisissez entre « Playground » (mode test) et « Live » (mode production). N\'activez le mode production qu\'après avoir effectué avec succès les tests d\'intégration et après avoir consulté votre responsable de l\'intégration Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Veuillez saisir ici vos identifiants d\'accès à l\'API Klarna. Vous les avez reçus dans l\'e-mail de bienvenue envoyé par Klarna. Ce nom d\'utilisateur et ce mot de passe sont valables dans tous les pays. Si vous avez reçu des identifiants différents pour certains pays, vous pouvez les ajouter ci-dessous.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Saisissez ici le mot de passe correspondant au nom d\'utilisateur API que vous utilisez. Ce mot de passe vous a été communiqué dans l\'e-mail de bienvenue envoyé par Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Veuillez saisir ici votre identifiant de commerçant Klarna. Vous l\'avez reçu dans l\'e-mail de bienvenue envoyé par Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Dans la liste de gauche, sélectionnez le pays pour lequel vous avez reçu les identifiants d\'accès spécifiques à ce pays de la part de Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Veuillez saisir ici le nom d\'utilisateur correspondant à ce pays.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Veuillez saisir ici le mot de passe correspondant à ce pays.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Veuillez saisir ici l\'identifiant de commerçant correspondant à ce pays.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Active la fonction de journalisation afin que toutes les communications API avec Klarna soient enregistrées dans la table MySQL « tcklarna_logs ». Cela peut s\'avérer utile pour l\'analyse ou le dépannage. En environnement de production, cette fonction doit être désactivée, car sinon, des volumes importants de journaux risquent de s\'accumuler et des données sensibles pourraient être enregistrées.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Envoyez à Klarna les URL des pages de détail des produits qui se trouvent dans le panier de vos clients, afin que Klarna puisse ensuite créer des liens vers vos articles depuis le portail Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Envoyez à Klarna les URL des images des produits figurant dans le panier de vos clients afin que Klarna puisse les afficher sur le portail Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Activez l\'anonymisation pour masquer à Klarna les noms des articles figurant dans le panier de vos clients. Cette option est recommandée, par exemple, pour les pharmacies en ligne, mais ne doit être mise en place qu\'après consultation du responsable de l\'intégration Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Si vous souhaitez autoriser la livraison à une autre adresse, cochez cette case.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Si vous souhaitez rendre obligatoire la saisie d\'un numéro de téléphone, cochez cette case. En règle générale, le numéro de téléphone n\'est pas un champ obligatoire pour Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Si vous souhaitez rendre obligatoire la saisie de la date de naissance, cochez cette case. En règle générale, la date de naissance n\'est pas un champ obligatoire pour Klarna. Elle est toutefois nécessaire pour permettre l\'achat sur facture ou le paiement échelonné.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Non implémenté pour le moment',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Indiquez ici l\'URL de votre site web contenant les informations relatives au droit de rétractation. L\'URL doit commencer par https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Ces informations relatives à la livraison s\'affichent sur la page de remerciement une fois la commande finalisée.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Attribuez ce mode de paiement externe à l\'un des modes de paiement prédéfinis',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Veuillez indiquer une URL pour chaque langue',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Veuillez saisir une URL valide commençant par https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Ce bouton active la transmission de données supplémentaires à Klarna, en l\'occurrence les informations relatives au compte client, qui comprennent la date de création du compte client et celle de sa dernière modification.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Ce bouton active la transmission de données supplémentaires à Klarna, en l\'occurrence l\'historique complet des paiements (« Payment History Full »), qui contient les achats effectués jusqu\'à présent par le client.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Veuillez indiquer de quel type de paiement il s\'agit pour ce mode de paiement.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Veuillez indiquer ici si, et le cas échéant lesquelles, des commandes réglées avec ce mode de paiement doivent être incluses lors du transfert de l\'historique des commandes du client. La dépendance du champ OXORDER.OXPAID détermine si seules les commandes payées ou toutes les commandes doivent être prises en compte.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Il est possible de transmettre à Klarna d\'autres données de votre choix à l\'aide d\'un champ « pass-through ». Pour utiliser cette fonctionnalité, vous devez installer un module adapté dans OXID eShop, qui enregistrera les données souhaitées dans le champ « pass-through ». Vous trouverez des instructions à ce sujet dans la documentation destinée aux développeurs.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Ce bouton vous permet d\'activer une bannière Klarna sur la page d\'accueil de votre boutique dans le thème par défaut Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Vous pouvez saisir ici la balise script permettant d\'intégrer la bannière. Vous trouverez éventuellement d\'autres bannières parmi lesquelles choisir sur le portail dédié aux bannières de Klarna.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Ce bouton vous permet d\'activer l\'affichage du mode de paiement Klarna dans le pied de page de votre boutique, dans le thème par défaut Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Ce bouton vous permet d\'ajouter le logo Klarna dans le pied de page de votre boutique, dans le thème par défaut Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Cet interrupteur ajoute un bouton « Acheter maintenant » sur les pages de détails des articles de votre boutique dans le thème par défaut Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Couleur du cadre qui s\'affiche dans l\'interface client de la boutique après avoir sélectionné le mode de paiement Klarna, lorsque plusieurs sous-options sont disponibles.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Couleur du cadre qui s\'affiche dans l\'interface client de la boutique après la sélection du mode de paiement Klarna, lorsque plusieurs sous-options sont disponibles. Cette couleur sert à mettre en évidence la sous-option actuellement sélectionnée.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Au moment de la publication de ce module, ce paramètre n\'a encore aucun effet.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Au moment de la publication de ce module, ce paramètre n\'a encore aucun effet.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Couleur d\'arrière-plan des boutons radio qui s\'affichent dans l\'interface client de la boutique après la sélection du mode de paiement Klarna, lorsque plusieurs sous-options sont disponibles',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Au moment de la publication de ce module, ce paramètre n\'a encore aucun effet.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Couleur des puces dans l\'affichage des détails de paiement sur la page de sélection des modes de paiement.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Au moment de la publication de ce module, ce paramètre n\'a encore aucun effet.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Couleur des liens figurant dans la description détaillée des modes de paiement sur la page de sélection des modes de paiement.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Couleur du texte de la description détaillée des modes de paiement sur la page de sélection des modes de paiement.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Couleur alternative du texte de la description détaillée des modes de paiement sur la page de sélection des modes de paiement.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Ce paramètre vous permet de définir le degré d\'arrondi du cadre qui s\'affiche dans l\'interface client de la boutique après la sélection du mode de paiement Klarna, en fonction des différentes sous-options disponibles.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Cet onglet concerne uniquement les commandes passées via Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Enregistrer la commande complète',
    'KLARNA_CAPTURE_ID'                                 => 'Référence du prélèvement',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Référence Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Montant du prélèvement',
    'KLARNA_CAPTURE_DATE'                               => 'Débité le',
    'KLARNA_REFUND_AMOUNT'                              => 'montant du remboursement',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Remboursement - Explications',
    'KLARNA_REFUND_DATE'                                => 'Remplacé par',
    'KLARNA_CAPTURES'                                   => 'Prélèvements',
    'KLARNA_REFUNDS'                                    => 'Remboursements',
    'KLARNA_CANCEL_ORDER'                               => 'Annuler la commande',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'La commande a été annulée. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Accéder à cette commande sur le portail Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Attention !</strong> Les informations relatives à cette commande diffèrent de celles enregistrées chez Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Attention ! En raison du statut actuel de la commande, cette modification ne peut pas être transmise à Klarna. Si nécessaire, effectuez cette modification manuellement dans le portail Klarna Merchant.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Attention ! Klarna n\'a pas pu traiter vos dernières modifications apportées à cette commande (motif : %s). Veuillez annuler vos modifications récentes dans la boutique en ligne OXID ou, si nécessaire, effectuer manuellement les modifications correspondantes dans le portail commerçant Klarna.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Requête non autorisée. Vérifiez les paramètres du module Klarna, ainsi que l\'identifiant du commerçant et le mot de passe associé.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Cette commande n\'a pas pu être retrouvée dans le système de Klarna. Les modifications apportées aux informations de la commande ne seront donc pas transmises à Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Identifiants incorrects !</strong> Cette commande a été passée avec l\'identifiant de revendeur <strong>%s</strong>. L\'identifiant de revendeur actuellement configuré pour <strong>%s</strong> est <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nom du produit',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Intitulé anonymisé du produit :',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Le paiement est géré par notre partenaire Klarna. Veuillez prendre connaissance des informations de paiement envoyées par Klarna. Vous pouvez gérer tous vos achats sur Klarna.com ou via l\'application Klarna, et même payer en un seul clic.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Bon de réduction',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Emballage cadeau',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Carte de vœux',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Erreur fatale : vous devez impérativement indiquer une URL $this-&gt;sSSLShopURL valide et sécurisée par SSL (https) dans le fichier config.inc.php de votre boutique si vous souhaitez activer l\'%s !',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Identifiants incorrects !</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Le montant a bien été prélevé.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' La commande n\'a pas pu être débitée, car elle avait déjà été annulée.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Saisissez ici la chaîne de caractères qui doit être envoyée à Klarna à la place du titre réel du produit.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Les modifications que vous apportez à cette commande ne seront pas transmises à Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manuel d\'utilisation',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'S\'inscrire',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'En savoir plus',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Types de clients pris en charge',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Vous pouvez définir ici si la boutique doit accepter exclusivement des transactions B2C (paramètre par défaut), uniquement des transactions B2B, ou à la fois des transactions B2C et B2B.<br />  Remarque : après avoir modifié les types de clients, il faut vider le cache de session du navigateur afin de pouvoir tester le paiement.',
    'TCKLARNA_B2C'                                      => 'Uniquement les clients B2C',
    'TCKLARNA_B2B'                                      => 'Clients B2B uniquement',
    'TCKLARNA_B2B_B2C'                                  => 'Principalement des clients B2B, mais aussi des clients B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Principalement des clients B2C, mais aussi des clients B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Avez-vous besoin d\'aide pour l\'intégration ?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contactez le service d\'assistance aux commerçants de Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Messagerie sur site',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Vous pouvez ici configurer la messagerie sur site à utiliser avec le module Klarna pour la boutique en ligne OXID.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Scénario',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Page de détail du produit « Promotion de crédit »',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Promotion sur le crédit - Panier',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promotion « Top-strip »',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promotion en pied de page',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Bannière promotionnelle',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Veuillez insérer ici l\'extrait de code de la bibliothèque JavaScript nécessaire au fonctionnement de la messagerie sur site, que vous pouvez obtenir sur le portail des commerçants Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Veuillez insérer ici la balise de placement afin de promouvoir le financement et l\'achat à crédit proposé par Credit Promotions sur la page de détails de l\'article',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Veuillez insérer ici la balise de placement afin de promouvoir le financement et l\'achat à crédit proposé par Credit Promotions sur la page récapitulative du panier.',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Veuillez insérer ici la balise de placement afin de mettre en avant des informations générales et spécifiques aux modes de paiement sur la page d\'accueil de la boutique.',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Veuillez insérer ici la balise de placement afin d\'afficher les modes de paiement Klarna disponibles dans le pied de page de la boutique',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Veuillez insérer ici la balise de placement pour ajouter une bannière sur la page d\'accueil de votre boutique',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Qu\'est-ce que la messagerie sur site ?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Les clients ne sont pas toujours conscients des différentes possibilités de crédit et de financement qui s\'offrent à eux avant d\'arriver à la caisse. Les options de financement proposées dès le début influencent la décision d\'achat. 
 
 La messagerie sur site est simple et facile à intégrer ; elle propose des informations sur mesure, allant des bannières générales mettant en avant votre partenariat avec Klarna et la disponibilité du paiement échelonné, jusqu’aux offres de crédit personnalisées sur les pages de produits ou de panier.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Vous trouverez ici</a> de plus amples <br /><br />informations sur la mise en route : 
Connectez-vous au <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">portail des marchands</a> pour générer votre code JavaScript et votre code de placement personnels. La fonctionnalité « On-Site-Messaging » sera activée dans votre boutique dès que le code JavaScript aura été enregistré et qu\'au moins un code de placement aura été saisi.<br /> 
Vous pouvez la désactiver à tout moment en supprimant les codes.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portail des revendeurs',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Activer Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Actif',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Remplacer la touche « Button »',
    'TCKLARNA_IS_REPLACE'                               => 'Créer un nouveau bouton « Key »',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Vous pouvez mettre à jour la clé du bouton si des données de configuration ou d\'identification nécessitent une modification de la part de Klarna. En règle générale, une fois générée, vous pouvez utiliser la clé du bouton aussi longtemps que vous le souhaitez.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Activez ici Klarna Instant Shopping. Cela génère automatiquement un bouton à intégrer dans l\'interface publique de votre boutique.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Paramètres de personnalisation des boutons',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Veuillez choisir entre un bouton entièrement personnalisé aux couleurs de Klarna et une version « Light » plus neutre.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Veuillez choisir si la couleur du texte du slogan situé sous le bouton doit être claire ou foncée.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Veuillez choisir le libellé souhaité pour le bouton.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Aperçu du bouton',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Afficher sur la page de détail de l\'article',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Activez cette fonctionnalité pour que le bouton « Klarna Instant Shopping » s\'affiche sur toutes les pages de détails des articles de votre boutique.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Afficher dans le récapitulatif du panier',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Activez cette fonctionnalité pour que le bouton « Klarna Instant Shopping » s\'affiche dans la page récapitulative du panier de votre boutique.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Autres paramètres d\'Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'L\'adresse de livraison peut être différente de l\'adresse de facturation',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Si vous souhaitez autoriser la livraison à une autre adresse, cochez cette case.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'La date de naissance est un champ obligatoire',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Si vous souhaitez rendre obligatoire la saisie de la date de naissance, cochez cette case. En règle générale, la date de naissance n\'est pas un champ obligatoire pour Klarna. Elle est toutefois nécessaire pour permettre l\'achat sur facture ou le paiement échelonné.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Le numéro d\'identification national est un champ obligatoire',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Veuillez indiquer si le numéro d\'identification national doit être un champ obligatoire.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variation',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Le numéro de téléphone est un champ obligatoire',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Veuillez indiquer si le numéro de téléphone doit être un champ obligatoire.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Veuillez sélectionner dans la liste le pays qui doit être sélectionné par défaut lors de l\'ouverture de Klarna Instant Shopping, tant que le client n\'a pas encore indiqué son pays.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Indiquez ici l\'URL de vos conditions générales de vente. Un lien vers celles-ci sera affiché dans la fenêtre contextuelle Klarna Instant Shopping. Vous devez indiquer une URL valide commençant par https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Modes de livraison',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Créditer la totalité de la commande',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Aucun mode de livraison actif n\'a été trouvé',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Mode de paiement utilisé : ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'carte de crédit',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'prélèvement automatique',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Virement instantané',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 versements sans intérêts',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financement',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Facture B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'facture',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Paiement par carte dans un délai de 30 jours',
];
