<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Dansk";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Generelt',
    'TCKLARNA_CONFIGURATION'                            => 'Konfiguration',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfiguration af Klarna-betalinger',
    'TCKLARNA_KLARNADESIGN'                             => 'Designindstillinger',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Eksterne betalingsmetoder',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Yderligere forhandleroplysninger',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Grundindstillinger',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Rabat',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'I denne tilstand er der ingen indstillinger.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Alle indstillinger er blevet gemt.',

    'TCKLARNA_EASY'                                     => 'Så nemt er det at aktivere Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Åbningstider',
    'TCKLARNA_MONDAY'                                   => 'Mandag',
    'TCKLARNA_TUESDAY'                                  => 'Tirsdag',
    'TCKLARNA_WEDNESDAY'                                => 'Onsdag',
    'TCKLARNA_THURSDAY'                                 => 'torsdag',
    'TCKLARNA_FRIDAY'                                   => 'fredag',
    'TCKLARNA_SATURDAY'                                 => 'Lørdag',
    'TCKLARNA_SUNDAY'                                   => 'søndag',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Dine landespecifikke loginoplysninger',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Tilføj landespecifikke adgangsoplysninger',
    'TCKLARNA_COUNTRY'                                  => 'Land',
    'TCKLARNA_MERCHANT_ID'                              => 'API-brugernavn',
    'TCKLARNA_PASSWORD'                                 => 'API-adgangskode',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Forhandler-ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Butikkens standardland',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Logning aktiv',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Skal der sendes udvidede produktdata til Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Produkt-URL\'er',
    'TCKLARNA_IMAGE_URLS'                               => 'Billed-URL\'er',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymisere',
    'TCKLARNA_ADD'                                      => 'Tilføj',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-betalinger',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Vælg Klarna-modul og -tilstand',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Med Klarna kan slutkunderne betale på tre måder: Sofortüberweisung, senere eller i rater. Det giver slutkunderne mulighed for først at prøve varerne og kun betale for det, de ønsker at beholde, finansiere produkter i butikken eller betale med det samme. Faktura, afbetalingskøb, øjeblikkelig bankoverførsel eller direkte debitering kan du aktivere med en integration, og takket være Klarnas iFrame-løsning er de altid opdaterede, både juridisk og indholdsmæssigt.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'De mest populære betalingsmetoder. Sikre og nemme at integrere.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Hjertelig velkommen til konfigurationsindstillingerne for Klarna Payments. Her finder du alt, hvad der skal til for at aktivere tjenesten. Vælg undermenupunkterne for Klarna i venstre sidepanel for at afslutte opsætningen af modulet.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Opret en kundekonto i OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Tilmelding til nyhedsbrev',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Opret kundekonto OG tilmelding til nyhedsbrev',
    'TCKLARNA_NO_CHECKBOX'                              => 'Vis ikke afkrydsningsfeltet',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Skal det vises på butikkens forside?',
    'TCKLARNA_BANNER_SRC'                               => 'Kilde til Klarna-banneret',
    'TCKLARNA_FOOTER'                                   => 'Fodnote',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Hvad skal der vises i sidefoden?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visning af betalingsmetoder',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna-logoet',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Lang version:',
    'TCKLARNA_SHORT_VERSION'                            => 'Kort version:',
    'TCKLARNA_WHITE'                                    => 'Hvid:',
    'TCKLARNA_BLACK'                                    => 'Sort:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Produktdetaljeside og indkøbskurv',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Skal Klarna-betalingsmetode-widgeten vises?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'På artiklens detaljeside',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'På siden med indkøbskurven',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Skal knappen »Køb nu« vises?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Klarna-betalingsdesignmuligheder',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Farveindstillinger:',
    'TCKLARNA_BORDER'                                   => 'Kant:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Valgt grænse:',
    'TCKLARNA_BUTTON'                                   => 'Knap:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Tekst på knappen:',
    'TCKLARNA_CHECKBOX'                                 => 'Afkrydsningsfelt:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Afkrydsningsfelt:',
    'TCKLARNA_DETAILS'                                  => 'Detaljer:',
    'TCKLARNA_HEADER'                                   => 'Overskrift:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Tekst:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Yderligere tekst:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Indstilling af radius:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Kantradius:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Leveringsadressen må afvige fra fakturaadressen',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefonnummeret er et obligatorisk felt',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Fødselsdato er et obligatorisk felt',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktivér levering til DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktivér forudfyldning',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktivér bemærkning om forudfyldning',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Titel er et obligatorisk felt',
    'TCKLARNA_SET_TAC_URI'                              => 'URL til jeres vilkår og betingelser',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL vedrørende fortrydelsesretten',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Forsendelsesoplysninger',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Ingen validering',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Udfør validering, men ignorér timeouts',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Validering skal gennemføres med succes',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Bekræftelse af bestilling',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vælg venligst de Klarna-betalingsmuligheder, som du ønsker at tilbyde dine kunder:',
    'TCKLARNA_PAY_LATER'                                => 'Regning',
    'TCKLARNA_PAY_LATER.'                               => 'Regning.',
    'TCKLARNA_PAY_LATER_START'                          => 'Til kunder, der gerne vil købe nu og betale senere. Helt bekvemt inden for 14, 21 eller 28 dage, afhængigt af markedet.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Funktionen »Faktura« gør betalingsprocessen nem og hurtig for kunderne, uden at de behøver at indtaste personlige oplysninger eller komplicerede numre. Kunden kan vælge mellem faktura og betaling i måned X.',
    'TCKLARNA_SLICE_IT'                                 => 'Afbetalingskøb.',
    'TCKLARNA_SLICE_IT.'                                => 'Betal i rater.',
    'TCKLARNA_SLICE_IT_START'                           => 'Øg dine kunders købekraft ved at tilbyde afbetaling. Kunderne kan betale for deres indkøb i faste månedlige rater over en periode på 6 til 36 måneder.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Med »afbetalingskøb« kan kunderne dele købsbeløbet op i mindre rater til en lav rente. Det øger investeringsrammen og købekraften. Klarnas unikke kreditbehandling tager kun få øjeblikke og kræver kun en minimal indtastning af oplysninger.',
    'TCKLARNA_PAY_NOW'                                  => 'Betal nu',
    'TCKLARNA_PAY_NOW.'                                 => 'Betal med det samme.',
    'TCKLARNA_PAY_NOW_START'                            => 'Enkel og hurtig direkte betaling med Klarnas »Sofort bezahlen«. I Tyskland bør Sofortüberweisung, kreditkort og direkte debitering være en fast del af betalingsudbuddet.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Kunder, der ønsker at betale det fulde beløb med det samme, når de afslutter deres bestilling, kan benytte sig af muligheden »Betal nu«. Her kan man vælge mellem kreditkort, direkte debitering og Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Vejledning i, hvordan man <br />aktiverer Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Klik på det nye menupunkt »Klarna« i OXID-backend, vælg underkategorien »Generelt«, og vælg derefter det ønskede Klarna-produkt.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Indtast dine loginoplysninger (brugernavn og adgangskode), og foretag de for OXID typiske tilknytninger for betalingsmetoder under »Butiksindstillinger« &gt; »Betalingsmetoder« samt »Forsendelsesmetoder«.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Gem ændringerne.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Du er nu online og kan begynde at sælge med Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Support til forhandlere',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Her kan du konfigurere, om eventuelle ekstra forhandleroplysninger skal overføres til Klarna. 
For en detaljeret beskrivelse af de forskellige indstillinger henvises der til værktøjstipene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, læs <a class="cl-pink" href="%s" target="_blank">vejledningen</a> 
eller kontakt Klarna Integration Support.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Her kan du konfigurere designindstillingerne til brug med Klarna-modulet til OXID eShop. 
For en detaljeret beskrivelse af de forskellige indstillinger henvises der til værktøjstipene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, læs <a class="cl-pink" href="%s" target="_blank">vejledningen</a> 
eller kontakt Klarna Integration Support.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Her kan du vælge indstillinger for Klarna Payments og foretage overordnede indstillinger. 
For en detaljeret beskrivelse af de forskellige indstillinger henvises der til værktøjstipene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, læs <a class="cl-pink" href="%s" target="_blank">vejledningen</a> 
eller kontakt Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'På denne side vælger du, hvilke Klarna-betalingsmetoder du ønsker at tilbyde. 
For en detaljeret beskrivelse af de forskellige indstillinger henvises der til værktøjstipene 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, læs <a class="cl-pink" href="%s" target="_blank">vejledningen</a> 
eller kontakt Klarna Integration Support.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Betalingsmåde',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Ekstern betalingsmetode',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Billede-URI for ekstern betalingsmetode',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Billedstørrelse: 69x24 pixel',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Billedstørrelse: 276x48 pixel',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Du kan se brugervejledningen til Klarna-modulet til OXID eShop her.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Brugervejledning',

    'TCKLARNA_CHOOSE'                                   => 'Vælg',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Oplysninger om kundekontoen',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Fuldstændig betalingshistorik',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Gennemløbsfelt',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Tildel betalingsmetode:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Hvilke ordrer skal medtages i den fulde betalingshistorik?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Alle ordrer betragtes som betalte, uanset oxpaid-datoen',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Send kun ordrer, hvor der er angivet en oxpaid-dato; ignorér ubetalte ordrer',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Alle ordrer, der er afgivet med denne betalingsmetode, ignoreres',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Anden betalingsmulighed',
    'TCKLARNA_DIRECT_BANKING'                           => 'Øjeblikkelig overførsel',
    'TCKLARNA_CARD'                                     => 'Kort',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Vælg mellem Playground (testdrift) og Live (produktiv drift). Aktiver først produktiv drift, når integrationstestene er gennemført med succes, og efter at have rådført dig med din Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Indtast venligst dine Klarna API-adgangskoder her. Du har modtaget disse i velkomst-e-mailen fra Klarna. Dette brugernavn og denne adgangskode gælder globalt for alle lande. Kun hvis du har modtaget forskellige adgangskoder for forskellige lande, kan du tilføje disse længere nede.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Indtast her din adgangskode, der passer til det anvendte API-brugernavn. Du har modtaget denne adgangskode i velkomst-e-mailen fra Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Indtast venligst dit Klarna-forhandler-ID her. Du har modtaget dette i velkomst-e-mailen fra Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Vælg det land i listen til venstre, som du har modtaget landespecifikke adgangsoplysninger fra Klarna for.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Indtast venligst det relevante brugernavn for dette land her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Indtast venligst den tilhørende adgangskode for dette land her.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Indtast venligst det tilhørende Merchant ID for dette land her.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktiverer logfunktionen, så al API-kommunikation med Klarna registreres i MySQL-tabellen tcklarna_logs. Dette kan være nyttigt ved analyse eller fejlfinding. I produktionsdrift bør funktionen være deaktiveret, da der ellers kan ophobes store mængder logfiler, og følsomme data kan blive gemt.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Send URL’erne til produktdetaljesiderne for de varer, der ligger i dine kunders indkøbskurv, til Klarna, så Klarna senere kan linke til dine varer fra Klarna-portalen.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Send URL’erne til produktbillederne for de varer, der ligger i dine kunders indkøbskurv, til Klarna, så Klarna kan vise dem i Klarna-portalen.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktivér anonymiseringen for at skjule varenavnene på de produkter, der ligger i dine kunders indkøbskurv, for Klarna. Dette anbefales f.eks. til onlineapoteker, men bør kun ske efter aftale med Klarna Integration Manager.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Hvis leveringen skal kunne ske til en anden leveringsadresse, skal du aktivere denne knap.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Hvis De ønsker at gøre det obligatorisk at angive et telefonnummer, skal De aktivere denne knap. Normalt er telefonnummeret ikke et obligatorisk felt hos Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Hvis De ønsker at gøre angivelsen af fødselsdato obligatorisk, skal De aktivere denne knap. Normalt er fødselsdatoen ikke et obligatorisk felt hos Klarna. Oplysningen er dog nødvendig for at muliggøre køb på regning eller betaling i rater.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Ikke implementeret på nuværende tidspunkt',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Indtast her URL’en til din hjemmeside, hvor forbrugerens fortrydelsesret er beskrevet. URL’en skal begynde med https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Disse forsendelsesoplysninger vises for kunden på takkesiden, når bestillingen er afsluttet.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Tildel denne eksterne betalingsmetode en af de foruddefinerede betalingsmetoder',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Angiv venligst en URL for alle sprog',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Indtast venligst en gyldig URL, der begynder med https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Denne knap aktiverer overførslen af yderligere data til Klarna, i dette tilfælde oplysninger om kundekontoen, som indeholder datoen for oprettelsen af kundekontoen og datoen for den seneste ændring.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Denne knap aktiverer overførslen af yderligere data til Klarna, i dette tilfælde »Payment History Full«, som indeholder kundens hidtidige køb.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Vær venlig at angive, hvilken betalingsform denne betalingsmetode henviser til.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Angiv her, om og i givet fald hvilke ordrer der skal medtages med denne betalingsmetode, når kundens ordrehistorik overføres. Afhængigheden for feltet OXORDER.OXPAID angiver, om det kun er betalte ordrer eller alle ordrer, der skal medtages.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Det er muligt at overføre yderligere data af enhver art til Klarna ved hjælp af et pass-through-felt. For at kunne benytte denne funktion skal du installere et passende modul i OXID eShop, som indskriver de ønskede data i pass-through-feltet. Du finder en vejledning hertil i udviklerdokumentationen.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Med denne knap aktiverer du et Klarna-banner på din webshops forside i standardtemaet Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Her kan du indsætte script-tagget til integrering af banneren. I Klarnas bannerportal kan du eventuelt finde flere bannere at vælge imellem.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Med denne knap aktiverer du visningen af Klarna-betalingsmetoden i footeren på din webshop i standardtemaet Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Med denne knap kan du indsætte Klarna-logoet i footeren på din webshop i standardtemaet Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Denne knap tilføjer en »Køb nu«-knap på varedetaljesiderne i din webshop i standardtemaet Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Farven på den ramme, der vises i webshoppens frontend, når man vælger Klarna som betalingsmetode, hvis der er forskellige underindstillinger til rådighed.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Farven på den ramme, der vises i webshoppens frontend, når der er flere tilgængelige underindstillinger, efter at man har valgt betalingsmetoden Klarna. Denne farve bruges til at fremhæve den underindstilling, der aktuelt er valgt.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Denne indstilling har endnu ingen virkning på tidspunktet for offentliggørelsen af dette modul.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Denne indstilling har endnu ingen virkning på tidspunktet for offentliggørelsen af dette modul.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Baggrundsfarven på de radioknapper, der vises i webshoppens frontend, når der er flere underindstillinger til rådighed, efter at man har valgt betalingsmetoden Klarna',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Denne indstilling har endnu ingen virkning på tidspunktet for offentliggørelsen af dette modul.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Farven på punktopstillingstegnene ved visningen af betalingsoplysningerne på siden til valg af betalingsmetode.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Denne indstilling har endnu ingen virkning på tidspunktet for offentliggørelsen af dette modul.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Farven på linkene i den detaljerede beskrivelse af betalingsmetoderne på siden til valg af betalingsmetode.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Tekstfarve i den detaljerede beskrivelse af betalingsmetoderne på siden til valg af betalingsmetode.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternativ tekstfarve til detaljebeskrivelsen af betalingsmetoderne på siden til valg af betalingsmetode.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Med denne indstilling kan du fastlægge, hvor afrundet rammen skal være, når de forskellige tilgængelige underindstillinger vises i webshoppens frontend, efter at betalingsmetoden Klarna er valgt.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Denne fane gælder kun for Klarna-bestillinger',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Registrer hele bestillingen',
    'KLARNA_CAPTURE_ID'                                 => 'Afregnings-ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-reference',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Trækbeløb',
    'KLARNA_CAPTURE_DATE'                               => 'Afskrevet den',
    'KLARNA_REFUND_AMOUNT'                              => 'Refusionsbeløb',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Refusion – forklaring',
    'KLARNA_REFUND_DATE'                                => 'Erstattet den',
    'KLARNA_CAPTURES'                                   => 'Afskrivninger',
    'KLARNA_REFUNDS'                                    => 'Refusioner',
    'KLARNA_CANCEL_ORDER'                               => 'Annuller ordre',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Bestillingen er blevet annulleret. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Åbn denne bestilling på Klarna-portalen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>OBS!</strong> Oplysningerne i denne bestilling adskiller sig fra de oplysninger, der er gemt hos Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'OBS! På grund af den aktuelle ordrestatus kan denne ændring ikke overføres til Klarna. Udfør om nødvendigt ændringen manuelt direkte i Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'OBS! Klarna har ikke kunnet behandle dine seneste ændringer til denne ordre (årsag: %s). Du bedes enten fortryde dine seneste ændringer i OXID eShop eller, hvis det er nødvendigt, foretage den pågældende justering manuelt i Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Ugyldig forespørgsel. Kontroller indstillingerne for Klarna-modulet samt Merchant-ID’et og den tilhørende adgangskode',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Denne ordre kunne ikke findes i Klarnas system. Ændringer af ordreoplysningerne overføres derfor ikke til Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Forkerte loginoplysninger!</strong> Denne bestilling blev afgivet ved hjælp af forhandler-ID’et <strong>%s</strong>. Det forhandler-ID, der i øjeblikket er konfigureret for <strong>%s</strong>, er <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Produktnavn',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymiseret produktnavn:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Betalingen håndteres af vores partner Klarna. Vær opmærksom på de betalingsoplysninger, som Klarna har sendt dig. Du kan administrere alle dine køb via Klarna.com eller Klarna-appen og endda betale med blot et enkelt klik.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Rabatkupon',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Gaveindpakning',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Lykønskningskort',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Alvorlig fejl: Det er obligatorisk at angive en gyldig SSL-beskyttet (https) $this-&gt;sSSLShopURL i din butiks config.inc.php, hvis du ønsker at aktivere %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Forkerte loginoplysninger!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Beløbet er blevet trukket fra kontoen.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Det var ikke muligt at trække beløbet for bestillingen, da den allerede var blevet annulleret.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Indtast her den tekststreng, der skal sendes til Klarna i stedet for den egentlige produkttitel.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Dine ændringer til denne bestilling overføres ikke til Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Brugervejledning',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrer dig',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Læs mere',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Understøttede kundetyper',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Her kan du indstille, om webshoppen udelukkende skal acceptere B2C-transaktioner (standardindstilling), kun B2B-transaktioner eller både B2C- og B2B-transaktioner.<br />  Bemærk: Efter ændring af kundetyperne skal browserens sessionscache ryddes, så betalingen kan testes.',
    'TCKLARNA_B2C'                                      => 'Kun B2C-kunder',
    'TCKLARNA_B2B'                                      => 'Kun B2B-kunder',
    'TCKLARNA_B2B_B2C'                                  => 'Hovedsageligt B2B-kunder, men også B2C-kunder',
    'TCKLARNA_B2C_B2B'                                  => 'Hovedsageligt B2C-kunder, men også B2B-kunder',
    'TCKLARNA_NEED_SUPPORT'                             => 'Har du brug for hjælp til integrationen?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Kontakt Klarnas kundesupport for forhandlere',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Beskeder på stedet',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Her kan du konfigurere On-Site Messaging til brug sammen med Klarna-modulet til OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Manuskript',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion – produktdetaljeside',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Kreditfremme Indkøbskurv',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Kampagne med topbanner',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Kampagne i sidefoden',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Banner-kampagne',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Indsæt venligst her det JavaScript-bibliotekskodestykke, der er nødvendigt for On-Site Messaging, og som du kan finde i Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Indsæt venligst placerings-tagget her for at promovere finansiering og afbetalingskøb via Credit Promotions på varedetaljesiden',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Indsæt venligst placerings-tag\'et her for at promovere finansiering og afbetalingskøb via Credit Promotions på oversigten over indkøbskurven',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Indsæt venligst placerings-tagget her for at fremhæve generelle oplysninger og oplysninger om betalingsmetoder på webshoppens forside',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Indsæt venligst placeringskoden her for at vise de tilgængelige Klarna-betalingsmetoder i butikkens sidefod',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Indsæt venligst placeringskoden her for at indsætte et banner på din butiks forside',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Hvad er on-site messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Kunderne er ikke altid klar over de forskellige kredit- og finansieringsmuligheder, der står til deres rådighed, før de når til kassen. Finansieringsmuligheder, der præsenteres i god tid, påvirker købsbeslutningen. 

On-Site Messaging er nemt og problemfrit at integrere og tilbyder skræddersyede oplysninger, der spænder fra generelle bannere om promovering af dit partnerskab med Klarna og muligheden for afbetaling til personaliserede kreditkampagner på produkt- eller indkøbskurvsider.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Du</a> <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">kan finde</a> yderligere oplysninger om de første trin <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">her</a>:<br /><br /> 
Log ind på <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">forhandlerportalen</a> for at generere din personlige JavaScript- og placeringskode. On-Site-Messaging aktiveres i din butik, så snart JavaScript-koden er gemt, og der er indtastet mindst én placeringskode.<br /> 
Du kan til enhver tid deaktivere det ved at fjerne koderne igen.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Forhandlerportal',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktivér Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktiv',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Udskift knapnøgle',
    'TCKLARNA_IS_REPLACE'                               => 'Opret en ny knap »Key«',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Du kan opdatere Button Key, hvis der er behov for ændringer i konfigurations- eller identifikationsoplysningerne fra Klarnas side. Normalt kan du bruge en Button Key, der er oprettet én gang, så længe du ønsker.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Aktivér Klarna Instant Shopping her. Der oprettes derved automatisk en knap, som kan bruges i webshoppens frontend.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Indstillinger for knapdesign',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vælg venligst mellem en knap, der er fuldstændig designet i Klarna-stilen, og en mere neutral »Light«-variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Vælg venligst, om teksten i sloganet under knappen skal være lys eller mørk.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vælg venligst den ønskede tekst til knappen.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Forhåndsvisning af knappen',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Vis på artikeldetaljesiden',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Aktivér denne funktion, så Klarna Instant Shopping-knappen vises på alle varedetaljesider i din webshop.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Vis i indkøbskurven',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Aktivér denne funktion, så Klarna Instant Shopping-knappen vises på oversigten over indkøbskurven i din webshop.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Yderligere indstillinger for Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Leveringsadressen må afvige fra fakturaadressen',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Hvis leveringen skal kunne ske til en anden leveringsadresse, skal du aktivere denne knap.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Fødselsdato er et obligatorisk felt',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Hvis De ønsker at gøre angivelsen af fødselsdato obligatorisk, skal De aktivere denne knap. Normalt er fødselsdatoen ikke et obligatorisk felt hos Klarna. Oplysningen er dog nødvendig for at muliggøre køb på regning eller betaling i rater.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Nationale ID-nummer som obligatorisk felt',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Vælg venligst, om det nationale identifikationsnummer skal være et obligatorisk felt.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variation',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefonnummeret er et obligatorisk felt',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Vælg venligst, om telefonnummeret skal være et obligatorisk felt.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Vælg venligst fra listen, hvilket land der som standard skal være valgt, når Klarna Instant Shopping åbnes, så længe kunden endnu ikke har angivet sit land.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Indtast her URL’en til dine generelle forretningsbetingelser. Der vil blive indsat et link til disse i Klarna Instant Shopping-pop op-vinduet. Der skal angives en gyldig URL, der begynder med https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Forsendelsesmetoder',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Kreditere hele ordren',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Der blev ikke fundet nogen aktive forsendelsesmetoder',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Anvendt betalingsmetode: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kreditkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Direkte debitering',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Øjeblikkelig overførsel',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 rentefrie afdrag',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finansiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Regning',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Betaling med kort inden for 30 dage',
];
