<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Suomi";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Aloita',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Yleistä',
    'TCKLARNA_CONFIGURATION'                            => 'Määritykset',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Klarna Payments -asetukset',
    'TCKLARNA_KLARNADESIGN'                             => 'Suunnitteluasetukset',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Ulkoiset maksutavat',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Lisätietoja jälleenmyyjistä',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Perusasetukset',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Alennus',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'Tässä tilassa ei ole asetuksia.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Kaikki asetukset on tallennettu.',

    'TCKLARNA_EASY'                                     => 'Klarnan aktivointi on näin helppoa',
    'TCKLARNA_PHONE'                                    => 'Puhelin',
    'TCKLARNA_EMAIL'                                    => 'Sähköposti',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Aukioloajat',
    'TCKLARNA_MONDAY'                                   => 'Maanantai',
    'TCKLARNA_TUESDAY'                                  => 'tiistai',
    'TCKLARNA_WEDNESDAY'                                => 'keskiviikko',
    'TCKLARNA_THURSDAY'                                 => 'torstai',
    'TCKLARNA_FRIDAY'                                   => 'perjantai',
    'TCKLARNA_SATURDAY'                                 => 'lauantai',
    'TCKLARNA_SUNDAY'                                   => 'sunnuntai',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Maakohtaiset kirjautumistunnuksenne',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Lisää maakohtaiset kirjautumistiedot',
    'TCKLARNA_COUNTRY'                                  => 'Maa',
    'TCKLARNA_MERCHANT_ID'                              => 'API-käyttäjätunnus',
    'TCKLARNA_PASSWORD'                                 => 'API-salasana',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Kauppiaan tunnus',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Kaupan oletusmaa',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Kirjautuminen aktiivinen',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Lähetetäänkö laajennetut tuotetiedot Klarnalle?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Tuotteiden URL-osoitteet',
    'TCKLARNA_IMAGE_URLS'                               => 'Kuvien URL-osoitteet',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymisointi',
    'TCKLARNA_ADD'                                      => 'Lisää',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-maksut',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Valitse Klarna-moduulin tila',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Klarnan avulla loppuasiakkaat voivat maksaa kolmella tavalla: Sofortüberweisung-maksuna, myöhemmin tai erissä. Tämä antaa loppuasiakkaille mahdollisuuden kokeilla tuotteita ensin ja maksaa vain siitä, mitä he haluavat pitää, rahoittaa tuotteita verkkokaupassa tai maksaa heti. Lasku, osamaksu, välitön tilisiirto tai suoraveloitus voidaan ottaa käyttöön integroinnin avulla, ja Klarnan iFrame-ratkaisun ansiosta ne ovat aina oikeudellisesti ja sisällöllisesti ajan tasalla.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Suosituimmat maksutavat. Turvallisia ja helppoja integroida.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Tervetuloa Klarna Paymentsin asetuksiin. Täältä löydät kaiken, mitä aktivointiin tarvitaan. Valitse vasemmalla olevasta valikosta Klarna-alavalikot, jotta voit viimeistellä moduulin asennuksen.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Asiakastilin luominen OXID eShopissa',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Uutiskirjeen tilaaminen',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Asiakastilin luominen JA uutiskirjeen tilaaminen',
    'TCKLARNA_NO_CHECKBOX'                              => 'Älä näytä valintaruutua',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Näytetäänkö se kaupan etusivulla?',
    'TCKLARNA_BANNER_SRC'                               => 'Klarna-bannerin lähde',
    'TCKLARNA_FOOTER'                                   => 'Alatunniste',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Mitä alaviitteessä tulisi näkyä?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Maksutapojen näyttö',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna-logo',
    'TCKLARNA_DESIGN'                                   => 'Suunnittelu',
    'TCKLARNA_LONG_VERSION'                             => 'Pitkä versio:',
    'TCKLARNA_SHORT_VERSION'                            => 'Lyhyt versio:',
    'TCKLARNA_WHITE'                                    => 'Valkoinen:',
    'TCKLARNA_BLACK'                                    => 'Musta:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Tuotetietosivu ja ostoskori',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Näytetäänkö Klarna-maksutavan widget?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Tuotteen tietosivulla',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Ostoskorisivulla',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Näytetäänkö ”Osta nyt” -painike?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Klarnan maksusuunnitteluvaihtoehdot',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Väriasetukset:',
    'TCKLARNA_BORDER'                                   => 'Raja:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Valittu raja:',
    'TCKLARNA_BUTTON'                                   => 'Painike:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Painikkeen teksti:',
    'TCKLARNA_CHECKBOX'                                 => 'Valintaruutu:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Valintaruutu:',
    'TCKLARNA_DETAILS'                                  => 'Tiedot:',
    'TCKLARNA_HEADER'                                   => 'Otsikko:',
    'TCKLARNA_LINK'                                     => 'Linkki:',
    'TCKLARNA_TEXT'                                     => 'Teksti:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Lisätietoja:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Säteen säätö:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Reunan säde:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Toimitusosoite voi poiketa laskutusosoitteesta',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Puhelinnumero on pakollinen kenttä',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Syntymäaika on pakollinen kenttä',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Ota käyttöön toimitus DHL Packstationiin',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Ota esitäyttö käyttöön',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Ota esitäyttö-ilmoitus käyttöön',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Kutsumanimi on pakollinen kenttä',
    'TCKLARNA_SET_TAC_URI'                              => 'Käyttöehtojenne URL-osoite',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Peruuttamisoikeutta koskeva URL-osoite',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Toimitustiedot',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Ei validointia',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Suorita validointi, mutta ohita aikakatkaisut',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Onnistunut validointi vaaditaan',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Tilauksen vahvistus',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Valitse ne Klarna-maksuvaihtoehdot, joita haluat tarjota asiakkaillesi:',
    'TCKLARNA_PAY_LATER'                                => 'Lasku',
    'TCKLARNA_PAY_LATER.'                               => 'Lasku.',
    'TCKLARNA_PAY_LATER_START'                          => 'Asiakkaille, jotka haluavat ostaa nyt ja maksaa myöhemmin. Erittäin kätevästi 14, 21 tai 28 päivän kuluttua, markkinasta riippuen.',
    'TCKLARNA_PAY_LATER_TEXT'                           => '”Lasku”-vaihtoehto tekee maksamisesta asiakkaille helppoa ja nopeaa ilman, että heidän tarvitsee syöttää henkilötietoja tai monimutkaisia numeroita. Asiakas voi valita joko laskun tai maksun kuukaudessa X.',
    'TCKLARNA_SLICE_IT'                                 => 'Osamaksukauppa.',
    'TCKLARNA_SLICE_IT.'                                => 'Maksaminen erissä.',
    'TCKLARNA_SLICE_IT_START'                           => 'Lisää asiakkaidesi ostovoimaa tarjoamalla maksuaikaa. Asiakkaat voivat maksaa ostoksensa kiinteinä kuukausierinä 6–36 kuukauden aikana.',
    'TCKLARNA_SLICE_IT_TEXT'                            => '”Osamaksukaupan” avulla asiakkaat voivat jakaa ostosumman pienillä koroilla useisiin eriin. Tämä kasvattaa investointivaraa ja ostovoimaa. Klarnan ainutlaatuinen luottokäsittely vie vain hetken ja vaatii vain vähän tietojen syöttämistä.',
    'TCKLARNA_PAY_NOW'                                  => 'Maksa heti',
    'TCKLARNA_PAY_NOW.'                                 => 'Maksa heti.',
    'TCKLARNA_PAY_NOW_START'                            => 'Helppo ja nopea suoramaksu Klarnan Sofort bezahlen -palvelun avulla. Saksassa tarjontavalikoimasta eivät saa puuttua Sofortüberweisung, luottokortti ja suoraveloitus.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Asiakkaat, jotka haluavat maksaa summan kokonaan heti tilauksen yhteydessä, voivat käyttää ”Maksa heti” -vaihtoehtoa. Valittavina maksutapoina ovat luottokortti, suoraveloitus ja Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Klarnan<br /> aktivointiohje.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Napsauta OXID-hallintapaneelissa uutta Klarna-valikkokohtaa, sen alaluokkaa Yleistä ja valitse sitten haluamasi Klarna-tuote.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Syötä kirjautumistietosi (käyttäjätunnus ja salasana) ja määritä OXID-järjestelmälle tyypilliset maksutapojen kohdistukset kohdissa Shopeinstellungen &gt; Zahlungsarten sekä &gt; Versandarten.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Tallenna muutokset.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Olet nyt verkossa ja voit aloittaa myynnin Klarnan kautta.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Kauppiaiden tuki',
    'TCKLARNA_DEVICE_IMG'                               => 'laite.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Täällä voit määrittää, siirretäänkö Klarnalle tarvittaessa ylimääräisiä kauppiaan tietoja. 
Saat yksityiskohtaisen kuvauksen eri asetuksista tutustumalla työkaluvinkkeihin 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lukemalla <a class="cl-pink" href="%s" target="_blank">käyttöoppaan</a> 
tai ottamalla yhteyttä Klarnan integraatiotukeen.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Täällä voit määrittää OXID eShopin Klarna-moduulin käyttöä koskevat ulkoasuasetukset. 
Saat yksityiskohtaisen kuvauksen eri asetuksista tutustumalla työkaluvinkkeihin 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lukemalla <a class="cl-pink" href="%s" target="_blank">käyttöopp</a>aan 
tai ottamalla yhteyttä Klarnan integraatiotukeen.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Täältä voit tehdä Klarna Payments -valinnat ja määrittää yleiset asetukset. 
Saat yksityiskohtaisen kuvauksen eri asetuksista tutustumalla työkaluvinkkeihin 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lukemalla <a class="cl-pink" href="%s" target="_blank">käyttöoppaan</a> 
tai ottamalla yhteyttä Klarnan integraatiotukeen.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Tällä sivulla voit valita, mitä Klarna-maksutapoja haluat tarjota. 
Saat yksityiskohtaisen kuvauksen eri asetuksista tutustumalla työkaluvinkkeihin 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lukemalla <a class="cl-pink" href="%s" target="_blank">käyttöoppaan</a> 
tai ottamalla yhteyttä Klarnan integraatiotukeen.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Maksutapa',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Ulkoinen maksutapa',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Ulkoisen maksutavan kuvan URI',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Kuvan koko: 69x24 pikseliä',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Kuvan koko: 276x48 pikseliä',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Voit lukea OXID eShopin Klarna-moduulin käyttöoppaan täältä.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Käyttöopas',

    'TCKLARNA_CHOOSE'                                   => 'Valitse',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Asiakastilin tiedot',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Täydellinen maksuhistoria',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Läpikulkukenttä',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Määritä maksutavan tyyppi:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Mitkä tilaukset tulisi ottaa huomioon Payment history full -kohdassa?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Kaikki tilaukset katsotaan maksetuiksi riippumatta Oxpaid-päivämäärästä',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Lähetä vain tilaukset, joille on määritetty oxpaid-päivämäärä; jätä maksamattomat tilaukset huomiotta',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ohita kaikki tilaukset, jotka on tehty tällä maksutavalla',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Muu maksutapa',
    'TCKLARNA_DIRECT_BANKING'                           => 'Välitön tilisiirto',
    'TCKLARNA_CARD'                                     => 'Kartta',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Valitse joko Playground (testikäyttö) tai Live (tuotantokäyttö). Ota tuotantokäyttö käyttöön vasta, kun integraatiotestit on suoritettu onnistuneesti ja kun olet neuvotellut asiasta Klarnan integraatiovastaavan kanssa.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Syötä tähän Klarna API -käyttäjätunnuksesi. Olet saanut ne Klarnan tervetuloviestissä. Tämä käyttäjätunnus ja salasana ovat voimassa kaikissa maissa. Vain jos olet saanut eri käyttäjätunnukset eri maille, voit lisätä ne alla olevaan kenttään.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Syötä tähän salasana, joka vastaa käyttämääsi API-käyttäjätunnusta. Olet saanut tämän salasanan Klarnan tervetuloviestissä.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Syötä tähän Klarna-kauppias-tunnuksesi. Olet saanut sen Klarnan tervetuloviestissä.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Valitse vasemmalla olevasta valikosta se maa, jolle olet saanut Klarnalta maakohtaiset kirjautumistiedot.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Syötä tähän kyseisen maan käyttäjätunnus.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Syötä tähän kyseisen maan salasana.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Syötä tähän kyseisen maan kauppias-ID.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Ottaa lokitoiminnon käyttöön, jolloin kaikki Klarnan kanssa tapahtuva API-viestintä tallennetaan mysql-taulukkoon tcklarna_logs. Tästä voi olla hyötyä analysoinnissa tai vianetsinnässä. Tuotantokäytössä toiminto tulisi poistaa käytöstä, sillä muuten lokitiedostoihin voi kertyä suuria määriä tietoa ja niihin voi tallentua arkaluonteisia tietoja.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Lähetä Klarnalle niiden tuotteiden tuotetietosivujen URL-osoitteet, jotka ovat asiakkaidesi ostoskorissa, jotta Klarna voi myöhemmin linkittää tuotteisiisi Klarna-portaalista.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Lähetä asiakkaiden ostoskoriin lisättyjen tuotteiden tuotekuvien URL-osoitteet Klarnalle, jotta Klarna voi näyttää ne Klarna-portaalissa.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Ota anonymisointi käyttöön, jotta asiakkaiden ostoskoriin lisättyjen tuotteiden nimet piilotetaan Klarnalta. Tätä suositellaan esimerkiksi verkkokauppojen apteekeille, mutta se tulisi tehdä vasta neuvoteltuasi asiasta Klarnan integraatiovastaavan kanssa.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Jos toimitus halutaan mahdollistaa eri toimitusosoitteeseen, aktivoi tämä valintakytkin.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Jos haluatte, että puhelinnumeron antaminen on pakollista, aktivoikaa tämä valintakytkin. Normaalisti puhelinnumero ei ole pakollinen kenttä Klarnassa.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Jos haluatte, että syntymäpäivän ilmoittaminen on pakollista, aktivoikaa tämä valintakytkin. Normaalisti syntymäpäivä ei ole pakollinen kenttä Klarnassa. Sen ilmoittaminen on kuitenkin välttämätöntä, jotta ostos voidaan maksaa laskulla tai osamaksulla.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Ei tällä hetkellä käytössä',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Kirjoita tähän verkkosivustosi URL-osoite, jossa on selostus peruuttamisoikeudesta. URL-osoitteen on alettava https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Nämä toimitustiedot näytetään asiakkaalle kiitossivulla tilauksen tekemisen jälkeen.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Määritä tämä ulkoinen maksutapa johonkin ennalta määritetyistä maksutavoista',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Ilmoittakaa URL-osoite kaikille kielille',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Anna kelvollinen URL-osoite, joka alkaa https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Tämä kytkin aktivoi lisätietojen siirron Klarnalle; tässä tapauksessa kyseessä ovat asiakastilin tiedot, jotka sisältävät asiakastilin rekisteröintipäivämäärän ja sen viimeisimmän muutospäivämäärän.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Tämä valintakytkin aktivoi lisätietojen siirron Klarnalle; tässä tapauksessa kyseessä on ”Payment History Full”, joka sisältää asiakkaan aiemmat ostokset.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Määritä, minkä tyyppinen maksutapa tämä on.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Määritä tässä, sisällytetäänkö asiakkaan tilaushistoriaan tällä maksutavalla tehtyjä tilauksia ja, jos sisällytetään, mitkä tilaukset. Kentän OXORDER.OXPAID riippuvuus määrittää, otetaanko huomioon vain maksetut tilaukset vai kaikki tilaukset.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Pass-through-kentän avulla on mahdollista välittää Klarnalle mitä tahansa muita tietoja. Jotta voit käyttää tätä toimintoa, sinun on asennettava OXID eShopiin sopiva moduuli, joka tallentaa halutut tiedot pass-through-kenttään. Ohjeet tähän löytyvät kehittäjädokumentaatiosta.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Tällä kytkimellä voit ottaa Klarna-bannerin käyttöön verkkokauppasi etusivulla Apex-vakioaiheessa.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Tänne voit lisätä bannerin upottamiseen tarvittavan script-tagin. Klarnan banneriportaalista löydät tarvittaessa lisää bannereita, joista voit valita.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Tällä kytkimellä voit ottaa Klarna-maksutavan näytön käyttöön verkkokauppasi alatunnisteessa Apex-oletusteemassa.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Tällä painikkeella voit lisätä Klarna-logon verkkokauppasi alatunnisteeseen Apex-vakioaiheessa.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Tämä kytkin lisää ”Osta nyt” -painikkeen verkkokauppasi tuotetietosivuille Apex-oletusteemassa.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Kehyksen väri, joka näkyy verkkokaupan käyttöliittymässä, kun Klarna-maksutapa on valittu ja saatavilla on erilaisia alavaihtoehtoja.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Kehyksen väri, joka näkyy verkkokaupan käyttöliittymässä, kun Klarna-maksutapa on valittu ja saatavilla on useita alavaihtoehtoja. Tätä väriarvoa käytetään korostamaan kulloinkin aktiivisesti valittua alavaihtoehtoa.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Tällä asetuksella ei ole vielä vaikutusta tämän moduulin julkaisuhetkellä.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Tällä asetuksella ei ole vielä vaikutusta tämän moduulin julkaisuhetkellä.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Niiden valintapainikkeiden taustaväri, jotka näkyvät verkkokaupan käyttöliittymässä, kun Klarna-maksutapa on valittu ja saatavilla on erilaisia alavaihtoehtoja',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Tällä asetuksella ei ole vielä vaikutusta tämän moduulin julkaisuhetkellä.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Luettelomerkkien väri, kun maksutiedot näytetään maksutapavalintasivulla.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Tällä asetuksella ei ole vielä vaikutusta tämän moduulin julkaisuhetkellä.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Maksutapojen valintasivulla olevien maksutapojen yksityiskohtaisten kuvauksien sisällä olevien linkkien väri.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Maksutapojen valintasivulla olevien maksutapojen yksityiskohtaisten kuvauksien tekstin väri.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Maksutapojen valintasivulla olevien maksutapojen yksityiskohtaisten kuvauksien vaihtoehtoinen tekstiväri.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Tämän asetuksen avulla voit määrittää kehyksen pyöristysasteen, joka näkyy verkkokaupan käyttöliittymässä, kun Klarna-maksutapa on valittu ja eri alavaihtoehtoja on saatavilla.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Tämä välilehti koskee vain Klarna-tilauksia',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Tallenna koko tilaus',
    'KLARNA_CAPTURE_ID'                                 => 'Veloitustunnus',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-viite',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Veloitussumma',
    'KLARNA_CAPTURE_DATE'                               => 'Veloitettu',
    'KLARNA_REFUND_AMOUNT'                              => 'Hyvityssumma',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Korvaus – Selitys',
    'KLARNA_REFUND_DATE'                                => 'Korvattu am',
    'KLARNA_CAPTURES'                                   => 'Veloitukset',
    'KLARNA_REFUNDS'                                    => 'Hyvitykset',
    'KLARNA_CANCEL_ORDER'                               => 'Peruuta tilaus',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Tilaus on peruutettu. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Avaa tämä tilaus Klarna-portaalissa</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Huomio!</strong> Tämän tilauksen tiedot poikkeavat Klarnassa tallennetuista tiedoista. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Huomio! Nykyisen tilausstatuksen vuoksi tätä muutosta ei voida välittää Klarnalle. Tee tarvittava muutos tarvittaessa manuaalisesti suoraan Klarnan kauppiasportaalissa.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Huomio! Klarna ei pystynyt käsittelemään viimeisimpiä muutoksia tähän tilaukseen (syy: %s). Peruuta viimeisimmät muutokset OXID eShopissa tai tee tarvittavat muutokset manuaalisesti Klarna Merchant Portalissa, jos se on tarpeen.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Luvaton pyyntö. Tarkista Klarna-moduulin asetukset sekä kauppiaan tunnus (Merchant ID) ja siihen liittyvä salasana.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Tätä tilausta ei löytynyt Klarnan järjestelmästä. Siksi tilaustietojen muutoksia ei siirretä Klarnalle.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Virheelliset kirjautumistiedot!</strong> Tämä tilaus on tehty käyttämällä jälleenmyyjän tunnusta <strong>%s</strong>. <strong>%s</strong>-sivustolle tällä hetkellä määritetty jälleenmyyjän tunnus on <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Tuotteen nimi',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymisoitu tuotteen nimi:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Maksu hoidetaan yhteistyökumppanimme Klarnan kautta. Huomioi Klarnan lähettämät maksutiedot. Voit hallinnoida kaikkia ostoksiasi Klarna.com-sivustolla tai Klarna-sovelluksessa ja jopa maksaa ne yhdellä napsautuksella.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Alennuskuponki',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Lahjapakkaus',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Onnittelukortti',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Kriittinen virhe: Sinun on ehdottomasti määritettävä kelvollinen SSL-suojattu (https) $this-&gt;sSSLShopURL-arvo kaupan config.inc.php-tiedostossa, jos haluat ottaa käyttöön %s-toiminnon!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Virheelliset kirjautumistiedot!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Summa on veloitettu onnistuneesti.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Tilausta ei voitu veloittaa, koska se oli jo peruutettu.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Kirjoita tähän merkkijono, joka lähetetään Klarnalle varsinaisen tuotteen nimen sijaan.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Tähän tilaukseen tekemiäsi muutoksia ei siirretä Klarnalle.',
    'TCKLARNA_USER_GUIDE'                               => 'Käyttöopas',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Rekisteröidy',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Lue lisää',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tuetut asiakastyypit',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Täällä voit määrittää, hyväksyykö verkkokauppa yksinomaan B2C-tapahtumia (oletusasetus), vain B2B-tapahtumia vai sekä B2C- että B2B-tapahtumia.<br />  Huomautus: Asiakastyypin muuttamisen jälkeen selaimen istuntovälimuisti on tyhjennettävä, jotta maksua voidaan testata.',
    'TCKLARNA_B2C'                                      => 'Vain B2C-asiakkaat',
    'TCKLARNA_B2B'                                      => 'Vain B2B-asiakkaat',
    'TCKLARNA_B2B_B2C'                                  => 'Pääasiassa B2B-asiakkaita, mutta myös B2C-asiakkaita',
    'TCKLARNA_B2C_B2B'                                  => 'Pääasiassa B2C-asiakkaita, mutta myös B2B-asiakkaita',
    'TCKLARNA_NEED_SUPPORT'                             => 'Tarvitsetteko apua integroinnissa?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Ota yhteyttä Klarnan kauppiaspalveluun',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Paikan päällä tapahtuva viestintä',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Täällä voit määrittää On-Site Messaging -toiminnon käytettäväksi OXID eShopin Klarna-moduulin kanssa.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Käsikirjoitus',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion -tuotteen tietosivu',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Luottokampanja Ostoskori',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Top-strip-kampanja',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Alatunnisteen mainos',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Bannerimainonta',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Lisää tähän On-Site Messaging -toiminnon edellyttämä JavaScript-kirjaston koodinpätkä, jonka saat Klarna Merchant Portalista.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Lisää tähän sijoitustagi, jotta voit mainostaa Credit Promotionsin tarjoamaa rahoitusta ja osamaksua tuotteen yksityiskohtaisella sivulla',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Lisää tähän sijoitustagi, jotta voit mainostaa Credit Promotionsin tarjoamaa rahoitusta ja osamaksua ostoskorin yhteenvedossa',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Lisää tähän sijoitustagi, jotta voit mainostaa yleisiä ja maksutapakohtaisia tietoja verkkokaupan etusivulla',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Lisää tähän sijoitustagi, jotta käytettävissä olevat Klarna-maksutavat näkyvät verkkokaupan alatunnisteessa',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Lisää tähän sijoitustagi, jotta voit lisätä bannerin verkkokauppasi etusivulle',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Mitä on On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Asiakkaat eivät aina ole tietoisia heille tarjolla olevista erilaisista luotto- ja rahoitusvaihtoehdoista ennen kuin he pääsevät kassalle. Varhaisessa vaiheessa tarjolla olevat rahoitusvaihtoehdot vaikuttavat ostopäätökseen. 

On-Site Messaging on helppo ja vaivaton integroida, ja se tarjoaa räätälöityä tietoa, joka ulottuu yleisistä bannereista Klarna-kumppanuuden mainostamiseen ja osamaksumahdollisuuksien esittelyyn aina tuote- tai ostoskorisivuilla näkyviin henkilökohtaisiin luottokampanjoihin asti.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Lisätietoja ensimmäisistä vaiheista <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">löytyy täältä:</a><br /><br /> 
Kirjaudu kau<a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">ppias</a>portaaliin luodaksesi henkilökohtaisen JavaScript- ja sijoituskoodisi. On-Site-Messaging otetaan käyttöön verkkokaupassasi heti, kun JavaScript-koodi on tallennettu ja vähintään yksi sijoituskoodi on syötetty.<br /> 
Voit poistaa sen käytöstä milloin tahansa poistamalla koodit.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Jälleenmyyjäportaali',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Klarna Instant Shoppingin käyttöönotto',
    'TCKLARNA_IS_ENABLED'                               => 'Aktiivinen',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Painikkeen näppäimen uusiminen',
    'TCKLARNA_IS_REPLACE'                               => 'Luo uusi painike Key',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Voit päivittää Button Key -avaimen, jos Klarnan puolella tapahtuneet muutokset edellyttävät konfigurointi- tai tunnistetietojen päivittämistä. Yleensä kerran luotua Button Key -avainta voi käyttää niin kauan kuin haluat.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Ota Klarna Instant Shopping käyttöön tästä. Tämä luo automaattisesti painikkeen, jota voi käyttää verkkokaupan käyttöliittymässä.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Painikkeiden tyylin asetukset',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Valitse joko täysin Klarna-tyylillä brändätty painike tai neutraalimpi Light-versio.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Valitse, onko painikkeen alla olevan iskulauseen tekstin väri vaalea vai tumma.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Valitse haluamasi painikkeen teksti.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Painikkeen esikatselu',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Näytä tuotetietosivulla',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Ota tämä toiminto käyttöön, jotta Klarna Instant Shopping -painike näkyy verkkokauppasi kaikilla tuotetietosivuilla.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Näytä ostoskorin yhteenveto',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Ota tämä toiminto käyttöön, jotta Klarna Instant Shopping -painike näkyy verkkokauppasi ostoskorin yhteenvedossa.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Muita Instant Shopping -asetuksia',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Toimitusosoite voi poiketa laskutusosoitteesta',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Jos toimitus halutaan mahdollistaa eri toimitusosoitteeseen, aktivoi tämä valintakytkin.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Syntymäaika on pakollinen kenttä',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Jos haluatte, että syntymäpäivän ilmoittaminen on pakollista, aktivoikaa tämä valintakytkin. Normaalisti syntymäpäivä ei ole pakollinen kenttä Klarnassa. Sen ilmoittaminen on kuitenkin välttämätöntä, jotta ostos voidaan maksaa laskulla tai osamaksulla.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Kansallinen henkilötunnus on pakollinen kenttä',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Valitse, onko kansallinen henkilötunnus pakollinen kenttä.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Vaihtelu',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tyyppi',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Puhelinnumero on pakollinen kenttä',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Valitse, onko puhelinnumero pakollinen kenttä.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Valitse luettelosta, mikä maa asetetaan oletukseksi Klarna Instant Shopping -palvelun avaamisen yhteydessä, kunnes asiakas on ilmoittanut maansa.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Syötä tähän yleisten käyttöehtojesi URL-osoite. Niihin linkitetään Klarna Instant Shopping -ponnahdusikkunassa. On annettava kelvollinen URL-osoite, joka alkaa https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Toimitustavat',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Hyvitä koko tilaus',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Aktiivisia toimitustapoja ei löytynyt',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Käytetty maksutapa: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Luottokortti',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'suoraveloitus',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Välitön tilisiirto',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 korotonta erää',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Rahoitus',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-lasku (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Lasku',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Korttimaksu 30 päivän kuluessa',
];
