<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'General',
    'TCKLARNA_CONFIGURATION'                            => 'Configuration',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configuration for Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Design settings',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'External payment methods',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Additional retailer details',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Basic settings',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Discount',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'There are no settings in this mode.',
    'TCKLARNA_CHANGES_SAVED'                            => 'All settings have been saved.',

    'TCKLARNA_EASY'                                     => 'It’s that easy to activate Klarna',
    'TCKLARNA_PHONE'                                    => 'Telephone',
    'TCKLARNA_EMAIL'                                    => 'Email',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Opening hours',
    'TCKLARNA_MONDAY'                                   => 'Monday',
    'TCKLARNA_TUESDAY'                                  => 'Tuesday',
    'TCKLARNA_WEDNESDAY'                                => 'Wednesday',
    'TCKLARNA_THURSDAY'                                 => 'Thursday',
    'TCKLARNA_FRIDAY'                                   => 'Friday',
    'TCKLARNA_SATURDAY'                                 => 'Saturday',
    'TCKLARNA_SUNDAY'                                   => 'Sunday',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Your country-specific login details',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Add country-specific login details',
    'TCKLARNA_COUNTRY'                                  => 'Country',
    'TCKLARNA_MERCHANT_ID'                              => 'API username',
    'TCKLARNA_PASSWORD'                                 => 'API password',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Merchant ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Default country of the shop',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Logging active',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Send extended product data to Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Product URLs',
    'TCKLARNA_IMAGE_URLS'                               => 'Image URLs',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymise',
    'TCKLARNA_ADD'                                      => 'Add',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna Payments',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Select Klarna module mode',

    'TCKLARNA_PAYMENTS_DESC'                            => 'With Klarna, end customers can pay in three ways: instant bank transfer, later, or in instalments. This allows end customers to try out goods first and pay only for what they wish to keep, finance products in the shop, or pay immediately. You can activate invoice payments, instalment purchases, instant bank transfer or direct debit via a single integration, and thanks to Klarna’s iFrame solution, these options are always up to date in terms of both legal requirements and content.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'The most popular payment methods. Secure and easy to integrate.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'A warm welcome to the Klarna Payments configuration settings. Here you will find everything you need to activate the service. Select the Klarna sub-menus in the left-hand sidebar to complete the module setup.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Create a customer account in the OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Newsletter subscription',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Create a customer account AND subscribe to the newsletter',
    'TCKLARNA_NO_CHECKBOX'                              => 'Do not display the tick box',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Show on the shop homepage?',
    'TCKLARNA_BANNER_SRC'                               => 'Klarna banner source',
    'TCKLARNA_FOOTER'                                   => 'Footer',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'What should be displayed in the footer?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Display of payment methods',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna Logo',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Long version:',
    'TCKLARNA_SHORT_VERSION'                            => 'Short version:',
    'TCKLARNA_WHITE'                                    => 'White:',
    'TCKLARNA_BLACK'                                    => 'Black:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Product details page and shopping basket',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Show the Klarna payment method widget?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'On the product details page',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'On the shopping basket page',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Show the "Buy now" button?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Klarna Payment Design Options',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Colour settings:',
    'TCKLARNA_BORDER'                                   => 'Border:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Border selected:',
    'TCKLARNA_BUTTON'                                   => 'Button:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Button Text:',
    'TCKLARNA_CHECKBOX'                                 => 'Tick box:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Tick the box:',
    'TCKLARNA_DETAILS'                                  => 'Details:',
    'TCKLARNA_HEADER'                                   => 'Header:',
    'TCKLARNA_LINK'                                     => 'Link:',
    'TCKLARNA_TEXT'                                     => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Further text:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Radius setting:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Border Radius:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'The delivery address may differ from the billing address',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'The telephone number is a required field',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Date of birth is a mandatory field',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Enable delivery to a DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Enable pre-filling',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Enable pre-filling prompt',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'The title field is compulsory',
    'TCKLARNA_SET_TAC_URI'                              => 'URL to your terms and conditions',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL regarding the right of withdrawal',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Delivery details',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'No validation',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Perform validation, but ignore timeouts',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Successful validation required',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Order validation',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Please select the Klarna payment options you would like to offer your customers:',
    'TCKLARNA_PAY_LATER'                                => 'Invoice',
    'TCKLARNA_PAY_LATER.'                               => 'Invoice.',
    'TCKLARNA_PAY_LATER_START'                          => 'For customers who want to buy now and pay later. Conveniently in 14, 21 or 28 days, depending on the market.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'The “Invoice” option makes the payment process quick and easy for customers, without them having to enter personal details or complicated numbers. Customers can choose between an invoice or paying in month X.',
    'TCKLARNA_SLICE_IT'                                 => 'Hire purchase.',
    'TCKLARNA_SLICE_IT.'                                => 'Pay in instalments.',
    'TCKLARNA_SLICE_IT_START'                           => 'Boost your customers’ purchasing power by offering payment in instalments. Customers can pay for their purchases in fixed monthly instalments over a period of 6 to 36 months.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'With “pay-as-you-go”, customers can split the total cost of their purchase into instalments at a low interest rate. This increases their spending power and the amount they can afford to spend. Klarna’s unique credit assessment process takes just a few moments and requires minimal data entry.',
    'TCKLARNA_PAY_NOW'                                  => 'Pay now',
    'TCKLARNA_PAY_NOW.'                                 => 'Pay now.',
    'TCKLARNA_PAY_NOW_START'                            => 'Quick and easy direct payment with Klarna’s ‘Pay Now’ option. In Germany, Sofortüberweisung, credit card and direct debit are essential payment methods to include in your portfolio.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Customers who wish to pay the full amount immediately when completing their order can use the "Pay now" option. They can choose between credit card, direct debit and Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'How-to-activateKlarna<br /> guide.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'In the OXID backend, click on the new ‘Klarna’ menu item, then the ‘General’ subcategory, and finally select the desired Klarna product.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Enter your login details (username and password), and configure the standard OXID mappings for payment methods under Shop Settings &gt; Payment Methods and &gt; Delivery Methods.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Save the changes.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'You are now online and can start selling with Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Merchant Support',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Here you can configure whether any additional merchant data should be transferred to Klarna. 
For a detailed description of the various settings, please refer to the tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, read the <a class="cl-pink" href="%s" target="_blank">manual</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Here you can configure the design settings for use with the Klarna module for the OXID eShop. 
For a detailed description of the various settings, please refer to the tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, read the <a class="cl-pink" href="%s" target="_blank">manual</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Configure your Klarna Payments settings here and set up general settings. 
For a detailed description of the various settings, please refer to the tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, read the <a class="cl-pink" href="%s" target="_blank">manual</a> 
or contact Klarna Integration Support.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'On this page, you can select which Klarna payment methods you wish to offer. 
For a detailed description of the various settings, please refer to the tooltips 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, read the <a class="cl-pink" href="%s" target="_blank">manual</a> 
or contact Klarna Integration Support.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Payment method',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'External payment method',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Bild URI für External Payment Method',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Image size: 69x24 pixels',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Image size: 276x48 pixels',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'You can view the user manual for the Klarna module for the OXID eShop here.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'User Manual',

    'TCKLARNA_CHOOSE'                                   => 'Vote',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Customer account information',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Full payment history',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Pass-through field',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Assign payment method type:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Which orders should be included in the ‘Payment history full’?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'All orders are to be regarded as paid, regardless of the Oxpaid date',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Only submit orders with a set Oxpaid date; ignore unpaid orders',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignore all orders placed using this payment method',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Other payment options',
    'TCKLARNA_DIRECT_BANKING'                           => 'Instant Bank Transfer',
    'TCKLARNA_CARD'                                     => 'Map',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Choose between Playground (test environment) and Live (production environment). Only switch to the production environment once integration tests have been successfully completed and after consulting your Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Please enter your Klarna API login details here. You received these in the welcome email from Klarna. This username and password are valid globally for all countries. Only if you have received different login details for different countries can you add them below.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Enter your password here, matching the API username you are using. You received this password in the welcome email from Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Please enter your Klarna Merchant ID here. You will have received this in the welcome email from Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'From the list on the left, select the country for which you have received country-specific login details from Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Please enter the relevant username for this country here.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Please enter the relevant password for this country here.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Please enter the relevant Merchant ID for this country here.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Enables the logging function so that all API communication with Klarna is recorded in the MySQL table `tcklarna_logs`. This can be useful for analysis or troubleshooting. In production, this function should be disabled, as otherwise large amounts of log data may accumulate and sensitive data may be stored.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Please send Klarna the URLs of the product detail pages for the items in your customers’ shopping baskets so that Klarna can later link to your products from the Klarna Portal.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Please send Klarna the URLs of the product images for the items in your customers’ shopping baskets so that Klarna can display them on the Klarna portal.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Enable anonymisation to hide the product names of items in your customers’ shopping baskets from Klarna. This is recommended, for example, for online pharmacies, but should only be done after consulting the Klarna Integration Manager.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'If you wish to allow delivery to a different delivery address, please tick this box.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'If you wish to make it compulsory to provide a telephone number, please tick this box. Normally, the telephone number is not a compulsory field for Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'If you wish to make it compulsory to provide a date of birth, please tick this box. Normally, Klarna does not require a date of birth. However, this information is necessary to enable purchase on account or payment in instalments.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Not currently implemented',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Please enter the URL of your website containing the information on the right of withdrawal here. The URL must begin with https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'These delivery details are displayed to the customer on the thank-you page once the order has been completed.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Assign this external payment method to one of the predefined payment methods',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Please provide a URL for all languages',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Please enter a valid URL beginning with https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'This switch enables the transmission of additional data to Klarna; in this case, the customer account information, which includes the date on which the customer account was registered and the date of its last update.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'This switch enables the transmission of additional data to Klarna; in this case, the ‘Payment History Full’, which contains the customer’s previous purchases.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Please indicate what type of payment method this is.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Please specify here whether, and if so which, orders made using this payment method should be included when transferring the customer’s order history. The dependency of the OXORDER.OXPAID field determines whether only paid orders or all orders should be included.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'It is possible to send any additional data to Klarna using a pass-through field. To use this function, you must install a suitable module in the OXID eShop that writes the required data to the pass-through field. You can find instructions on how to do this in the developer documentation.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Use this toggle to enable a Klarna banner on your shop’s homepage in the Apex default theme.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'You can enter the script tag for embedding the banner here. You may find further banners to choose from in Klarna’s banner portal.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'This toggle enables the Klarna payment method display in the footer of your shop in the Apex default theme.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Use this toggle to add the Klarna logo to the footer of your shop in the Apex default theme.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'This switch adds a \'Buy Now\' button to the product detail pages of your shop in the Apex default theme.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'The colour of the frame that appears in the shop frontend after selecting the Klarna payment method, where various sub-options are available.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'The colour of the frame that appears in the shop frontend after selecting the Klarna payment method, where various sub-options are available. This colour is used to highlight the currently selected sub-option.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'This setting has no effect at the time of publication of this module.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'This setting has no effect at the time of publication of this module.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'The background colour of the radio buttons that appear in the shop frontend when the Klarna payment method is selected, where various sub-options are available',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'This setting has no effect at the time of publication of this module.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Colour of the bullet points when displaying payment details on the payment method selection page.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'This setting has no effect at the time of publication of this module.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Colour of the links within the detailed description of the payment methods on the payment method selection page.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Text colour for the detailed description of payment methods on the payment method selection page.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternative text colour for the detailed description of payment methods on the payment method selection page.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'This setting allows you to specify the degree of rounding for the frame that appears in the shop frontend once the Klarna payment method has been selected, depending on the various sub-options available.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'This tab applies only to Klarna orders',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Capture the entire order',
    'KLARNA_CAPTURE_ID'                                 => 'Debit ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna Reference',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Amount to be debited',
    'KLARNA_CAPTURE_DATE'                               => 'Debited on',
    'KLARNA_REFUND_AMOUNT'                              => 'Refund amount',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Refund – Explanation',
    'KLARNA_REFUND_DATE'                                => 'Replaced by am',
    'KLARNA_CAPTURES'                                   => 'Debits',
    'KLARNA_REFUNDS'                                    => 'Refunds',
    'KLARNA_CANCEL_ORDER'                               => 'Cancel order',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'The order has been cancelled. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">View this order on the Klarna portal</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Please note!</strong> The details of this order differ from those stored with Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Please note! Due to the current order status, this adjustment cannot be submitted to Klarna. If necessary, please make the relevant adjustment manually in the Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Please note! Klarna was unable to process your latest changes to this order (reason: %s). Please undo your recent changes in the OXID eShop or make the necessary adjustments manually in the Klarna Merchant Portal if required.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Unauthorised request. Please check the settings for the Klarna module, the Merchant ID and the associated password',
    'KLARNA_ORDER_NOT_FOUND'                            => 'This order could not be found in Klarna’s system. Changes to the order details will therefore not be sent to Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Incorrect login details!</strong> This order was placed using the merchant ID <strong>%s</strong>. The merchant ID currently configured for <strong>%s</strong> is <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Product name',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymised product title:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Payment is processed by our partner, Klarna. Please refer to the payment details sent by Klarna. You can manage all your purchases via Klarna.com or the Klarna app, and even pay with just one click.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Voucher discount',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Gift wrapping',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Greeting card',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Critical error: You must specify a valid SSL-secured (https) $this->sSSLShopURL in your shop’s config.inc.php file if you wish to enable the %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Incorrect login details!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'The amount has been successfully debited.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' The payment for the order could not be taken as it had already been cancelled.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Enter the string here that you want to send to Klarna instead of the actual product title.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Any changes you make to this order will not be passed on to Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'User Manual',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Register',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Find out more',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Supported customer types',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Here you can specify whether the shop should accept only B2C transactions (default setting), only B2B transactions, or both B2C and B2B transactions.<br />  Note: After changing the customer types, the browser’s session cache must be cleared so that the payment process can be tested.',
    'TCKLARNA_B2C'                                      => 'B2C customers only',
    'TCKLARNA_B2B'                                      => 'B2B customers only',
    'TCKLARNA_B2B_B2C'                                  => 'Mainly B2B customers, but also B2C customers',
    'TCKLARNA_B2C_B2B'                                  => 'Mainly B2C customers, but also B2B customers',
    'TCKLARNA_NEED_SUPPORT'                             => 'Do you need help with integration?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Contact Klarna’s Merchant Support',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'On-Site Messaging',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Here you can configure the on-site messaging for use with the Klarna module for the OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Script',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion Product Details Page',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Credit Promotion Shopping Basket',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Top-strip Promotion',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Footer Promotion',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Banner Promotion',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Please insert the JavaScript library code snippet required for on-site messaging here; you can find this in the Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Please insert the placement tag here to promote financing and hire purchase via Credit Promotions on the product details page',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Please insert the placement tag here to promote financing and hire purchase via Credit Promotions on the shopping basket overview page',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Please insert the placement tag here to promote generic and payment method-specific information on the shop’s homepage',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Please insert the placement tag here to display your available Klarna payment methods in the shop’s footer',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Please insert the placement tag here to add a banner to your shop’s homepage',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'What is on-site messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Customers are not always aware of the various credit and financing options available to them before they reach the checkout. Financing options made available at an early stage influence the purchasing decision.

On-site messaging is simple and easy to integrate, and provides tailored information ranging from general banners promoting your partnership with Klarna and the availability of instalment payments, right through to personalised credit offers on product or basket pages.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Further information on getting started <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">can be found here</a>:<br /><br /> 
Log in to <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">the merchant portal</a> to generate your personal JavaScript and placement codes. On-site messaging will be activated in your shop as soon as the JavaScript code has been saved and at least one placement code has been entered.<br /> 
You can deactivate it at any time by removing the codes.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Dealer Portal',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Enable Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Active',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Replace the button key',
    'TCKLARNA_IS_REPLACE'                               => 'Create a new \'Key\' button',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'You can update the Button Key if any changes to configuration or identification details on Klarna’s end are required. Normally, once a Button Key has been generated, you can use it for as long as you like.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Enable Klarna Instant Shopping here. This will automatically generate a button key for use in the shop frontend.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Button Styling Settings',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Please choose between a button fully branded in the Klarna style and a more neutral ‘Light’ version.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Please choose whether the text colour of the tagline below the button should be light or dark.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Please select the text you would like to appear on the button.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Button preview',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Display on the product details page',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Enable this feature so that the Klarna Instant Shopping button is displayed on all product detail pages in your shop.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Show on the shopping basket overview',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Enable this feature to display the Klarna Instant Shopping button on the shopping basket overview page in your shop.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Further Instant Shopping settings',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'The delivery address may differ from the billing address',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'If you wish to allow delivery to a different delivery address, please tick this box.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Date of birth as a required field',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'If you wish to make it compulsory to provide a date of birth, please tick this box. Normally, the date of birth is not a compulsory field for Klarna. However, this information is required to enable purchase on account or payment by instalments.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'National ID number as a mandatory field',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Please select whether the national identification number should be a mandatory field.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variation',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Tagline',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Type',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'The telephone number is a required field',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Please select whether the telephone number should be a required field.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Please select from the list which country should be set as the default when Klarna Instant Shopping is launched, provided the customer has not yet specified their country.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Please enter the URL for your Terms and Conditions here. These will be linked in the Klarna Instant Shopping pop-up. You must provide a valid URL beginning with https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Delivery options',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Credit the entire order',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'No active delivery methods found',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Payment method used: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Credit card',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Direct debit',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Instant Bank Transfer',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 interest-free instalments',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financing',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B invoice (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Invoice',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Card payment within 30 days',
];
