<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Español";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Inicio',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Generalidades',
    'TCKLARNA_CONFIGURATION'                            => 'Configuración',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Configuración para Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Configuración de diseño',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Formas de pago externas',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Datos adicionales del distribuidor',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Configuración básica',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Descuento',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'En este modo no hay opciones de configuración.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Se han guardado todos los ajustes.',

    'TCKLARNA_EASY'                                     => 'Activar Klarna es así de fácil',
    'TCKLARNA_PHONE'                                    => 'Teléfono',
    'TCKLARNA_EMAIL'                                    => 'Correo electrónico',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Horario comercial',
    'TCKLARNA_MONDAY'                                   => 'Lunes',
    'TCKLARNA_TUESDAY'                                  => 'Martes',
    'TCKLARNA_WEDNESDAY'                                => 'Miércoles',
    'TCKLARNA_THURSDAY'                                 => 'Jueves',
    'TCKLARNA_FRIDAY'                                   => 'Viernes',
    'TCKLARNA_SATURDAY'                                 => 'Sábado',
    'TCKLARNA_SUNDAY'                                   => 'Domingo',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Sus datos de acceso específicos para cada país',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Añadir datos de acceso específicos de cada país',
    'TCKLARNA_COUNTRY'                                  => 'País',
    'TCKLARNA_MERCHANT_ID'                              => 'Nombre de usuario de la API',
    'TCKLARNA_PASSWORD'                                 => 'Contraseña de la API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID de comerciante',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'País predeterminado de la tienda',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Registro activo',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => '¿Enviar datos adicionales del producto a Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL de los productos',
    'TCKLARNA_IMAGE_URLS'                               => 'URL de las imágenes',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonimizar',
    'TCKLARNA_ADD'                                      => 'Añadir',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Pagos con Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Seleccionar el modo del módulo Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Con Klarna, los clientes finales pueden pagar de tres formas: transferencia inmediata, más tarde o a plazos. Esto permite a los clientes finales probar primero los productos y pagar solo lo que deseen quedarse, financiar la compra en la tienda o pagar al instante. Puede activar el pago mediante factura, a plazos, transferencia inmediata o domiciliación bancaria con una única integración y, gracias a la solución iFrame de Klarna, estas opciones estarán siempre actualizadas tanto desde el punto de vista legal como en cuanto al contenido.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Los métodos de pago más populares. Seguros y fáciles de integrar.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Bienvenido a los ajustes de configuración de Klarna Payments. Aquí encontrarás todo lo necesario para la activación. Selecciona las opciones del submenú de Klarna en la barra de la izquierda para completar la configuración del módulo.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Crear una cuenta de cliente en OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Suscripción al boletín informativo',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Crear una cuenta de cliente Y suscribirse al boletín informativo',
    'TCKLARNA_NO_CHECKBOX'                              => 'No mostrar la casilla de selección',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => '¿Mostrar en la página de inicio de la tienda?',
    'TCKLARNA_BANNER_SRC'                               => 'Fuente del banner de Klarna',
    'TCKLARNA_FOOTER'                                   => 'Pie de página',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => '¿Qué se debe mostrar en el pie de página?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visualización de las formas de pago',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logotipo de Klarna',
    'TCKLARNA_DESIGN'                                   => 'Diseño',
    'TCKLARNA_LONG_VERSION'                             => 'Versión larga:',
    'TCKLARNA_SHORT_VERSION'                            => 'Versión resumida:',
    'TCKLARNA_WHITE'                                    => 'Blanco:',
    'TCKLARNA_BLACK'                                    => 'Negro:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Página de detalles del artículo y cesta de la compra',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => '¿Mostrar el widget del método de pago de Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'En la página de detalles del artículo',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'En la página del carrito de la compra',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => '¿Mostrar el botón «Comprar ahora»?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Opciones de diseño de pago de Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Ajustes de color:',
    'TCKLARNA_BORDER'                                   => 'Frontera:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Borde seleccionado:',
    'TCKLARNA_BUTTON'                                   => 'Botón:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Texto del botón:',
    'TCKLARNA_CHECKBOX'                                 => 'Casilla de selección:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Casilla de selección marcada:',
    'TCKLARNA_DETAILS'                                  => 'Detalles:',
    'TCKLARNA_HEADER'                                   => 'Encabezado:',
    'TCKLARNA_LINK'                                     => 'Enlace:',
    'TCKLARNA_TEXT'                                     => 'Texto:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Texto adicional:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Ajuste del radio:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Radio del borde:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'La dirección de entrega puede ser diferente de la dirección de facturación',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'El número de teléfono es un campo obligatorio',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'La fecha de nacimiento es un campo obligatorio',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Activar la entrega en un punto de recogida de DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Activar el prellenado',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Activar la indicación de prellenado',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'El tratamiento es un campo obligatorio',
    'TCKLARNA_SET_TAC_URI'                              => 'URL de sus condiciones generales de contratación',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL sobre el derecho de desistimiento',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Detalles del envío',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Sin validación',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Realizar la validación, pero ignorar los tiempos de espera',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Es necesario que la validación se realice con éxito',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Validación del pedido',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Seleccione las opciones de pago de Klarna que desee ofrecer a sus clientes:',
    'TCKLARNA_PAY_LATER'                                => 'Factura',
    'TCKLARNA_PAY_LATER.'                               => 'Factura.',
    'TCKLARNA_PAY_LATER_START'                          => 'Para los clientes que quieran comprar ahora y pagar más tarde. De forma muy cómoda, en 14, 21 o 28 días, según el mercado.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'La opción «Factura» permite a los clientes realizar el pago de forma sencilla y rápida, sin tener que introducir datos personales ni números complicados. El cliente puede elegir entre pagar mediante factura o pagar en el mes X.',
    'TCKLARNA_SLICE_IT'                                 => 'Compra a plazos.',
    'TCKLARNA_SLICE_IT.'                                => 'Pagar a plazos.',
    'TCKLARNA_SLICE_IT_START'                           => 'Aumente el poder adquisitivo de sus clientes mediante el pago a plazos. Los clientes pueden abonar sus compras en cuotas mensuales fijas durante un periodo de entre 6 y 36 meses.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Mediante la «compra a plazos», los clientes pueden fraccionar el importe de la compra en pequeñas cuotas con un tipo de interés reducido. Esto aumenta el margen de inversión y el poder adquisitivo. El exclusivo proceso de tramitación de créditos de Klarna solo requiere unos segundos y una introducción mínima de datos.',
    'TCKLARNA_PAY_NOW'                                  => 'Pagar ahora',
    'TCKLARNA_PAY_NOW.'                                 => 'Pagar ahora.',
    'TCKLARNA_PAY_NOW_START'                            => 'Pago directo, sencillo y rápido con la opción «Pagar ahora» de Klarna. En Alemania, no pueden faltar en la cartera las opciones de transferencia inmediata, tarjeta de crédito y domiciliación bancaria.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Los clientes que deseen abonar el importe íntegro de inmediato al finalizar el pedido pueden utilizar la opción «Pagar ahora». Para ello, pueden elegir entre tarjeta de crédito, domiciliación bancaria y transferencia inmediata.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Guía sobre cómo <br />activar Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'En el panel de administración de OXID, haz clic en la nueva opción de menú «Klarna», en la subcategoría «General» y, a continuación, selecciona el producto de Klarna que desees.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Introduzca sus datos de acceso (nombre de usuario y contraseña) y configure las asignaciones típicas de OXID para los métodos de pago en «Configuración de la tienda» &gt; «Métodos de pago» y «Métodos de envío».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Guarda los cambios.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Ya estás en línea y puedes empezar a vender con Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Asistencia para comerciantes',
    'TCKLARNA_DEVICE_IMG'                               => 'dispositivo.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Aquí puede configurar si, en su caso, se deben transferir datos adicionales del comerciante a Klarna. 
Para obtener una descripción detallada de los distintos ajustes, consulte las descripciones emergentes en 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lea el <a class="cl-pink" href="%s" target="_blank">manual</a> en 
o póngase en contacto con el servicio de asistencia de integración de Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Aquí puede configurar los ajustes de diseño para utilizarlos con el módulo de Klarna para la tienda OXID eShop. 
Para obtener una descripción detallada de los distintos ajustes, consulte las descripciones emergentes en 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lea el <a class="cl-pink" href="%s" target="_blank">manual</a> en 
o póngase en contacto con el servicio de asistencia de integración de Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Aquí puede configurar las opciones de Klarna Payments y establecer los ajustes generales. 
Para obtener una descripción detallada de los distintos ajustes, consulte las descripciones emergentes en 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lea el <a class="cl-pink" href="%s" target="_blank">manual</a> en 
o póngase en contacto con el servicio de asistencia de integración de Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'En esta página puede seleccionar qué métodos de pago de Klarna desea ofrecer. 
Para obtener una descripción detallada de las distintas configuraciones, consulte las descripciones emergentes en 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, lea el <a class="cl-pink" href="%s" target="_blank">manual</a> en 
o póngase en contacto con el servicio de asistencia para la integración de Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Forma de pago',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Forma de pago externa',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI de la imagen para el método de pago externo',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Tamaño de la imagen: 69 x 24 píxeles',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Tamaño de la imagen: 276 x 48 píxeles',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Aquí puede consultar el manual de usuario del módulo de Klarna para OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Manual de usuario',

    'TCKLARNA_CHOOSE'                                   => 'Votar',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Información sobre la cuenta de cliente',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Historial completo de pagos',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Campo de paso',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Asignar tipo de forma de pago:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => '¿Qué pedidos deben incluirse en el «Historial de pagos completo»?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Considerar todos los pedidos como pagados, independientemente de la fecha de Oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Enviar únicamente los pedidos que tengan una fecha de pago «oxpaid» establecida; ignorar los pedidos pendientes de pago.',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorar todos los pedidos realizados con esta forma de pago',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Otra forma de pago',
    'TCKLARNA_DIRECT_BANKING'                           => 'Transferencia inmediata',
    'TCKLARNA_CARD'                                     => 'Mapa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Elige entre «Playground» (modo de prueba) y «Live» (modo de producción). Activa el modo de producción únicamente tras haber realizado con éxito las pruebas de integración y tras consultarlo con tu gestor de integración de Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Introduzca aquí sus datos de acceso a la API de Klarna. Los habrá recibido en el correo electrónico de bienvenida de Klarna. Este nombre de usuario y contraseña son válidos para todos los países. Solo en caso de que haya recibido datos de acceso diferentes para distintos países, podrá añadirlos más abajo.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Introduzca aquí la contraseña correspondiente al nombre de usuario de la API que utilice. Ha recibido esta contraseña en el correo electrónico de bienvenida de Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Introduzca aquí su ID de comerciante de Klarna. Lo recibió en el correo electrónico de bienvenida de Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Seleccione en la lista de la izquierda el país para el que haya recibido los datos de acceso específicos de Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Introduzca aquí el nombre de usuario correspondiente a este país.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Introduzca aquí la contraseña correspondiente a este país.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Introduzca aquí el ID de comerciante correspondiente a este país.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Activa la función de registro para que toda la comunicación mediante API con Klarna quede registrada en la tabla tcklarna_logs de MySQL. Esto puede resultar útil para el análisis o la resolución de errores. En el entorno de producción, esta función debe estar desactivada, ya que, de lo contrario, podrían acumularse grandes cantidades de registros y almacenarse datos confidenciales.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Envíe a Klarna las URL de las páginas de detalles de los productos que se encuentran en el carrito de la compra de sus clientes, para que Klarna pueda enlazar posteriormente a sus artículos desde el portal de Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Envía a Klarna las URL de las imágenes de los artículos que se encuentran en el carrito de la compra de tus clientes, para que Klarna pueda mostrarlas en el portal de Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Active la función de anonimización para ocultar a Klarna los nombres de los artículos que se encuentran en el carrito de la compra de sus clientes. Se recomienda esta opción, por ejemplo, para las farmacias en línea, pero solo debe aplicarse tras consultar con el gestor de integración de Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Si desea que sea posible realizar la entrega en una dirección de entrega diferente, active este botón.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Si desea que sea obligatorio introducir un número de teléfono, active este botón. Normalmente, en Klarna el número de teléfono no es un campo obligatorio.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Si desea que la indicación de la fecha de nacimiento sea obligatoria, active este botón. Normalmente, para Klarna la fecha de nacimiento no es un campo obligatorio. Sin embargo, es necesario indicarla para poder realizar la compra a cuenta o mediante pago a plazos.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Por el momento no está implementado',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Indique aquí la URL de su página web en la que figura la información sobre el derecho de desistimiento. La URL debe comenzar por https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Estas instrucciones de envío se muestran al cliente en la página de agradecimiento tras finalizar el pedido.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Asigne esta forma de pago externa a una de las formas de pago predefinidas',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Por favor, indique una URL para todos los idiomas',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Introduzca una URL válida que comience por https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Este botón activa el envío de datos adicionales a Klarna; en este caso, la información de la cuenta del cliente, que incluye la fecha de registro de la cuenta y la fecha de su última modificación.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Este botón activa el envío de datos adicionales a Klarna; en este caso, se trata del «Payment History Full», que incluye las compras realizadas hasta la fecha por el cliente.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Por favor, indique a qué tipo de forma de pago corresponde este método de pago.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Indique aquí si desea que se incluyan los pedidos realizados con esta forma de pago en la transferencia del historial de pedidos del cliente y, en su caso, cuáles. La dependencia del campo OXORDER.OXPAID determina si se deben tener en cuenta solo los pedidos pagados o todos los pedidos.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Existe la posibilidad de enviar cualquier otro dato a Klarna mediante un campo «pass-through». Para utilizar esta función, debe instalar el módulo correspondiente en OXID eShop, que introduzca los datos deseados en el campo «pass-through». Encontrará las instrucciones correspondientes en la documentación para desarrolladores.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Con este botón, podrás activar un banner de Klarna en la página de inicio de tu tienda en el tema predeterminado Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Aquí puede introducir la etiqueta de script para la integración del banner. En el portal de banners de Klarna encontrará, si lo desea, más banners entre los que elegir.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Con este botón, podrás activar la visualización del método de pago Klarna en el pie de página de tu tienda, en el tema predeterminado Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Con este botón podrás añadir el logotipo de Klarna al pie de página de tu tienda en el tema predeterminado Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Este control añade un botón «Comprar ahora» a las páginas de detalles de los artículos de tu tienda en el tema predeterminado Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Color del recuadro que aparece en la interfaz de la tienda tras seleccionar la forma de pago Klarna, en caso de que haya varias subopciones disponibles.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Color del marco que aparece en la interfaz de la tienda tras seleccionar la forma de pago Klarna, en caso de que haya varias subopciones disponibles. Este valor de color se utiliza para resaltar la subopción seleccionada en ese momento.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Esta configuración aún no tiene ningún efecto en el momento de la publicación de este módulo.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Esta configuración aún no tiene ningún efecto en el momento de la publicación de este módulo.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Color de fondo de los botones de radio que aparecen en la interfaz de la tienda tras seleccionar la forma de pago «Klarna», en caso de que haya varias subopciones disponibles',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Esta configuración aún no tiene ningún efecto en el momento de la publicación de este módulo.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Color de los símbolos de enumeración en la visualización de los detalles de pago en la página de selección de formas de pago.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Esta configuración aún no tiene ningún efecto en el momento de la publicación de este módulo.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Color de los enlaces que aparecen en la descripción detallada de las formas de pago en la página de selección de formas de pago.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Color del texto de la descripción detallada de las formas de pago en la página de selección de formas de pago.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Color alternativo del texto de la descripción detallada de las formas de pago en la página de selección de formas de pago.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Con esta configuración, puedes establecer el grado de redondeo del marco que aparecerá en la interfaz de la tienda tras seleccionar la forma de pago Klarna, en función de las distintas subopciones disponibles.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Esta pestaña solo se aplica a los pedidos de Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Capturar el pedido completo',
    'KLARNA_CAPTURE_ID'                                 => 'N.º de cargo',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Referencia de Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Importe del cargo',
    'KLARNA_CAPTURE_DATE'                               => 'Cargado el',
    'KLARNA_REFUND_AMOUNT'                              => 'Importe del reembolso',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Reembolso: explicación',
    'KLARNA_REFUND_DATE'                                => 'Sustituido por',
    'KLARNA_CAPTURES'                                   => 'Cargos',
    'KLARNA_REFUNDS'                                    => 'Reembolsos',
    'KLARNA_CANCEL_ORDER'                               => 'Cancelar el pedido',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'El pedido se ha cancelado. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Acceder a este pedido en el portal de Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>¡Atención!</strong> Los datos de este pedido difieren de los datos almacenados en Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => '¡Atención! Debido al estado actual del pedido, este ajuste no se puede enviar a Klarna. Si es necesario, realice el ajuste correspondiente manualmente en el portal para comerciantes de Klarna.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => '¡Atención! Klarna no ha podido procesar los últimos cambios que ha realizado en este pedido (motivo: %s). Le rogamos que deshaga los cambios recientes en la tienda OXID eShop o que, si es necesario, realice los ajustes correspondientes manualmente en el portal de comerciantes de Klarna.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Solicitud no autorizada. Compruebe la configuración del módulo de Klarna, así como el ID de comerciante y la contraseña correspondiente.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'No se ha podido encontrar este pedido en el sistema de Klarna. Por lo tanto, los cambios en los datos del pedido no se transmitirán a Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>¡Datos de acceso incorrectos!</strong> Este pedido se ha realizado utilizando el ID de comerciante <strong>%s</strong>. El ID de comerciante configurado actualmente para <strong>%s</strong> es <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Nombre del producto',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Título del producto anonimizado:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'El pago lo gestiona nuestro socio Klarna. Por favor, ten en cuenta la información de pago que te haya enviado Klarna. Puedes gestionar todas tus compras a través de Klarna.com o de la aplicación de Klarna, e incluso pagar con un solo clic.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Cupón de descuento',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Envase de regalo',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Tarjeta de felicitación',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Error grave: ¡Es obligatorio indicar una URL válida protegida por SSL (https) en $this-&gt;sSSLShopURL en el archivo config.inc.php de tu tienda si deseas activar el %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>¡Datos de acceso incorrectos!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'El importe se ha cargado correctamente.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' No se ha podido cobrar el pedido, ya que ya se había cancelado.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Introduzca aquí la cadena de texto que se enviará a Klarna en lugar del título real del producto.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Los cambios que realice en este pedido no se transferirán a Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Manual de usuario',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrarse',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Más información',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Tipos de clientes admitidos',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Aquí puede configurar si la tienda debe aceptar exclusivamente transacciones B2C (configuración predeterminada), solo transacciones B2B o tanto transacciones B2C como B2B.<br />  Nota: Tras cambiar los tipos de cliente, es necesario borrar la caché de sesión del navegador para poder probar el proceso de pago.',
    'TCKLARNA_B2C'                                      => 'Solo clientes B2C',
    'TCKLARNA_B2B'                                      => 'Solo clientes B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Principalmente clientes B2B, pero también clientes B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Principalmente clientes B2C, pero también clientes B2B',
    'TCKLARNA_NEED_SUPPORT'                             => '¿Necesita ayuda con la integración?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Póngase en contacto con el servicio de atención al comerciante de Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Mensajería en la propia página web',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Aquí puede configurar los mensajes en la página web para utilizarlos con el módulo de Klarna para OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Guión',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Página de detalles del artículo de Credit Promotion',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Cesta de la compra de Credit Promotion',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Promoción «Top-strip»',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Promoción en el pie de página',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Promoción con banners',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Por favor, inserte aquí el fragmento de código de la biblioteca JavaScript necesario para el servicio de mensajería en la página web, que puede obtener en el portal de comerciantes de Klarna.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Por favor, inserte aquí la etiqueta de colocación para promocionar la financiación y la compra a plazos a través de Credit Promotions en la página de detalles del artículo.',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Por favor, inserte aquí la etiqueta de colocación para promocionar la financiación y la compra a plazos a través de Credit Promotions en la página de resumen del carrito de la compra.',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Por favor, inserta aquí la etiqueta de colocación para promocionar información genérica y específica sobre los métodos de pago en la página de inicio de la tienda.',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Por favor, inserte aquí la etiqueta de colocación para mostrar las formas de pago disponibles de Klarna en el pie de página de la tienda.',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Por favor, inserta aquí la etiqueta de colocación para añadir un banner en la página de inicio de tu tienda.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => '¿Qué es la mensajería en la propia página web?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Los clientes no siempre son conscientes de las diferentes opciones de crédito y financiación de las que disponen antes de llegar a la caja. Las opciones de financiación disponibles desde el principio influyen en la decisión de compra. 
 
La función de mensajes en la página web es fácil de integrar y ofrece información a medida, que abarca desde banners generales sobre la promoción de tu colaboración con Klarna y la disponibilidad del pago a plazos, hasta promociones de crédito personalizadas en las páginas de productos o en la cesta de la compra.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => '<a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">Encontrará</a> más información sobre los primeros pasos <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">aquí</a>:<br /><br /> 
Inicie sesión en <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">el portal para comerciantes</a> para generar su código JavaScript y su código de ubicación personales. La función de mensajería en la página se activará en su tienda en cuanto se haya guardado el código JavaScript y se haya introducido al menos un código de ubicación.<br /> 
Puede desactivarla en cualquier momento eliminando los códigos.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portal para distribuidores',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Activar Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Activo',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Sustituir la tecla del botón',
    'TCKLARNA_IS_REPLACE'                               => 'Crear un nuevo botón «Key»',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Puede actualizar la «Button Key» si es necesario modificar los datos de configuración o identificación por parte de Klarna. Normalmente, una vez generada, puede utilizar la «Button Key» durante el tiempo que desee.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Activa aquí Klarna Instant Shopping. De este modo, se generará automáticamente un botón para utilizarlo en la interfaz de la tienda.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Configuración del estilo de los botones',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Elige entre un botón con el diseño completo de Klarna y una variante «Light» más neutra.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Seleccione si el color de la letra del eslogan que aparece debajo del botón debe ser claro u oscuro.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Seleccione el texto que desee que aparezca en el botón.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Vista previa del botón',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Mostrar en la página de detalles del artículo',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Activa esta función para que el botón «Klarna Instant Shopping» aparezca en todas las páginas de detalles de los artículos de tu tienda.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Mostrar en el resumen de la cesta de la compra',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Activa esta función para que aparezca el botón «Klarna Instant Shopping» en la página de resumen del carrito de la compra de tu tienda.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Otras opciones de Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'La dirección de entrega puede ser diferente de la dirección de facturación',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Si desea que sea posible realizar la entrega en una dirección de entrega diferente, active este botón.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'La fecha de nacimiento es un campo obligatorio',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Si desea que la indicación de la fecha de nacimiento sea obligatoria, active este botón. Normalmente, para Klarna la fecha de nacimiento no es un campo obligatorio. Sin embargo, es necesario indicarla para poder realizar la compra a cuenta o mediante pago a plazos.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'El número de identificación nacional es un campo obligatorio',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Seleccione si el número de identificación nacional debe ser un campo obligatorio.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variación',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Eslogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Tipo',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'El número de teléfono es un campo obligatorio',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Seleccione si el número de teléfono debe ser un campo obligatorio.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Seleccione de la lista el país que se mostrará por defecto al acceder a Klarna Instant Shopping, siempre que el cliente aún no haya indicado su país.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Introduce aquí la URL de tus condiciones generales de contratación. Estas aparecerán como enlace en la ventana emergente de Klarna Instant Shopping. Debes introducir una URL válida que comience por https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Formas de envío',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Abonar el importe total del pedido',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'No se han encontrado métodos de envío activos',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Forma de pago utilizada: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Tarjeta de crédito',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Débito directo',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Transferencia inmediata',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 plazos sin intereses',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financiación',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Factura B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Factura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Pago con tarjeta a 30 días',
];
