<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Svenska";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Start',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Allmänt',
    'TCKLARNA_CONFIGURATION'                            => 'Konfiguration',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfiguration för Klarna Payments',
    'TCKLARNA_KLARNADESIGN'                             => 'Designinställningar',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Externa betalningssätt',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ytterligare uppgifter om återförsäljaren',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Grundinställningar',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Rabatt',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'I det här läget finns det inga inställningar.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Alla inställningar har sparats.',

    'TCKLARNA_EASY'                                     => 'Så enkelt är det att aktivera Klarna',
    'TCKLARNA_PHONE'                                    => 'Telefon',
    'TCKLARNA_EMAIL'                                    => 'E-post',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Öppettider',
    'TCKLARNA_MONDAY'                                   => 'Måndag',
    'TCKLARNA_TUESDAY'                                  => 'tisdag',
    'TCKLARNA_WEDNESDAY'                                => 'Onsdag',
    'TCKLARNA_THURSDAY'                                 => 'torsdag',
    'TCKLARNA_FRIDAY'                                   => 'fredag',
    'TCKLARNA_SATURDAY'                                 => 'lördag',
    'TCKLARNA_SUNDAY'                                   => 'söndag',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Dina landsspecifika inloggningsuppgifter',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Lägg till landsspecifika inloggningsuppgifter',
    'TCKLARNA_COUNTRY'                                  => 'Land',
    'TCKLARNA_MERCHANT_ID'                              => 'API-användarnamn',
    'TCKLARNA_PASSWORD'                                 => 'API-lösenord',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Handlar-ID',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Butikens standardland',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Loggningsfunktionen är aktiv',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Ska utökade produktuppgifter skickas till Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'Produkt URLs',
    'TCKLARNA_IMAGE_URLS'                               => 'Bild URLs',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymisera',
    'TCKLARNA_ADD'                                      => 'Lägg till',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Klarna-betalningar',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Välj läge för Klarna-modulen',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Med Klarna kan slutkunderna betala på tre olika sätt: direktöverföring, senare eller i delbetalningar. Detta gör det möjligt för slutkunderna att först prova varorna och bara betala för det de vill behålla, finansiera produkterna i butiken eller betala direkt. Faktura, avbetalning, omedelbar överföring eller autogiro kan du aktivera med en integration och är tack vare Klarnas iFrame-lösning alltid uppdaterade både juridiskt och innehållsmässigt.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'De mest populära betalningssätten. Säkra och enkla att integrera.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Välkommen till konfigurationsinställningarna för Klarna Payments. Här hittar du allt du behöver för att aktivera tjänsten. Välj undermenyerna för Klarna i menyn till vänster för att slutföra modulens inställningar.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Skapa ett kundkonto i OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Anmälan till nyhetsbrevet',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Skapa ett kundkonto OCH prenumerera på nyhetsbrevet',
    'TCKLARNA_NO_CHECKBOX'                              => 'Visa ingen kryssruta',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Ska den visas på butikens startsida?',
    'TCKLARNA_BANNER_SRC'                               => 'Källa till Klarna-banner',
    'TCKLARNA_FOOTER'                                   => 'Fotnot',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Vad ska visas i sidfoten?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Visning av betalningssätt',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Klarna Logo',
    'TCKLARNA_DESIGN'                                   => 'Design',
    'TCKLARNA_LONG_VERSION'                             => 'Lång version:',
    'TCKLARNA_SHORT_VERSION'                            => 'Kortversion:',
    'TCKLARNA_WHITE'                                    => 'Vit:',
    'TCKLARNA_BLACK'                                    => 'Svart:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Artikelsida och varukorg',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Visa Klarna-betalningswidgeten?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'På artikelns detaljsida',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'På sidan med varukorgen',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Visa knappen ”Köp nu”?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Alternativ för Klarna Payment Design',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Färginställningar:',
    'TCKLARNA_BORDER'                                   => 'Gräns:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Markerad gräns:',
    'TCKLARNA_BUTTON'                                   => 'Knapp:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Text på knappen:',
    'TCKLARNA_CHECKBOX'                                 => 'Kryssruta:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Kryssruta:',
    'TCKLARNA_DETAILS'                                  => 'Detaljer:',
    'TCKLARNA_HEADER'                                   => 'Rubrik:',
    'TCKLARNA_LINK'                                     => 'Länk:',
    'TCKLARNA_TEXT'                                     => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Ytterligare text:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Inställning av radie:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Kantradie:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Leveransadressen får skilja sig från fakturaadressen',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefonnummer är ett obligatoriskt fält',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Födelsedatum är ett obligatoriskt fält',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktivera leverans till DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktivera förifyllning',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktivera anvisningen om förfyllning',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Titeln är ett obligatoriskt fält',
    'TCKLARNA_SET_TAC_URI'                              => 'Länk till era allmänna villkor',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Länk till information om ångerrätten',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Leveransinformation',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Ingen validering',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Utför validering, men ignorera tidsgränser',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Framgångsrik validering krävs',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Orderbekräftelse',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Välj de betalningsalternativ från Klarna som du vill erbjuda dina kunder:',
    'TCKLARNA_PAY_LATER'                                => 'Faktura',
    'TCKLARNA_PAY_LATER.'                               => 'Faktura.',
    'TCKLARNA_PAY_LATER_START'                          => 'För kunder som vill köpa nu och betala senare. Helt bekvämt inom 14, 21 eller 28 dagar, beroende på marknad.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Alternativet ”Faktura” gör betalningsprocessen enkel och snabb för kunderna, utan att de behöver ange personuppgifter eller komplicerade nummer. Kunden kan välja mellan faktura och att betala under månad X.',
    'TCKLARNA_SLICE_IT'                                 => 'Avbetalningsköp.',
    'TCKLARNA_SLICE_IT.'                                => 'Betala i delbetalningar.',
    'TCKLARNA_SLICE_IT_START'                           => 'Öka dina kunders köpkraft genom delbetalning. Kunderna kan betala sina inköp i fasta månadsrater under en period på 6 till 36 månader.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Genom ”avbetalningsköp” kan kunderna dela upp köpesumman i mindre delbetalningar till låg ränta. Detta ökar investeringsutrymmet och köpkraften. Klarnas unika kreditbehandling tar bara några ögonblick och kräver minimalt med uppgifter.',
    'TCKLARNA_PAY_NOW'                                  => 'Betala direkt',
    'TCKLARNA_PAY_NOW.'                                 => 'Betala direkt.',
    'TCKLARNA_PAY_NOW_START'                            => 'Enkel och snabb direktbetalning med Klarnas ”Sofort bezahlen”. I Tyskland bör Sofortüberweisung, kreditkort och autogiro ingå i utbudet.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Kunder som vill betala hela beloppet direkt vid beställningens slutförande kan använda alternativet ”Betala direkt”. Här kan man välja mellan kreditkort, autogiro och Sofortüberweisung.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Guide till hur man <br />aktiverar Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Klicka på den nya menyposten Klarna i OXID-backend, välj underkategorin Allmänt och välj sedan önskad Klarna-produkt.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Ange dina inloggningsuppgifter (användarnamn och lösenord) och gör de för OXID typiska inställningarna för betalningssätt under Butiksinställningar &gt; Betalningssätt samt &gt; Fraktalternativ.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Spara ändringarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Ni är nu online och kan börja sälja med Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Support för handlare',
    'TCKLARNA_DEVICE_IMG'                               => 'enhet.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Här kan du ställa in om eventuella extra handelsuppgifter ska överföras till Klarna. 
För en detaljerad beskrivning av de olika inställningarna, se verktygstipsen 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, läs <a class="cl-pink" href="%s" target="_blank">handboken</a> 
eller kontakta Klarnas integrationssupport.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Här kan du konfigurera designinställningarna för användning med Klarna-modulen för OXID eShop. 
För en detaljerad beskrivning av de olika inställningarna, se verktygstipsen 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, läs <a class="cl-pink" href="%s" target="_blank">handb</a>oken 
eller kontakta Klarnas integrationssupport.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Här kan du göra dina val för Klarna Payments och ställa in övergripande inställningar. 
För en detaljerad beskrivning av de olika inställningarna, se verktygstipsen 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, läs <a class="cl-pink" href="%s" target="_blank">handb</a>oken 
eller kontakta Klarnas integrationssupport.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'På den här sidan väljer du vilka Klarna-betalningsalternativ du vill erbjuda. 
För en detaljerad beskrivning av de olika inställningarna, se verktygstipsen 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, läs <a class="cl-pink" href="%s" target="_blank">handboken</a> 
eller kontakta Klarnas integrationssupport.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Betalningssätt',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Extern betalningsmetod',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'Bild-URI för extern betalningsmetod',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Bildstorlek: 69x24 pixlar',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Bildstorlek: 276x48 pixlar',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Här kan du läsa användarhandboken för Klarna-modulen för OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Användarhandbok',

    'TCKLARNA_CHOOSE'                                   => 'Välj',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Information om kundkontot',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Fullständig betalningshistorik',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Genomgångsfält',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Tilldela betalningssättstyp:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Vilka beställningar ska inkluderas i den fullständiga betalningshistoriken?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Alla beställningar ska betraktas som betalda, oavsett datum för oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Skicka endast beställningar med angivet oxpaid-datum; ignorera obetalda beställningar',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Ignorera alla beställningar som har gjorts med denna betalningsmetod',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Andra betalningsalternativ',
    'TCKLARNA_DIRECT_BANKING'                           => 'Direktöverföring',
    'TCKLARNA_CARD'                                     => 'Karta',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Välj mellan Playground (testdrift) och Live (produktiv drift). Aktivera produktiv drift först efter att integrationstesterna har genomförts med gott resultat och efter samråd med din Klarna Integration Manager.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Ange här dina inloggningsuppgifter för Klarnas API. Du har fått dessa i välkomstmejlet från Klarna. Användarnamnet och lösenordet gäller globalt för alla länder. Endast om du har fått olika inloggningsuppgifter för olika länder kan du lägga till dessa längre ner.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Ange här ditt lösenord som hör till det API-användarnamn du använder. Du har fått detta lösenord i välkomstmejlet från Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Ange här ditt Klarna-handlar-ID. Du har fått detta i välkomstmejlet från Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Välj det land i listan till vänster för vilket du har fått landspecifika inloggningsuppgifter från Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Ange här det användarnamn som gäller för detta land.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Ange här lösenordet för detta land.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Ange här det tillhörande Merchant ID för detta land.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktiverar loggningsfunktionen så att all API-kommunikation med Klarna loggas i MySQL-tabellen tcklarna_logs. Detta kan vara användbart vid analys eller felsökning. I produktiv drift bör funktionen vara avstängd, eftersom det annars kan leda till att stora mängder loggdata ackumuleras och att känslig information lagras.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Skicka URL-adresserna till produktdetaljsidorna för de produkter som finns i dina kunders varukorg till Klarna, så att Klarna senare kan länka till dina produkter från Klarna-portalen.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Skicka URL:erna till produktbilderna för de varor som finns i kundernas varukorg till Klarna, så att Klarna kan visa dem i Klarna-portalen.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktivera anonymiseringen för att dölja produktnamnen i dina kunders varukorg för Klarna. Detta rekommenderas till exempel för onlineapotek, men bör endast göras efter samråd med Klarnas integrationsansvarige.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Om leverans till en annan leveransadress ska vara möjlig, aktivera den här knappen.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Om ni vill göra det obligatoriskt att ange ett telefonnummer, aktivera den här knappen. Normalt sett är telefonnumret inte ett obligatoriskt fält för Klarna.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Om ni vill göra det obligatoriskt att ange födelsedatum, aktivera den här knappen. Normalt sett är födelsedatumet inte ett obligatoriskt fält hos Klarna. Uppgiften är dock nödvändig för att möjliggöra köp på faktura eller delbetalning.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'För närvarande inte implementerat',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Ange här webbadressen till din webbplats där informationen om ångerrätten finns. Webbadressen måste börja med https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Dessa leveransuppgifter visas för kunden på tack-sidan efter att beställningen har slutförts.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Koppla denna externa betalningsmetod till en av de fördefinierade betalningsmetoderna',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Ange en URL för alla språk',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Ange en giltig URL som börjar med https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Denna knapp aktiverar överföringen av ytterligare data till Klarna, i detta fall kundkontoinformationen, som innehåller datumet för registreringen av kundkontot och datumet för den senaste ändringen.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Denna knapp aktiverar överföringen av ytterligare data till Klarna, i detta fall ”Payment History Full”, som innehåller kundens tidigare köp.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Vänligen ange vilken typ av betalningssätt det här rör sig om.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Ange här om, och i så fall vilka, beställningar som ska ingå i kundens beställningshistorik när denna överförs med detta betalningssätt. Beroendet för fältet OXORDER.OXPAID anger om endast betalda beställningar eller alla beställningar ska beaktas.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Det finns möjlighet att skicka ytterligare valfria uppgifter till Klarna med hjälp av ett pass-through-fält. För att kunna använda denna funktion måste du installera en lämplig modul i OXID eShop som skriver in de önskade uppgifterna i pass-through-fältet. Du hittar instruktioner för detta i utvecklardokumentationen.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Med den här knappen aktiverar du en Klarna-banner på din webbutiks startsida i standardtemat Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Här kan du ange script-taggen för att integrera bannern. I Klarnas bannerportal kan du eventuellt hitta fler banners att välja mellan.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Med den här knappen aktiverar du Klarna-betalningsmetodvisningen i sidfoten på din webbutik i standardtemat Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Med den här knappen kan du lägga till Klarna-logotypen i sidfoten på din webbutik i standardtemat Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Den här knappen lägger till en ”Köp nu”-knapp på artikelsidorna i din webbutik i standardtemat Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Färgen på ramen som visas i butikens frontend när man väljer betalningssättet Klarna, beroende på vilka underalternativ som finns tillgängliga.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Färgen på ramen som visas i butikens frontend när man väljer betalningssättet Klarna och det finns flera underalternativ att välja mellan. Denna färg används för att markera det underalternativ som för tillfället är aktivt valt.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Denna inställning har ännu ingen effekt vid tidpunkten för publiceringen av detta modul.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Denna inställning har ännu ingen effekt vid tidpunkten för publiceringen av detta modul.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Bakgrundsfärgen på radioknapparna som visas i webbutikens frontend när man väljer betalningssättet Klarna och det finns flera underalternativ att välja mellan',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Denna inställning har ännu ingen effekt vid tidpunkten för publiceringen av detta modul.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Färgen på punktmarkeringarna vid visningen av betalningsuppgifterna på sidan för val av betalningssätt.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Denna inställning har ännu ingen effekt vid tidpunkten för publiceringen av detta modul.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Färgen på länkarna i detaljbeskrivningen av betalningssätten på sidan för val av betalningssätt.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Textfärg för detaljbeskrivningen av betalningssätten på sidan för val av betalningssätt.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternativ textfärg för detaljbeskrivningen av betalningssätten på sidan för val av betalningssätt.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Med den här inställningen kan du ange graden av avrundning för ramen som visas i butikens frontend när du väljer betalningssättet Klarna, beroende på vilka underalternativ som finns tillgängliga.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Denna flik gäller endast beställningar via Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Registrera hela beställningen',
    'KLARNA_CAPTURE_ID'                                 => 'Debiterings-ID',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Klarna-referens',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Avdragsbelopp',
    'KLARNA_CAPTURE_DATE'                               => 'Draget den',
    'KLARNA_REFUND_AMOUNT'                              => 'Återbetalningsbelopp',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Återbetalning – Förklaring',
    'KLARNA_REFUND_DATE'                                => 'Ersatt den',
    'KLARNA_CAPTURES'                                   => 'Avdrag',
    'KLARNA_REFUNDS'                                    => 'Återbetalningar',
    'KLARNA_CANCEL_ORDER'                               => 'Avboka beställning',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Beställningen har annullerats. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Öppna denna beställning i Klarna-portalen</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Obs!</strong> Uppgifterna för denna beställning skiljer sig från de uppgifter som finns lagrade hos Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Obs! På grund av den aktuella beställningsstatusen kan denna justering inte överföras till Klarna. Gör vid behov justeringen manuellt direkt i Klarnas Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Obs! Dina senaste ändringar av denna beställning kunde inte behandlas av Klarna (orsak: %s). Vänligen ångra dina senaste ändringar i OXID eShop eller gör den nödvändiga justeringen manuellt i Klarna Merchant Portal om så krävs.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Ogiltig förfrågan. Kontrollera inställningarna för Klarna-modulen samt Merchant ID och tillhörande lösenord',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Denna beställning kunde inte hittas i Klarnas system. Ändringar av beställningsuppgifterna kommer därför inte att överföras till Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Felaktiga inloggningsuppgifter!</strong> Denna beställning gjordes med återförsäljar-ID:t <strong>%s</strong>. Det återförsäljar-ID som för närvarande är konfigurerat för <strong>%s</strong> är <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Produktnamn',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymiserad produkttitel:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Betalningen hanteras av vår samarbetspartner Klarna. Vänligen följ de betalningsuppgifter som Klarna har skickat. Du kan hantera alla dina köp via Klarna.com eller Klarna-appen och till och med betala med ett enda klick.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Rabattkupong',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Presentförpackning',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Gratulationskort',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Allvarligt fel: Det är obligatoriskt att ange en giltig SSL-skyddad (https) $this-&gt;sSSLShopURL i filen config.inc.php i din webbutik om du vill aktivera %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Felaktiga inloggningsuppgifter!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Beloppet har debiterats.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Beställningen kunde inte debiteras eftersom den redan hade annullerats.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Ange här den teckensträng som ska skickas till Klarna istället för den faktiska produkttiteln.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Dina ändringar av denna beställning överförs inte till Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Användarhandbok',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrera dig',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Läs mer',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Typer av kunder som stöds',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Här kan du ställa in om webbutiken ska acceptera enbart B2C-transaktioner (standardinställning), enbart B2B-transaktioner eller både B2C- och B2B-transaktioner.<br />  Obs! Efter att kundtyperna har ändrats måste webbläsarens sessionscache rensas för att betalningen ska kunna testas.',
    'TCKLARNA_B2C'                                      => 'Endast B2C-kunder',
    'TCKLARNA_B2B'                                      => 'Endast B2B-kunder',
    'TCKLARNA_B2B_B2C'                                  => 'Främst B2B-kunder, men även B2C-kunder',
    'TCKLARNA_B2C_B2B'                                  => 'Främst B2C-kunder, men även B2B-kunder',
    'TCKLARNA_NEED_SUPPORT'                             => 'Behöver ni hjälp med integrationen?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Kontakta Klarnas kundsupport för handlare',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Meddelanden på plats',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Här kan du konfigurera On-Site Messaging för användning med Klarna-modulen för OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Manus',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Credit Promotion – produktdetaljsida',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Kreditkampanj Varukorg',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Kampanj för toppremsan',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Kampanj i sidfoten',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Bannerreklam',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Vänligen infoga här det kodavsnitt för JavaScript-biblioteket som krävs för On-Site Messaging och som du hittar i Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Vänligen infoga placeringskoden här för att marknadsföra finansiering och avbetalningsköp via Credit Promotions på artikelsidan',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Vänligen infoga placeringskoden här för att marknadsföra finansiering och avbetalningsköp via Credit Promotions på översikten över varukorgen',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Vänligen infoga placeringskoden här för att marknadsföra allmän information och information om specifika betalningsmetoder på butikens startsida',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Vänligen infoga placeringskoden här för att visa dina tillgängliga Klarna-betalningsalternativ i webbutikens sidfot',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Vänligen infoga placeringskoden här för att lägga in en banner på din butiks startsida',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Vad är On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Kunderna är inte alltid medvetna om de olika kredit- och finansieringsmöjligheter som finns tillgängliga för dem innan de kommer till kassan. Finansieringsmöjligheter som presenteras i ett tidigt skede påverkar köpbeslutet. 

On-Site Messaging är enkelt och smidigt att integrera och erbjuder skräddarsydd information, allt från allmänna banners som lyfter fram ditt samarbete med Klarna och möjligheten till delbetalning till personliga kreditkampanjer på produkt- eller varukorgssidor.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Mer information om hur du kommer igång <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">hittar du här</a>:<br /><br /> 
Logga in på <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">återförsäljarportalen</a> för att generera din personliga JavaScript- och placeringskod. On-Site-Messaging aktiveras i din butik så snart JavaScript-koden har sparats och minst en placeringskod har angetts.<br /> 
Du kan inaktivera funktionen när som helst genom att ta bort koderna.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Återförsäljarportalen',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktivera Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktiv',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Byta ut knappnyckel',
    'TCKLARNA_IS_REPLACE'                               => 'Skapa en ny knapp ”Key”',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Du kan uppdatera Button Key om konfigurations- eller identifieringsuppgifterna kräver en ändring från Klarnas sida. Normalt sett kan du använda en Button Key så länge du vill efter att den har skapats.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Aktivera Klarna Instant Shopping här. Då skapas automatiskt en knapp som kan användas i webbutikens frontend.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Inställningar för knappdesign',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Välj mellan en knapp som helt är utformad i Klarnas stil och en mer neutral ”Light”-variant.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Välj om texten i taglinen under knappen ska vara ljus eller mörk.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Välj önskad text för knappen.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Förhandsgranskning av knappen',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Visa på artikelsidan',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Aktivera den här funktionen så att Klarna Instant Shopping-knappen visas på alla produktdetaljsidor i din webbutik.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Visa i varukorgsöversikten',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Aktivera den här funktionen så att Klarna Instant Shopping-knappen visas i varukorgsöversikten i din webbutik.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Ytterligare inställningar för Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Leveransadressen får skilja sig från fakturaadressen',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Om leverans till en annan leveransadress ska vara möjlig, aktivera den här knappen.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Födelsedatum är ett obligatoriskt fält',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Om ni vill göra det obligatoriskt att ange födelsedatum, aktivera den här knappen. Normalt sett är födelsedatumet inte ett obligatoriskt fält hos Klarna. Uppgiften är dock nödvändig för att möjliggöra köp på faktura eller delbetalning.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Nationellt ID-nummer är ett obligatoriskt fält',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Välj om det nationella identifikationsnumret ska vara ett obligatoriskt fält.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variation',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Typ',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefonnummer är ett obligatoriskt fält',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Välj om telefonnumret ska vara ett obligatoriskt fält.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Välj från listan vilket land som ska vara förinställt som standard när Klarna Instant Shopping öppnas, så länge kunden ännu inte har angett sitt land.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Ange här URL:en till dina allmänna villkor. Dessa kommer att länkas i Klarna Instant Shopping-popupfönstret. Du måste ange en giltig URL som börjar med https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Leveranssätt',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Kreditera hela beställningen',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Inga aktiva leveranssätt hittades',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Använd betalningsmetod: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kreditkort',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Autogiro',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Direktöverföring',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 räntefria delbetalningar',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Finansiering',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B-faktura (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktura',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Kortbetalning inom 30 dagar',
];
