<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Ελληνικά";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Έναρξη',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Γενικά',
    'TCKLARNA_CONFIGURATION'                            => 'Διαμόρφωση',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Ρυθμίσεις για τις πληρωμές μέσω Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Ρυθμίσεις σχεδιασμού',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Εξωτερικοί τρόποι πληρωμής',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Πρόσθετα στοιχεία εμπόρου',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Βασικές ρυθμίσεις',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Έκπτωση',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'Σε αυτή τη λειτουργία δεν υπάρχουν ρυθμίσεις.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Όλες οι ρυθμίσεις έχουν αποθηκευτεί.',

    'TCKLARNA_EASY'                                     => 'Είναι τόσο απλό να ενεργοποιήσετε το Klarna',
    'TCKLARNA_PHONE'                                    => 'Τηλέφωνο',
    'TCKLARNA_EMAIL'                                    => 'Ηλεκτρονικό ταχυδρομείο',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Ώρες λειτουργίας',
    'TCKLARNA_MONDAY'                                   => 'Δευτέρα',
    'TCKLARNA_TUESDAY'                                  => 'Τρίτη',
    'TCKLARNA_WEDNESDAY'                                => 'Τετάρτη',
    'TCKLARNA_THURSDAY'                                 => 'Πέμπτη',
    'TCKLARNA_FRIDAY'                                   => 'Παρασκευή',
    'TCKLARNA_SATURDAY'                                 => 'Σάββατο',
    'TCKLARNA_SUNDAY'                                   => 'Κυριακή',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Τα στοιχεία πρόσβασής σας για κάθε χώρα',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Προσθήκη στοιχείων πρόσβασης ανά χώρα',
    'TCKLARNA_COUNTRY'                                  => 'Χώρα',
    'TCKLARNA_MERCHANT_ID'                              => 'Όνομα χρήστη API',
    'TCKLARNA_PASSWORD'                                 => 'Κωδικός πρόσβασης API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'Αριθμός εμπόρου',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Προεπιλεγμένη χώρα του καταστήματος',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Η καταγραφή είναι ενεργή',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Να σταλούν τα αναλυτικά στοιχεία του προϊόντος στην Klarna;',
    'TCKLARNA_PRODUCT_URLS'                             => 'Διευθύνσεις URL προϊόντων',
    'TCKLARNA_IMAGE_URLS'                               => 'Διευθύνσεις URL εικόνων',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Ανώνυμη επεξεργασία',
    'TCKLARNA_ADD'                                      => 'Προσθήκη',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Πληρωμές μέσω Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Επιλογή τρόπου λειτουργίας της ενότητας Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'Με την Klarna, οι τελικοί πελάτες μπορούν να πληρώσουν με τρεις τρόπους: άμεση μεταφορά χρημάτων, αργότερα ή σε δόσεις. Αυτό δίνει τη δυνατότητα στους τελικούς πελάτες να δοκιμάσουν πρώτα τα προϊόντα και να πληρώσουν μόνο όσα επιθυμούν να κρατήσουν, να χρηματοδοτήσουν τις αγορές τους στο κατάστημα ή να πληρώσουν αμέσως. Μπορείτε να ενεργοποιήσετε την πληρωμή με τιμολόγιο, την αγορά με δόσεις, την άμεση μεταφορά χρημάτων ή την άμεση χρέωση μέσω μιας ενσωμάτωσης, ενώ χάρη στη λύση iFrame της Klarna, αυτές οι επιλογές είναι πάντα ενημερωμένες τόσο από νομική όσο και από περιεχομενική άποψη.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Οι πιο δημοφιλείς τρόποι πληρωμής. Ασφαλείς και εύκολοι στην ενσωμάτωση.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Καλώς ήρθατε στις ρυθμίσεις διαμόρφωσης της Klarna Payments. Εδώ θα βρείτε όλα όσα χρειάζεστε για την ενεργοποίηση. Επιλέξτε τις υποεπιλογές της Klarna στην αριστερή γραμμή για να ολοκληρώσετε τη ρύθμιση της ενότητας.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Δημιουργία λογαριασμού πελάτη στο OXID eShop',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Εγγραφή στο ενημερωτικό δελτίο',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Δημιουργία λογαριασμού πελάτη ΚΑΙ εγγραφή στο ενημερωτικό δελτίο',
    'TCKLARNA_NO_CHECKBOX'                              => 'Να μην εμφανίζεται το πλαίσιο επιλογής',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Να εμφανίζεται στην αρχική σελίδα του καταστήματος;',
    'TCKLARNA_BANNER_SRC'                               => 'Πηγή του banner της Klarna',
    'TCKLARNA_FOOTER'                                   => 'Υποσέλιδο',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Τι πρέπει να εμφανίζεται στο υποσέλιδο;',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Εμφάνιση των τρόπων πληρωμής',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Λογότυπο της Klarna',
    'TCKLARNA_DESIGN'                                   => 'Σχεδιασμός',
    'TCKLARNA_LONG_VERSION'                             => 'Πλήρης έκδοση:',
    'TCKLARNA_SHORT_VERSION'                            => 'Συνοπτική έκδοση:',
    'TCKLARNA_WHITE'                                    => 'Λευκό:',
    'TCKLARNA_BLACK'                                    => 'Μαύρο:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Σελίδα λεπτομερειών προϊόντος και καλάθι αγορών',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Να εμφανιστεί το widget της μεθόδου πληρωμής Klarna;',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Στη σελίδα λεπτομερειών του προϊόντος',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Στη σελίδα του καλαθιού αγορών',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Να εμφανιστεί το κουμπί «Αγορά τώρα»;',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Επιλογές σχεδιασμού πληρωμών Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Ρυθμίσεις χρωμάτων:',
    'TCKLARNA_BORDER'                                   => 'Σύνορα:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Επιλεγμένο όριο:',
    'TCKLARNA_BUTTON'                                   => 'Κουμπί:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Κείμενο κουμπιού:',
    'TCKLARNA_CHECKBOX'                                 => 'Πλαίσιο επιλογής:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Επιλογή πλαισίου:',
    'TCKLARNA_DETAILS'                                  => 'Λεπτομέρειες:',
    'TCKLARNA_HEADER'                                   => 'Επικεφαλίδα:',
    'TCKLARNA_LINK'                                     => 'Σύνδεσμος:',
    'TCKLARNA_TEXT'                                     => 'Κείμενο:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Συνέχεια κειμένου:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Ρύθμιση ακτίνας:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Ακτίνα περιγράμματος:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Η διεύθυνση παράδοσης μπορεί να διαφέρει από τη διεύθυνση τιμολόγησης',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Ο αριθμός τηλεφώνου είναι υποχρεωτικό πεδίο',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Η ημερομηνία γέννησης είναι υποχρεωτικό πεδίο',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Ενεργοποίηση παράδοσης σε σημείο παραλαβής της DHL',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Ενεργοποίηση της λειτουργίας προπλήρωσης',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Ενεργοποίηση της υπενθύμισης για την προπλήρωση',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Το πεδίο «Τίτλος» είναι υποχρεωτικό',
    'TCKLARNA_SET_TAC_URI'                              => 'Διεύθυνση URL των Όρων Χρήσης σας',
    'TCKLARNA_SET_CANCEL_URI'                           => 'Διεύθυνση URL σχετικά με το δικαίωμα υπαναχώρησης',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Λεπτομέρειες αποστολής',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Χωρίς επικύρωση',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Εκτέλεση επικύρωσης, αλλά αγνοώντας τα timeouts',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Απαιτείται επιτυχής επικύρωση',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Επικύρωση παραγγελίας',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Παρακαλούμε επιλέξτε τις επιλογές πληρωμής της Klarna που θέλετε να προσφέρετε στους πελάτες σας:',
    'TCKLARNA_PAY_LATER'                                => 'Τιμολόγιο',
    'TCKLARNA_PAY_LATER.'                               => 'Τιμολόγιο.',
    'TCKLARNA_PAY_LATER_START'                          => 'Για πελάτες που επιθυμούν να αγοράσουν τώρα και να πληρώσουν αργότερα. Με απόλυτη ευκολία σε 14, 21 ή 28 ημέρες, ανάλογα με την αγορά.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Η επιλογή «Τιμολόγιο» καθιστά τη διαδικασία πληρωμής εύκολη και γρήγορη για τους πελάτες, χωρίς να χρειάζεται να εισάγουν προσωπικά στοιχεία ή περίπλοκους αριθμούς. Ο πελάτης μπορεί να επιλέξει μεταξύ τιμολογίου και πληρωμής τον μήνα Χ.',
    'TCKLARNA_SLICE_IT'                                 => 'Αγορά με δόσεις.',
    'TCKLARNA_SLICE_IT.'                                => 'Πληρωμή σε δόσεις.',
    'TCKLARNA_SLICE_IT_START'                           => 'Αυξήστε την αγοραστική δύναμη των πελατών σας μέσω της πληρωμής σε δόσεις. Οι πελάτες μπορούν να εξοφλήσουν τις αγορές τους με σταθερές μηνιαίες δόσεις σε διάστημα από 6 έως 36 μήνες.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Μέσω της «αγοράς με δόσεις», οι πελάτες μπορούν να κατανέμουν το ποσό της αγοράς σε δόσεις με χαμηλό επιτόκιο. Αυτό αυξάνει το επενδυτικό όριο και την αγοραστική δύναμη. Η μοναδική διαδικασία έγκρισης πίστωσης της Klarna διαρκεί μόνο λίγα δευτερόλεπτα και απαιτεί ελάχιστη εισαγωγή δεδομένων.',
    'TCKLARNA_PAY_NOW'                                  => 'Άμεση πληρωμή',
    'TCKLARNA_PAY_NOW.'                                 => 'Πληρώστε αμέσως.',
    'TCKLARNA_PAY_NOW_START'                            => 'Εύκολη και γρήγορη άμεση πληρωμή με τη λειτουργία «Άμεση πληρωμή» της Klarna. Στη Γερμανία, το χαρτοφυλάκιο πρέπει οπωσδήποτε να περιλαμβάνει τις επιλογές Sofortüberweisung, πιστωτική κάρτα και άμεση χρέωση.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Οι πελάτες που επιθυμούν να εξοφλήσουν αμέσως το συνολικό ποσό κατά την ολοκλήρωση της παραγγελίας μπορούν να χρησιμοποιήσουν την επιλογή «Άμεση πληρωμή». Μπορούν να επιλέξουν μεταξύ πιστωτικής κάρτας, χρέωσης μέσω τραπεζικού λογαριασμού και άμεσης τραπεζικής μεταφοράς.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Οδηγός για τον τρόπο <br />ενεργοποίησης της Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'Στο OXID Backend, κάντε κλικ στη νέα επιλογή μενού «Klarna», στην υποκατηγορία «Γενικά» και, στη συνέχεια, επιλέξτε το προϊόν Klarna που επιθυμείτε.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Εισάγετε τα στοιχεία πρόσβασής σας (όνομα χρήστη και κωδικός πρόσβασης) και ορίστε τις τυπικές για το OXID αντιστοιχίσεις των τρόπων πληρωμής στις ενότητες «Ρυθμίσεις καταστήματος» &gt; «Τρόποι πληρωμής» καθώς και &gt; «Τρόποι αποστολής».',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Αποθηκεύστε τις αλλαγές.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Είστε πλέον συνδεδεμένοι και μπορείτε να αρχίσετε να πραγματοποιείτε πωλήσεις μέσω της Klarna.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Υποστήριξη εμπόρων',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Εδώ μπορείτε να ρυθμίσετε αν θα πρέπει να μεταφέρονται τυχόν επιπλέον δεδομένα εμπόρου (Extra Merchant Data) στην Klarna. 
Για μια λεπτομερή περιγραφή των διαφόρων ρυθμίσεων, παρακαλούμε ανατρέξτε στις συμβουλές χρήσης 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, διαβάστε το <a class="cl-pink" href="%s" target="_blank">εγχειρίδιο</a> 
ή επικοινωνήστε με την Υποστήριξη Ενσωμάτωσης της Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Εδώ μπορείτε να διαμορφώσετε τις ρυθμίσεις εμφάνισης για χρήση με το module της Klarna για το OXID eShop. 
Για μια λεπτομερή περιγραφή των διαφόρων ρυθμίσεων, ανατρέξτε στις συμβουλές χρήσης 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, διαβάστε το <a class="cl-pink" href="%s" target="_blank">εγχειρίδιο</a> 
ή επικοινωνήστε με την Υποστήριξη Ενσωμάτωσης της Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Εδώ μπορείτε να κάνετε τις επιλογές για τις πληρωμές μέσω Klarna και να ορίσετε τις γενικές ρυθμίσεις. 
Για μια λεπτομερή περιγραφή των διαφόρων ρυθμίσεων, ανατρέξτε στις συμβουλές χρήσης 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, διαβάστε το <a class="cl-pink" href="%s" target="_blank">εγχειρίδιο</a> 
ή επικοινωνήστε με την Υποστήριξη Ενσωμάτωσης της Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Σε αυτή τη σελίδα μπορείτε να επιλέξετε ποιες υπηρεσίες πληρωμών της Klarna θέλετε να προσφέρετε. 
Για μια λεπτομερή περιγραφή των διαφόρων ρυθμίσεων, ανατρέξτε στις συμβουλές χρήσης 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, διαβάστε το <a class="cl-pink" href="%s" target="_blank">εγχειρίδιο</a> 
ή επικοινωνήστε με την Υποστήριξη Ενσωμάτωσης της Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Τρόπος πληρωμής',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Εξωτερικός τρόπος πληρωμής',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI εικόνας για εξωτερική μέθοδο πληρωμής',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Μέγεθος εικόνας: 69x24 εικονοστοιχεία',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Μέγεθος εικόνας: 276x48 εικονοστοιχεία',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Μπορείτε να δείτε εδώ το εγχειρίδιο χρήστη για το module Klarna για το OXID eShop.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Εγχειρίδιο χρήστη',

    'TCKLARNA_CHOOSE'                                   => 'Επιλογή',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Πληροφορίες λογαριασμού πελάτη',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Πλήρες ιστορικό πληρωμών',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Πεδίο διαβίβασης',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Επιλογή τύπου τρόπου πληρωμής:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Ποιες παραγγελίες πρέπει να συμπεριληφθούν στο «Ιστορικό πληρωμών» (Payment history full);',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Όλες οι παραγγελίες θεωρούνται πληρωμένες, ανεξάρτητα από την ημερομηνία oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Να διαβιβάζονται μόνο οι παραγγελίες για τις οποίες έχει οριστεί ημερομηνία oxpaid· να αγνοούνται οι μη πληρωμένες παραγγελίες',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Να αγνοηθούν όλες οι παραγγελίες που πραγματοποιήθηκαν με αυτόν τον τρόπο πληρωμής',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Άλλη επιλογή πληρωμής',
    'TCKLARNA_DIRECT_BANKING'                           => 'Άμεση μεταφορά χρημάτων',
    'TCKLARNA_CARD'                                     => 'Χάρτης',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Επιλέξτε μεταξύ «Playground» (δοκιμαστική λειτουργία) και «Live» (παραγωγική λειτουργία). Ενεργοποιήστε την παραγωγική λειτουργία μόνο αφού ολοκληρωθούν με επιτυχία οι δοκιμές ενσωμάτωσης και κατόπιν συνεννόησης με τον υπεύθυνο ενσωμάτωσης της Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Παρακαλούμε εισάγετε εδώ τα στοιχεία πρόσβασης στο API της Klarna. Τα έχετε λάβει στο email καλωσορίσματος από την Klarna. Αυτό το όνομα χρήστη και ο κωδικός πρόσβασης ισχύουν παγκοσμίως για όλες τις χώρες. Μόνο στην περίπτωση που έχετε λάβει διαφορετικά στοιχεία πρόσβασης για διαφορετικές χώρες, μπορείτε να τα προσθέσετε παρακάτω.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Εισάγετε εδώ τον κωδικό πρόσβασής σας, ο οποίος αντιστοιχεί στο όνομα χρήστη API που χρησιμοποιείτε. Έχετε λάβει αυτόν τον κωδικό πρόσβασης στο email καλωσορίσματος από την Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Παρακαλώ εισάγετε εδώ τον αριθμό Klarna Merchant ID σας. Τον έχετε λάβει στο email καλωσορίσματος από την Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Επιλέξτε από τη λίστα στα αριστερά τη χώρα για την οποία έχετε λάβει τα ειδικά για τη χώρα στοιχεία πρόσβασης από την Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Παρακαλώ εισάγετε εδώ το αντίστοιχο όνομα χρήστη για αυτή τη χώρα.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Παρακαλώ εισάγετε εδώ τον αντίστοιχο κωδικό πρόσβασης για αυτή τη χώρα.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Παρακαλώ εισάγετε εδώ τον αντίστοιχο κωδικό εμπόρου (Merchant ID) για τη συγκεκριμένη χώρα.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Ενεργοποιεί τη λειτουργία καταγραφής, ώστε όλη η επικοινωνία μέσω API με την Klarna να καταγράφεται στον πίνακα tcklarna_logs της βάσης δεδομένων MySQL. Αυτό μπορεί να είναι χρήσιμο κατά την ανάλυση ή τον εντοπισμό σφαλμάτων. Σε περιβάλλον παραγωγής, η λειτουργία αυτή θα πρέπει να είναι απενεργοποιημένη, καθώς διαφορετικά ενδέχεται να συσσωρευτούν μεγάλοι όγκοι αρχείων καταγραφής και να αποθηκευτούν ευαίσθητα δεδομένα.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Στείλτε στην Klarna τις διευθύνσεις URL των σελίδων λεπτομερειών των προϊόντων που βρίσκονται στο καλάθι αγορών των πελατών σας, ώστε η Klarna να μπορεί αργότερα να δημιουργήσει συνδέσμους προς τα προϊόντα σας από το Portal της Klarna.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Στείλτε στην Klarna τις διευθύνσεις URL των εικόνων των προϊόντων που βρίσκονται στο καλάθι αγορών των πελατών σας, ώστε η Klarna να μπορεί να τις εμφανίσει στο Klarna Portal.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Ενεργοποιήστε την ανωνυμοποίηση για να αποκρύψετε από την Klarna τις ονομασίες των προϊόντων που βρίσκονται στο καλάθι αγορών των πελατών σας. Αυτό συνιστάται, για παράδειγμα, για τα διαδικτυακά φαρμακεία, αλλά θα πρέπει να γίνεται μόνο κατόπιν συνεννόησης με τον υπεύθυνο ενσωμάτωσης της Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Εάν επιθυμείτε να καταστεί δυνατή η παράδοση σε διαφορετική διεύθυνση παράδοσης, ενεργοποιήστε αυτό το κουμπί.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Εάν επιθυμείτε να καταστήσετε υποχρεωτική την καταχώριση αριθμού τηλεφώνου, ενεργοποιήστε αυτό το κουμπί. Κανονικά, για την Klarna ο αριθμός τηλεφώνου δεν αποτελεί υποχρεωτικό πεδίο.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Εάν επιθυμείτε να καταστήσετε υποχρεωτική την καταχώριση της ημερομηνίας γέννησης, ενεργοποιήστε αυτό το κουμπί. Κανονικά, για την Klarna η ημερομηνία γέννησης δεν αποτελεί υποχρεωτικό πεδίο. Ωστόσο, η καταχώρισή της είναι απαραίτητη για να καταστεί δυνατή η αγορά με πληρωμή μέσω λογαριασμού ή η πληρωμή σε δόσεις.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'Δεν έχει υλοποιηθεί προς το παρόν',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Εισάγετε εδώ τη διεύθυνση URL της ιστοσελίδας σας που περιέχει την ενημέρωση σχετικά με το δικαίωμα υπαναχώρησης. Η διεύθυνση URL πρέπει να ξεκινά με https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Αυτές οι πληροφορίες αποστολής εμφανίζονται στον πελάτη στη σελίδα επιβεβαίωσης μετά την ολοκλήρωση της παραγγελίας.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Αντιστοιχίστε αυτόν τον εξωτερικό τρόπο πληρωμής σε έναν από τους προκαθορισμένους τρόπους πληρωμής',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Παρακαλώ, αναφέρετε μια διεύθυνση URL για όλες τις γλώσσες',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Παρακαλώ εισάγετε μια έγκυρη διεύθυνση URL που να ξεκινά με https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Αυτός ο διακόπτης ενεργοποιεί τη διαβίβαση πρόσθετων δεδομένων στην Klarna, στην περίπτωση αυτή των πληροφοριών λογαριασμού πελάτη, οι οποίες περιλαμβάνουν την ημερομηνία εγγραφής του λογαριασμού πελάτη και την ημερομηνία της τελευταίας τροποποίησής του.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Αυτός ο διακόπτης ενεργοποιεί τη διαβίβαση πρόσθετων δεδομένων στην Klarna, στην περίπτωση αυτή το «Payment History Full», το οποίο περιλαμβάνει τις μέχρι τώρα αγορές του πελάτη.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Παρακαλώ, προσδιορίστε σε ποιον τύπο πληρωμής αντιστοιχεί αυτή η μέθοδος πληρωμής.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Παρακαλώ καθορίστε εδώ αν και, ενδεχομένως, ποιες παραγγελίες με αυτόν τον τρόπο πληρωμής πρέπει να περιλαμβάνονται κατά τη μεταφορά του ιστορικού παραγγελιών του πελάτη. Η εξάρτηση του πεδίου OXORDER.OXPAID καθορίζει αν θα ληφθούν υπόψη μόνο οι πληρωμένες παραγγελίες ή όλες οι παραγγελίες.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Υπάρχει η δυνατότητα να διαβιβάσετε οποιαδήποτε άλλα δεδομένα στην Klarna μέσω ενός πεδίου «pass-through». Για να χρησιμοποιήσετε αυτή τη λειτουργία, πρέπει να εγκαταστήσετε ένα αντίστοιχο module στο OXID eShop, το οποίο θα καταχωρεί τα επιθυμητά δεδομένα στο πεδίο «pass-through». Μπορείτε να βρείτε σχετικές οδηγίες στην τεκμηρίωση για προγραμματιστές.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Με αυτό το κουμπί ενεργοποιείτε ένα banner της Klarna στην αρχική σελίδα του καταστήματός σας στο προεπιλεγμένο θέμα Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Εδώ μπορείτε να εισάγετε την ετικέτα script για την ενσωμάτωση του banner. Στο portal banner της Klarna θα βρείτε, αν χρειαστεί, και άλλα banner για να επιλέξετε.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Με αυτό το κουμπί ενεργοποιείτε την εμφάνιση της μεθόδου πληρωμής Klarna στο υποσέλιδο του καταστήματός σας στο προεπιλεγμένο θέμα Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Με αυτό το κουμπί μπορείτε να προσθέσετε το λογότυπο της Klarna στο υποσέλιδο του καταστήματός σας στο προεπιλεγμένο θέμα Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Αυτός ο διακόπτης προσθέτει ένα κουμπί «Αγορά τώρα» στις σελίδες λεπτομερειών προϊόντων του καταστήματός σας στο προεπιλεγμένο θέμα Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Χρώμα του πλαισίου που εμφανίζεται στο περιβάλλον χρήστη του ηλεκτρονικού καταστήματος μετά την επιλογή του τρόπου πληρωμής Klarna, σε περίπτωση που υπάρχουν διάφορες υποεπιλογές.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Χρώμα του πλαισίου που εμφανίζεται στο περιβάλλον χρήστη του ηλεκτρονικού καταστήματος μετά την επιλογή του τρόπου πληρωμής Klarna, σε περίπτωση που υπάρχουν διάφορες υποεπιλογές. Αυτή η χρωματική τιμή χρησιμοποιείται για την επισήμανση της υποεπιλογής που είναι ενεργή εκείνη τη στιγμή.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Αυτή η ρύθμιση δεν έχει ακόμη καμία επίδραση κατά τη στιγμή της δημοσίευσης αυτού του ενότητας.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Αυτή η ρύθμιση δεν έχει ακόμη καμία επίδραση κατά τη στιγμή της δημοσίευσης αυτού του ενότητας.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Χρώμα φόντου των κουμπιών επιλογής που εμφανίζονται στο περιβάλλον χρήστη του ηλεκτρονικού καταστήματος, όταν υπάρχουν διάφορες υποεπιλογές μετά την επιλογή του τρόπου πληρωμής «Klarna»',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Αυτή η ρύθμιση δεν έχει ακόμη καμία επίδραση κατά τη στιγμή της δημοσίευσης αυτού του ενότητας.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Χρώμα των σημείων κουκκίδων κατά την εμφάνιση των λεπτομερειών πληρωμής στη σελίδα επιλογής τρόπου πληρωμής.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Αυτή η ρύθμιση δεν έχει ακόμη καμία επίδραση κατά τη στιγμή της δημοσίευσης αυτού του ενότητας.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Χρώμα των συνδέσμων στην αναλυτική περιγραφή των τρόπων πληρωμής στη σελίδα επιλογής τρόπων πληρωμής.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Χρώμα κειμένου της αναλυτικής περιγραφής των τρόπων πληρωμής στη σελίδα επιλογής τρόπων πληρωμής.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Εναλλακτικό χρώμα κειμένου για την αναλυτική περιγραφή των τρόπων πληρωμής στη σελίδα επιλογής τρόπων πληρωμής.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Με αυτή τη ρύθμιση μπορείτε να καθορίσετε τον βαθμό στρογγυλοποίησης του πλαισίου που εμφανίζεται στο περιβάλλον χρήστη του καταστήματος, ανάλογα με τις διάφορες υπο-επιλογές που είναι διαθέσιμες μετά την επιλογή του τρόπου πληρωμής Klarna.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Αυτή η καρτέλα αφορά μόνο τις παραγγελίες μέσω της Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Καταγραφή ολόκληρης της παραγγελίας',
    'KLARNA_CAPTURE_ID'                                 => 'Αριθμός συναλλαγής',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Αναφορά Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Ποσό χρέωσης',
    'KLARNA_CAPTURE_DATE'                               => 'Χρεώθηκε στις',
    'KLARNA_REFUND_AMOUNT'                              => 'Ποσό επιστροφής',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Επιστροφή χρημάτων – Επεξήγηση',
    'KLARNA_REFUND_DATE'                                => 'Αντικαταστάθηκε στις',
    'KLARNA_CAPTURES'                                   => 'Χρεώσεις',
    'KLARNA_REFUNDS'                                    => 'Επιστροφές χρημάτων',
    'KLARNA_CANCEL_ORDER'                               => 'Ακύρωση παραγγελίας',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Η παραγγελία ακυρώθηκε. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Πρόσβαση σε αυτή την παραγγελία στο portal της Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Προσοχή!</strong> Τα στοιχεία αυτής της παραγγελίας διαφέρουν από τα στοιχεία που έχουν καταχωρηθεί στην Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Προσοχή! Λόγω της τρέχουσας κατάστασης της παραγγελίας, αυτή η τροποποίηση δεν μπορεί να διαβιβαστεί στην Klarna. Εάν χρειάζεται, πραγματοποιήστε την αντίστοιχη τροποποίηση χειροκίνητα απευθείας στο Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Προσοχή! Η Klarna δεν μπόρεσε να επεξεργαστεί τις τελευταίες αλλαγές που πραγματοποιήσατε σε αυτή την παραγγελία (λόγος: %s). Παρακαλούμε να ακυρώσετε τις πρόσφατες αλλαγές σας στο OXID eShop ή, εάν είναι απαραίτητο, να πραγματοποιήσετε τη σχετική προσαρμογή χειροκίνητα στο Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Μη επιτρεπόμενο αίτημα. Ελέγξτε τις ρυθμίσεις της ενότητας Klarna, καθώς και το Merchant ID και τον αντίστοιχο κωδικό πρόσβασης',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Η παραγγελία αυτή δεν εντοπίστηκε στο σύστημα της Klarna. Ως εκ τούτου, οι αλλαγές στα στοιχεία της παραγγελίας δεν θα μεταφερθούν στην Klarna.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Λανθασμένα στοιχεία σύνδεσης!</strong> Αυτή η παραγγελία υποβλήθηκε χρησιμοποιώντας τον κωδικό εμπόρου <strong>%s</strong>. Ο κωδικός εμπόρου που έχει ρυθμιστεί επί του παρόντος για το <strong>%s</strong> είναι <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Όνομα προϊόντος',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Ανώνυμος τίτλος προϊόντος:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Η πληρωμή διεκπεραιώνεται μέσω του συνεργάτη μας, της Klarna. Παρακαλούμε να λάβετε υπόψη τις πληροφορίες πληρωμής που σας έχει αποστείλει η Klarna. Μπορείτε να διαχειριστείτε όλες τις αγορές σας μέσω του Klarna.com ή της εφαρμογής της Klarna και μάλιστα να πληρώσετε με ένα μόνο κλικ.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Κουπόνι έκπτωσης',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Συσκευασία δώρου',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Ευχετήρια κάρτα',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Σοβαρό σφάλμα: Η καταχώριση μιας έγκυρης διεύθυνσης $this-&gt;sSSLShopURL που προστατεύεται με SSL (https) στο αρχείο config.inc.php του καταστήματός σας είναι υποχρεωτική, εάν θέλετε να ενεργοποιήσετε το %s!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Λανθασμένα στοιχεία σύνδεσης!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Το ποσό χρεώθηκε με επιτυχία.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Δεν ήταν δυνατή η χρέωση της παραγγελίας, καθώς είχε ήδη ακυρωθεί.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Εισάγετε εδώ τη συμβολοσειρά που θα αποσταλεί στην Klarna αντί του πραγματικού τίτλου του προϊόντος.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Οι αλλαγές που έχετε κάνει σε αυτή την παραγγελία δεν θα μεταφερθούν στην Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Εγχειρίδιο χρήστη',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Εγγραφή',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Μάθετε περισσότερα',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Υποστηριζόμενοι τύποι πελατών',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Εδώ μπορείτε να ορίσετε αν το ηλεκτρονικό κατάστημα θα δέχεται αποκλειστικά συναλλαγές B2C (προεπιλεγμένη ρύθμιση), μόνο συναλλαγές B2B ή τόσο συναλλαγές B2C όσο και B2B.<br />  Σημείωση: Μετά την αλλαγή των τύπων πελατών, πρέπει να διαγραφεί η προσωρινή μνήμη περιόδου λειτουργίας του προγράμματος περιήγησης, ώστε να είναι δυνατή η δοκιμή της πληρωμής.',
    'TCKLARNA_B2C'                                      => 'Μόνο πελάτες B2C',
    'TCKLARNA_B2B'                                      => 'Μόνο πελάτες B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Κυρίως πελάτες B2B, αλλά και πελάτες B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Κυρίως πελάτες B2C, αλλά και πελάτες B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Χρειάζεστε βοήθεια με την ενσωμάτωση;',
    'TCKLARNA_REACH_SUPPORT'                            => 'Επικοινωνήστε με την Υποστήριξη Εμπόρων της Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Ανταλλαγή μηνυμάτων εντός του ιστότοπου',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Εδώ μπορείτε να διαμορφώσετε το On-Site Messaging για χρήση με το module της Klarna για το OXID eShop.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Σενάριο',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Σελίδα λεπτομερειών προϊόντος «Credit Promotion»',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Προώθηση πιστώσεων Καλάθι αγορών',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Προωθητική ενέργεια «Top-strip»',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Προώθηση στο υποσέλιδο',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Προωθητική καμπάνια με banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Παρακαλώ εισάγετε εδώ το απόσπασμα κώδικα της βιβλιοθήκης JavaScript που απαιτείται για το On-Site Messaging και το οποίο μπορείτε να βρείτε στο Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Παρακαλώ εισάγετε εδώ την ετικέτα «Placement», για να προωθήσετε τη χρηματοδότηση και την αγορά με δόσεις μέσω της Credit Promotions στη σελίδα λεπτομερειών του προϊόντος',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Παρακαλώ εισάγετε εδώ την ετικέτα τοποθέτησης, για να προωθήσετε τη χρηματοδότηση και την αγορά με δόσεις μέσω της Credit Promotions στη σελίδα σύνοψης του καλαθιού αγορών',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Παρακαλώ εισάγετε εδώ την ετικέτα «Placement» για να προβάλετε γενικές πληροφορίες και πληροφορίες σχετικά με συγκεκριμένους τρόπους πληρωμής στην αρχική σελίδα του καταστήματος',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Παρακαλώ εισάγετε εδώ την ετικέτα τοποθέτησης για να εμφανίσετε τους διαθέσιμους τρόπους πληρωμής της Klarna στο υποσέλιδο του καταστήματος',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Παρακαλώ εισάγετε εδώ την ετικέτα τοποθέτησης για να προσθέσετε ένα banner στην αρχική σελίδα του καταστήματός σας',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Τι είναι το On-Site Messaging;',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Οι πελάτες δεν γνωρίζουν πάντα τις διάφορες επιλογές πίστωσης και χρηματοδότησης που έχουν στη διάθεσή τους, πριν φτάσουν στο ταμείο. Οι επιλογές χρηματοδότησης που διατίθενται έγκαιρα επηρεάζουν την απόφαση αγοράς. 

Το On-Site Messaging ενσωματώνεται εύκολα και χωρίς προβλήματα και προσφέρει εξατομικευμένες πληροφορίες, που κυμαίνονται από γενικά banner σχετικά με την προώθηση της συνεργασίας σας με την Klarna και τη δυνατότητα πληρωμής σε δόσεις, έως εξατομικευμένες προσφορές πίστωσης στις σελίδες προϊόντων ή στο καλάθι αγορών.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Περισσότερες πληροφορίες για τα πρώτα βήματα <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">θα βρείτε εδώ</a>:<br /><br /> 
Συνδεθείτε στην <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">πύλη</a> <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">εμπόρων</a> για να δημιουργήσετε τον προσωπικό σας κωδικό JavaScript και τον κωδικό τοποθέτησης. Η λειτουργία «On-Site-Messaging» θα ενεργοποιηθεί στο κατάστημά σας μόλις αποθηκευτεί ο κώδικας JavaScript και εισαχθεί τουλάχιστον ένας κώδικας τοποθέτησης.<br /> 
Μπορείτε να την απενεργοποιήσετε ανά πάσα στιγμή, αφαιρώντας ξανά τους κωδικούς.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Πύλη εμπόρων',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Ενεργοποίηση της υπηρεσίας Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Ενεργό',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Αντικατάσταση του πλήκτρου «Key»',
    'TCKLARNA_IS_REPLACE'                               => 'Δημιουργία νέου κουμπιού «Key»',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Μπορείτε να ενημερώσετε το Button Key, εφόσον απαιτείται αλλαγή στα στοιχεία διαμόρφωσης ή ταυτοποίησης από την πλευρά της Klarna. Συνήθως, μπορείτε να χρησιμοποιείτε ένα Button Key που έχει δημιουργηθεί μία φορά για όσο διάστημα επιθυμείτε.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Ενεργοποιήστε εδώ το Klarna Instant Shopping. Με αυτόν τον τρόπο δημιουργείται αυτόματα ένα κουμπί για χρήση στο περιβάλλον εργασίας του ηλεκτρονικού καταστήματος.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Ρυθμίσεις εμφάνισης κουμπιών',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Παρακαλώ επιλέξτε ανάμεσα σε ένα κουμπί με πλήρη επωνυμία «Klarna» και μια πιο ουδέτερη έκδοση «Light».',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Παρακαλώ επιλέξτε αν το χρώμα της γραμματοσειράς του σλόγκαν κάτω από το κουμπί θα είναι ανοιχτό ή σκούρο.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Παρακαλώ επιλέξτε την επιθυμητή επιγραφή για το κουμπί.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Προεπισκόπηση του κουμπιού',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Εμφάνιση στη σελίδα λεπτομερειών προϊόντος',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Ενεργοποιήστε αυτή τη λειτουργία, ώστε το κουμπί «Klarna Instant Shopping» να εμφανίζεται σε όλες τις σελίδες λεπτομερειών προϊόντων στο κατάστημά σας.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Εμφάνιση στη σύνοψη του καλαθιού αγορών',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Ενεργοποιήστε αυτή τη λειτουργία, ώστε να εμφανίζεται το κουμπί «Klarna Instant Shopping» στη σελίδα με τη σύνοψη του καλαθιού αγορών στο κατάστημά σας.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Περαιτέρω ρυθμίσεις για το Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Η διεύθυνση παράδοσης μπορεί να διαφέρει από τη διεύθυνση τιμολόγησης',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Εάν επιθυμείτε να καταστεί δυνατή η παράδοση σε διαφορετική διεύθυνση παράδοσης, ενεργοποιήστε αυτό το κουμπί.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Η ημερομηνία γέννησης είναι υποχρεωτικό πεδίο',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Εάν επιθυμείτε να καταστήσετε υποχρεωτική την καταχώριση της ημερομηνίας γέννησης, ενεργοποιήστε αυτό το κουμπί. Κανονικά, για την Klarna η ημερομηνία γέννησης δεν αποτελεί υποχρεωτικό πεδίο. Ωστόσο, η καταχώρισή της είναι απαραίτητη για να καταστεί δυνατή η αγορά με πληρωμή μέσω λογαριασμού ή η πληρωμή σε δόσεις.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Ο εθνικός αριθμός ταυτότητας ως υποχρεωτικό πεδίο',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Παρακαλώ επιλέξτε αν ο εθνικός αριθμός ταυτότητας θα πρέπει να είναι υποχρεωτικό πεδίο.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Παραλλαγή',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Σλόγκαν',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Τύπος',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Ο αριθμός τηλεφώνου είναι υποχρεωτικό πεδίο',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Παρακαλώ επιλέξτε αν ο αριθμός τηλεφώνου θα είναι υποχρεωτικό πεδίο.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Παρακαλώ επιλέξτε από τη λίστα ποια χώρα θα πρέπει να ορίζεται ως προεπιλογή κατά την πρόσβαση στο Klarna Instant Shopping, εφόσον ο πελάτης δεν έχει ακόμη δηλώσει τη χώρα του.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Εισάγετε εδώ τη διεύθυνση URL των Γενικών Όρων και Προϋποθέσεων σας. Θα εμφανιστεί σύνδεσμος προς αυτούς στο αναδυόμενο παράθυρο του Klarna Instant Shopping. Πρέπει να εισαχθεί μια έγκυρη διεύθυνση URL που να ξεκινά με https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Τρόποι αποστολής',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Πιστώστε ολόκληρη την παραγγελία',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Δεν βρέθηκαν ενεργοί τρόποι αποστολής',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Τρόπος πληρωμής που χρησιμοποιήθηκε: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Πιστωτική κάρτα',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Αυτόματη χρέωση',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Άμεση μεταφορά χρημάτων',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 άτοκες δόσεις',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Χρηματοδότηση',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'Τιμολόγιο B2B (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Τιμολόγιο',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Πληρωμή με κάρτα σε 30 ημέρες',
];
