<?php
/**
 * Copyright 2018 Klarna AB
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

$sLangName = "Slovenčina";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = [
    'charset'                                           => 'UTF-8',

    'TCKLARNA_KLARNAMAINMENU'                           => 'Klarna',
    'TCKLARNA_START'                                    => 'Začať',
    'TCKLARNA_GENERAL_SETTINGS'                         => 'Všeobecne',
    'TCKLARNA_CONFIGURATION'                            => 'Konfigurácia',
    'TCKLARNA_CONFIGURATION_KP'                         => 'Konfigurácia pre platby cez Klarna',
    'TCKLARNA_KLARNADESIGN'                             => 'Nastavenia dizajnu',
    'TCKLARNA_EXTERNAL_PAYMENTS'                        => 'Externé spôsoby platby',
    'TCKLARNA_EXTRA_MERCHANT_DATA'                      => 'Ďalšie údaje o predajcovi',
    'TCKLARNA_BASIC_SETTINGS'                           => 'Základné nastavenia',
    'TCKLARNA_DISCOUNT_TITLE'                           => 'Zľava',

    'tcklarna_tbclklarna_orders'                        => 'Klarna',
    'TCKLARNA_NO_OPTIONS_MODE'                          => 'V tomto režime nie sú k dispozícii žiadne nastavenia.',
    'TCKLARNA_CHANGES_SAVED'                            => 'Všetky nastavenia boli uložené.',

    'TCKLARNA_EASY'                                     => 'Aktivácia služby Klarna je naozaj taká jednoduchá',
    'TCKLARNA_PHONE'                                    => 'Telefón',
    'TCKLARNA_EMAIL'                                    => 'E-mail',
    'TCKLARNA_BUSINESS_HOURS'                           => 'Otváracie hodiny',
    'TCKLARNA_MONDAY'                                   => 'Pondelok',
    'TCKLARNA_TUESDAY'                                  => 'utorok',
    'TCKLARNA_WEDNESDAY'                                => 'streda',
    'TCKLARNA_THURSDAY'                                 => 'štvrtok',
    'TCKLARNA_FRIDAY'                                   => 'piatok',
    'TCKLARNA_SATURDAY'                                 => 'Sobota',
    'TCKLARNA_SUNDAY'                                   => 'nedeľa',
    'TCKLARNA_YOUR_COUNTRY_SPECIFIC_CREDS'              => 'Vaše prístupové údaje pre konkrétnu krajinu',
    'TCKLARNA_ADD_COUNTRY_SPECIFIC_CREDS'               => 'Pridať prístupové údaje pre jednotlivé krajiny',
    'TCKLARNA_COUNTRY'                                  => 'Krajina',
    'TCKLARNA_MERCHANT_ID'                              => 'Používateľské meno API',
    'TCKLARNA_PASSWORD'                                 => 'Heslo k API',
    'TCKLARNA_PORTAL_MERCHANT_ID'                       => 'ID obchodníka',
    'TCKLARNA_DEFAULT_SHOP_COUNTRY'                     => 'Štandardná krajina obchodu',
    'TCKLARNA_ENABLE_LOGGING'                           => 'Zaznamenávanie je aktívne',
    'TCKLARNA_SEND_ADDITIONAL_PRODUCT_DATA'             => 'Poslať rozšírené údaje o produkte spoločnosti Klarna?',
    'TCKLARNA_PRODUCT_URLS'                             => 'URL adresy produktov',
    'TCKLARNA_IMAGE_URLS'                               => 'URL obrázkov',
    'TCKLARNA_ENABLE_ANONYMIZATION'                     => 'Anonymizovať',
    'TCKLARNA_ADD'                                      => 'Pridať',

    'TCKLARNA_PAYMENTS_NAME'                            => 'Platby cez Klarna',
    'TCKLARNA_CHOOSE_KLARNA_MODULE_MODE'                => 'Vyberte režim modulu Klarna',

    'TCKLARNA_PAYMENTS_DESC'                            => 'S Klarnou môžu koncoví zákazníci platiť tromi spôsobmi: okamžitým prevodom, neskôr alebo na splátky. To im umožňuje najprv si tovar vyskúšať a zaplatiť len to, čo si chcú nechať, financovať produkty v obchode alebo zaplatiť ihneď. Faktúru, nákup na splátky, okamžitý prevod alebo inkasný príkaz môžete aktivovať prostredníctvom integrácie a vďaka riešeniu iFrame od spoločnosti Klarna sú vždy aktuálne z právneho aj obsahového hľadiska.',
    'TCKLARNA_EASY_AND_SECURE_SHOPPING'                 => 'Najobľúbenejšie spôsoby platby. Bezpečné a ľahko integrovateľné.',
    'TCKLARNA_WELCOME_TO_CONFIGURATION'                 => 'Srdečne vás vítame v nastaveniach konfigurácie služby Klarna Payments. Tu nájdete všetko, čo potrebujete na aktiváciu. Vyberte podponuky Klarna v ľavom paneli, aby ste dokončili nastavenie modulu.',

    'TCKLARNA_CREATE_USER_ACCOUNT'                      => 'Vytvorenie zákazníckeho účtu v e-shope OXID',
    'TCKLARNA_SUBSCRIBE_TO_NEWSLETTER'                  => 'Prihlásenie na odber noviniek',
    'TCKLARNA_CREATE_USER_ACCOUNT_AND_SUBSCRIBE'        => 'Vytvorenie zákazníckeho účtu A prihlásenie k odberu noviniek',
    'TCKLARNA_NO_CHECKBOX'                              => 'Nezobrazovať zaškrtávacie políčko',


    /* design */
    'TCKLARNA_DISPLAY_ON_HOME'                          => 'Zobraziť na úvodnej stránke obchodu?',
    'TCKLARNA_BANNER_SRC'                               => 'Zdroj banneru Klarna',
    'TCKLARNA_FOOTER'                                   => 'Pätica stránky',
    'TCKLARNA_DISPLAY_IN_FOOTER'                        => 'Čo sa má zobraziť v pätičke?',
    'TCKLARNA_FOOTER_PAYMENT_METHODS'                   => 'Zobrazenie spôsobov platby',
    'TCKLARNA_FOOTER_KLARNA_LOGO'                       => 'Logo spoločnosti Klarna',
    'TCKLARNA_DESIGN'                                   => 'Dizajn',
    'TCKLARNA_LONG_VERSION'                             => 'Dlhšia verzia:',
    'TCKLARNA_SHORT_VERSION'                            => 'Stručná verzia:',
    'TCKLARNA_WHITE'                                    => 'Biela:',
    'TCKLARNA_BLACK'                                    => 'Čierna:',
    'TCKLARNA_DETAILS_AND_BASKET'                       => 'Stránka s podrobnosťami o produkte a nákupný košík',
    'TCKLARNA_DISPLAY_PAYMENT_WIDGET'                   => 'Zobraziť widget platobnej metódy Klarna?',
    'TCKLARNA_ON_PROD_PAGE'                             => 'Na stránke s podrobnosťami o produkte',
    'TCKLARNA_ON_BASKET_PAGE'                           => 'Na stránke s nákupným košíkom',
    'TCKLARNA_DISPLAY_BUY_NOW'                          => 'Zobraziť tlačidlo „Kúpiť teraz“?',
    'TCKLARNA_PAYMENT_DESIGN'                           => 'Možnosti dizajnu platobného systému Klarna',
    'TCKLARNA_COLOR_SETTINGS'                           => 'Nastavenia farieb:',
    'TCKLARNA_BORDER'                                   => 'Hranica:',
    'TCKLARNA_BORDER_SELECTED'                          => 'Vybraná hranica:',
    'TCKLARNA_BUTTON'                                   => 'Tlačidlo:',
    'TCKLARNA_BUTTON_TEXT'                              => 'Text tlačidla:',
    'TCKLARNA_CHECKBOX'                                 => 'Zaškrtávacie políčko:',
    'TCKLARNA_CHECKBOX_CHECKMARK'                       => 'Zaškrtnutie políčka:',
    'TCKLARNA_DETAILS'                                  => 'Podrobnosti:',
    'TCKLARNA_HEADER'                                   => 'Nadpis:',
    'TCKLARNA_LINK'                                     => 'Odkaz:',
    'TCKLARNA_TEXT'                                     => 'Text:',
    'TCKLARNA_SECONDARY_TEXT'                           => 'Ďalší text:',
    'TCKLARNA_RADIUS_SETTINGS'                          => 'Nastavenie polomeru:',
    'TCKLARNA_BORDER_RADIUS'                            => 'Polomer ohybu rohu:',


    'TCKLARNA_ALLOW_SEPARATE_SHIPPING_ADDRESS'          => 'Doručovacia adresa sa môže líšiť od fakturačnej adresy',
    'TCKLARNA_PHONE_NUMBER_MANDATORY'                   => 'Telefónne číslo je povinné pole',
    'TCKLARNA_DATE_OF_BIRTH_MANDATORY'                  => 'Dátum narodenia je povinné pole',
    'TCKLARNA_ENABLE_DHL_PACKSTATION'                   => 'Aktivovať doručenie do DHL Packstation',
    'TCKLARNA_ENABLE_PRE_FILLING'                       => 'Aktivovať predbežné vyplnenie',
    'TCKLARNA_ENABLE_PREFILL_NOTIFICATION'              => 'Aktivovať upozornenie na predbežné vyplnenie',
    'TCKLARNA_SALUTATION_MANDATORY'                     => 'Oslovenie je povinné pole',
    'TCKLARNA_SET_TAC_URI'                              => 'URL k vašim obchodným podmienkam',
    'TCKLARNA_SET_CANCEL_URI'                           => 'URL týkajúca sa práva na odstúpenie od zmluvy',
    'TCKLARNA_SHIPPING_DETAILS'                         => 'Podrobnosti o doručení',
    'TCKLARNA_NO_VALIDATION_NEEDED'                     => 'Žiadna validácia',
    'TCKLARNA_VALIDATION_IGNORE_TIMEOUTS_NEEDED'        => 'Vykonajte validáciu, ale ignorujte časové limity',
    'TCKLARNA_SUCCESSFUL_VALIDATION_NEEDED'             => 'Je potrebná úspešná validácia',
    'TCKLARNA_ORDER_VALIDATION'                         => 'Overenie objednávky',

    'TCKLARNA_CHOOSE_KP_OPTIONS'                        => 'Vyberte si prosím platobné možnosti Klarna, ktoré chcete ponúknuť svojim zákazníkom:',
    'TCKLARNA_PAY_LATER'                                => 'Faktúra',
    'TCKLARNA_PAY_LATER.'                               => 'Faktúra.',
    'TCKLARNA_PAY_LATER_START'                          => 'Pre zákazníkov, ktorí chcú nakúpiť teraz a zaplatiť neskôr. Úplne pohodlne za 14, 21 alebo 28 dní, v závislosti od trhu.',
    'TCKLARNA_PAY_LATER_TEXT'                           => 'Možnosť „Faktúra“ umožňuje zákazníkom jednoduché a rýchle zaplatenie bez nutnosti zadávať osobné údaje alebo zložité čísla. Zákazník si môže vybrať medzi faktúrou a platbou v mesiaci X.',
    'TCKLARNA_SLICE_IT'                                 => 'Nákup na splátky.',
    'TCKLARNA_SLICE_IT.'                                => 'Platiť na splátky.',
    'TCKLARNA_SLICE_IT_START'                           => 'Zvýšte kúpnu silu svojich zákazníkov prostredníctvom splátok. Zákazníci môžu svoje nákupy uhradiť v pevných mesačných splátkach v priebehu 6 až 36 mesiacov.',
    'TCKLARNA_SLICE_IT_TEXT'                            => 'Prostredníctvom „nákupu na splátky“ si zákazníci môžu rozložiť sumu nákupu na menšie čiastky s nízkymi úrokmi. To zvyšuje investičný rámec a kúpnu silu. Jedinečný proces spracovania úveru spoločnosti Klarna trvá len niekoľko okamihov a vyžaduje zadanie minimálneho množstva údajov.',
    'TCKLARNA_PAY_NOW'                                  => 'Zaplatiť ihneď',
    'TCKLARNA_PAY_NOW.'                                 => 'Zaplatiť ihneď.',
    'TCKLARNA_PAY_NOW_START'                            => 'Jednoduchá a rýchla priama platba prostredníctvom služby „Sofort bezahlen“ od spoločnosti Klarna. V Nemecku by v ponuke nemali chýbať služby Sofortüberweisung, platba kreditnou kartou a inkasná platba.',
    'TCKLARNA_PAY_NOW_TEXT'                             => 'Zákazníci, ktorí chcú uhradiť celú sumu ihneď pri dokončení objednávky, môžu využiť možnosť „Zaplatiť ihneď“. Na výber majú platbu kreditnou kartou, inkasom z účtu a okamžitým prevodom.',

    'TCKLARNA_RB_HOW_TO_ACTIVATE'                       => 'Návod na<br /> aktiváciu služby Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_ONE'              => 'V administrácii OXID kliknite na novú položku menu „Klarna“, potom na podkategóriu „Všeobecné“ a následne vyberte požadovaný produkt Klarna.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_TWO'              => 'Zadajte svoje prihlasovacie údaje (užívateľské meno a heslo) a v časti Nastavenia obchodu &gt; Spôsoby platby a &gt; Spôsoby doručenia nastavte typické priradenia spôsobov platby pre systém OXID.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_THREE'            => 'Uložte zmeny.',
    'TCKLARNA_RB_HOW_TO_ACTIVATE_LIST_FOUR'             => 'Teraz ste online a môžete začať predávať prostredníctvom Klarny.',
    'TCKLARNA_RB_MERCHANT_SUPPORT'                      => 'Podpora pre obchodníkov',
    'TCKLARNA_DEVICE_IMG'                               => 'device.png',


    'TCKLARNA_EXTRA_MERCHANT_DATA_ADMIN_DESC'           => 'Tu môžete nastaviť, či sa majú prípadné dodatočné údaje o obchodníkovi odoslať spoločnosti Klarna. 
Podrobný popis jednotlivých nastavení nájdete v nápovedných tipoch 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">príručke</a> 
alebo sa obráťte na podporu integrácie Klarna.',
    'TCKLARNA_DESIGN_SETTINGS_ADMIN_DESC'               => 'Tu môžete nakonfigurovať nastavenia dizajnu pre použitie s modulom Klarna pre e-shop OXID. 
Podrobný popis jednotlivých nastavení nájdete v popiskách 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">príručke</a> 
alebo sa obráťte na podporu integrácie Klarna.',
    'TCKLARNA_GENERAL_SETTINGS_ADMIN_DESC'              => 'Tu môžete vybrať nastavenia pre platby Klarna a vykonať všeobecné nastavenia. 
Podrobný popis jednotlivých nastavení nájdete v nápovedách 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">príručke</a> 
alebo sa obráťte na podporu integrácie Klarna.',
    'TCKLARNA_CONFIGURATION_KP_ADMIN_DESC'              => 'Na tejto stránke si vyberiete, ktoré platobné metódy Klarna chcete ponúkať. 
Podrobný popis jednotlivých nastavení nájdete v popiskách 
<i class="fa fa-question-circle-o" aria-hidden="true"></i>, v <a class="cl-pink" href="%s" target="_blank">príručke</a> 
alebo sa obráťte na podporu integrácie Klarna.',

    'TCKLARNA_PAYMENT_METHOD'                           => 'Spôsob platby',
    'TCKLARNA_EXTERNAL_PAYMENT_METHOD'                  => 'Externý spôsob platby',
    'TCKLARNA_IMAGE_URI_EXT_PAYMENT'                    => 'URI obrázku pre externý spôsob platby',
    'TCKLARNA_IMAGE_TIP_69x24'                          => 'Veľkosť obrázku: 69 × 24 pixelov',
    'TCKLARNA_IMAGE_TIP_276x48'                         => 'Veľkosť obrázku: 276 × 48 pixelov',
    'TCKLARNA_USER_GUIDE_DESCRIPTION'                   => 'Návod na používanie modulu Klarna pre OXID eShop si môžete prečítať tu.',
    'TCKLARNA_USER_GUIDE_LINK'                          => 'https://wiki.fatchip.de/public/faqklarna7',
    'TCKLARNA_USER_GUIDE_BUTTON'                        => 'Návod na použitie',

    'TCKLARNA_CHOOSE'                                   => 'Vybrať',

    'TCKLARNA_CUSTOMER_ACCOUNT_INFO'                    => 'Informácie o zákazníckom účte',
    'TCKLARNA_PAYMENT_HISTORY_FULL'                     => 'Úplná história platieb',
    'TCKLARNA_PASSTHROUGH_FIELD'                        => 'Pole „Pass-through“',

    'TCKLARNA_ASSIGN_PAYMENT_METHOD_TYPE'               => 'Priradiť typ platobnej metódy:',
    'TCKLARNA_WHICH_ORDERS_IN_FULL_PAYMENT_HISTORY'     => 'Ktoré objednávky by mali byť zahrnuté v úplnej histórii platieb?',
    'TCKLARNA_EMD_ORDER_HISTORY_ALL'                    => 'Všetky objednávky sa považujú za zaplatené bez ohľadu na dátum oxpaid',
    'TCKLARNA_EMD_ORDER_HISTORY_PAID'                   => 'Odosielať len objednávky s nastaveným dátumom oxpaid; nezaplatené objednávky ignorovať',
    'TCKLARNA_EMD_ORDER_HISTORY_NONE'                   => 'Všetky objednávky, ktoré boli realizované s týmto spôsobom platby, ignorovať',
    'TCKLARNA_OTHER_PAYMENT'                            => 'Iná platobná možnosť',
    'TCKLARNA_DIRECT_BANKING'                           => 'Okamžitý prevod',
    'TCKLARNA_CARD'                                     => 'Mapa',

    'TCKLARNA_TEST_MODE_TOOLTIP'                        => 'Vyberte si medzi režimom „Playground“ (testovací režim) a „Live“ (produkčný režim). Produkčný režim aktivujte až po úspešnom vykonaní integračných testov a po konzultácii so svojím manažérom integrácie spoločnosti Klarna.',
    'TCKLARNA_GLOBAL_MERCHANT_ID_TOOLTIP'               => 'Zadajte sem, prosím, svoje prihlasovacie údaje do API služby Klarna. Tieto údaje ste dostali v uvítacom e-maile od spoločnosti Klarna. Toto používateľské meno a heslo platia globálne pre všetky krajiny. Iba v prípade, že ste dostali odlišné prihlasovacie údaje pre rôzne krajiny, môžete ich pridať nižšie.',
    'TCKLARNA_GLOBAL_PASSWORD_TOOLTIP'                  => 'Zadajte sem heslo, ktoré zodpovedá použitému používateľskému menu API. Toto heslo ste dostali v uvítacom e-maile od spoločnosti Klarna.',
    'TCKLARNA_GLOBAL_PORTAL_MERCHANT_ID_TOOLTIP'        => 'Zadajte sem, prosím, svoje identifikačné číslo obchodníka Klarna. Toto číslo ste dostali v uvítacom e-maile od spoločnosti Klarna.',
    'TCKLARNA_CREDENTIALS_COUNTRY_SELECTOR_TOOLTIP'     => 'Z ponuky vľavo vyberte krajinu, pre ktorú ste od spoločnosti Klarna dostali prístupové údaje platné pre danú krajinu.',
    'TCKLARNA_CREDENTIALS_COUNTRY_MERCHANT_ID_TOOLTIP'  => 'Zadajte sem príslušné používateľské meno pre túto krajinu.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PASSWORD_TOOLTIP'     => 'Zadajte tu príslušné heslo pre túto krajinu.',
    'TCKLARNA_CREDENTIALS_COUNTRY_PORTAL_MERCHANT_ID_TOOLTIP'=> 'Zadajte sem príslušné identifikačné číslo obchodníka pre túto krajinu.',
    'TCKLARNA_ENABLE_LOGGING_TOOLTIP'                   => 'Aktivuje funkciu protokolovania, aby sa všetka komunikácia cez API so spoločnosťou Klarna zaznamenávala do tabuľky tcklarna_logs v databáze MySQL. To môže byť užitočné pri analýze alebo hľadaní chýb. V produkčnom prostredí by mala byť táto funkcia vypnutá, pretože inak by sa mohli nahromadiť veľké množstvá protokolov a ukladať citlivé údaje.',
    'TCKLARNA_SEND_PRODUCT_URLS_TOOLTIP'                => 'Pošlite spoločnosti Klarna URL adresy stránok s podrobnými informáciami o produktoch, ktoré sa nachádzajú v nákupnom košíku vašich zákazníkov, aby mohla Klarna neskôr z portálu Klarna odkazovať na vaše produkty.',
    'TCKLARNA_SEND_PRODUCT_IMAGES_TOOLTIP'              => 'Pošlite spoločnosti Klarna URL adresy obrázkov produktov, ktoré sa nachádzajú v nákupnom košíku vašich zákazníkov, aby ich mohla Klarna zobraziť na portáli Klarna.',
    'TCKLARNA_ENABLE_ANONYMIZATION_TOOLTIP'             => 'Aktivujte anonymizáciu, aby ste pred spoločnosťou Klarna skryli názvy produktov, ktoré sa nachádzajú v nákupnom košíku vašich zákazníkov. Toto sa odporúča napríklad pre internetové lekárne, malo by sa to však urobiť len po konzultácii s manažérom integrácie spoločnosti Klarna.',
    'TCKLARNA_ALLOW_SEPARATE_DELIVERY_ADDRESS_TOOLTIP'  => 'Ak chcete umožniť doručenie na inú doručovaciu adresu, aktivujte toto políčko.',
    'TCKLARNA_MANDATORY_PHONE_TOOLTIP'                  => 'Ak chcete, aby bolo zadanie telefónneho čísla povinné, aktivujte tento prepínač. V bežnom prípade nie je telefónne číslo v systéme Klarna povinným poľom.',
    'TCKLARNA_MANDATORY_BIRTH_DATE_TOOLTIP'             => 'Ak chcete, aby bolo zadanie dátumu narodenia povinné, aktivujte tento prepínač. V bežnom prípade nie je dátum narodenia pre Klarnu povinným poľom. Jeho zadanie je však nevyhnutné na to, aby bolo možné uskutočniť nákup na faktúru alebo splátkový nákup.',
    'TCKLARNA_ENABLE_DHL_PACKSTATIONS_TOOLTIP'          => 'V súčasnosti nie je implementované',
    'TCKLARNA_CANCELLATION_RIGHTS_URL_TOOLTIP'          => 'Zadajte sem URL adresu vašej webovej stránky s informáciami o práve na odstúpenie od zmluvy. URL adresa musí začínať https://.',
    'TCKLARNA_SHIPPING_DETAILS_TOOLTIP'                 => 'Tieto informácie o doručení sa zákazníkovi zobrazia na stránke s poďakovaním po dokončení objednávky.',
    'TCKLARNA_EXTERNAL_PAYMENT_NAME_SELECT_TOOLTIP'     => 'Priraďte tento externý spôsob platby k jednému z preddefinovaných spôsobov platby',
    'TCKLARNA_EXTERNAL_IMAGE_URL_EMPTY'                 => 'Uveďte prosím URL pre všetky jazyky',
    'TCKLARNA_EXTERNAL_IMAGE_URL_INVALID'               => 'Zadajte prosím platnú URL adresu, ktorá začína na https://',
    'TCKLARNA_EMD_CUSTOMER_INFO_TOOLTIP'                => 'Toto prepínač aktivuje odosielanie dodatočných údajov spoločnosti Klarna, v tomto prípade informácií o zákazníckom účte, ktoré obsahujú dátum registrácie zákazníckeho účtu a dátum jeho poslednej zmeny.',
    'TCKLARNA_EMD_PAYMENT_HISTORY_FULL_TOOLTIP'         => 'Toto prepínač aktivuje odosielanie dodatočných údajov spoločnosti Klarna, v tomto prípade ide o „Payment History Full“, ktorý obsahuje doterajšie nákupy zákazníka.',
    'TCKLARNA_EMD_PAYMENT_TYPE_TOOLTIP'                 => 'Prosím, určite, o aký spôsob platby ide v prípade tejto platobnej metódy.',
    'TCKLARNA_EMD_HISTORY_FULL_TOOLTIP'                 => 'Tu prosím určite, či a prípadne ktoré objednávky s týmto spôsobom platby majú byť zahrnuté pri prenose histórie objednávok zákazníka. Závislosť poľa OXORDER.OXPAID určuje, či sa majú zohľadniť len zaplatené objednávky, alebo všetky objednávky.',
    'TCKLARNA_EMD_PASSTHROUGH_FIELD_TOOLTIP'            => 'Pomocou poľa „Pass-through“ je možné odoslať spoločnosti Klarna akékoľvek ďalšie údaje. Ak chcete túto funkciu využiť, musíte v e-shope OXID nainštalovať príslušný modul, ktorý zapíše požadované údaje do poľa „Pass-through“. Príslušný návod nájdete v dokumentácii pre vývojárov.',
    'TCKLARNA_DISPLAY_ON_HOME_TOOLTIP'                  => 'Týmto prepínačom aktivujete banner Klarna na úvodnej stránke vášho obchodu v štandardnej šablóne Apex.',
    'TCKLARNA_BANNER_SRC_TOOLTIP'                       => 'Tu môžete vložiť skriptovú značku na začlenenie banneru. V portáli bannerov spoločnosti Klarna nájdete prípadne ďalšie bannery na výber.',
    'TCKLARNA_FOOTER_PAYMENT_METHODS_TOOLTIP'           => 'Týmto prepínačom aktivujete zobrazenie platobnej metódy Klarna v pätičke vášho obchodu v štandardnej šablóne Apex.',
    'TCKLARNA_FOOTER_KLARNA_LOGO_TOOLTIP'               => 'Pomocou tohto prepínača vložíte logo Klarna do päty vášho obchodu v štandardnej šablóne Apex.',
    'TCKLARNA_BUY_NOW_ON_PROD_PAGE_TOOLTIP'             => 'Tento prepínač vloží tlačidlo „Kúpiť teraz“ na stránky s podrobnosťami o produktoch vo vašom obchode v štandardnej šablóne Apex.',
    'TCKLARNA_BORDER_TOOLTIP'                           => 'Farba rámčeka, ktorý sa zobrazí v prednej časti obchodu po výbere platobnej metódy Klarna, ak sú k dispozícii rôzne podmožnosti.',
    'TCKLARNA_BORDER_SELECTED_TOOLTIP'                  => 'Farba rámčeka, ktorý sa zobrazí v prednej časti obchodu po výbere platobnej metódy Klarna, ak sú k dispozícii rôzne podmožnosti. Táto farba sa používa na zvýraznenie aktuálne aktívnej podmožnosti.',
    'TCKLARNA_BUTTON_TOOLTIP'                           => 'Toto nastavenie nemá v čase zverejnenia tohto modulu zatiaľ žiadny vplyv.',
    'TCKLARNA_BUTTON_TEXT_TOOLTIP'                      => 'Toto nastavenie nemá v čase zverejnenia tohto modulu zatiaľ žiadny vplyv.',
    'TCKLARNA_DESIGN_CHECKBOX_TOOLTIP'                  => 'Farba pozadia rádiových tlačidiel, ktoré sa zobrazia v prednej časti obchodu po výbere platobnej metódy Klarna, ak sú k dispozícii rôzne podmožnosti',
    'TCKLARNA_DESIGN_CHECKBOX_CHECKMARK_TOOLTIP'        => 'Toto nastavenie nemá v čase zverejnenia tohto modulu zatiaľ žiadny vplyv.',
    'TCKLARNA_DETAILS_TOOLTIP'                          => 'Farba odrážok pri zobrazení podrobností o platbe na stránke výberu spôsobu platby.',
    'TCKLARNA_HEADER_TOOLTIP'                           => 'Toto nastavenie nemá v čase zverejnenia tohto modulu zatiaľ žiadny vplyv.',
    'TCKLARNA_LINK_TOOLTIP'                             => 'Farba odkazov v podrobnom popise spôsobov platby na stránke výberu spôsobov platby.',
    'TCKLARNA_TEXT_TOOLTIP'                             => 'Farba textu podrobného popisu spôsobov platby na stránke výberu spôsobov platby.',
    'TCKLARNA_SECONDARY_TEXT_TOOLTIP'                   => 'Alternatívna farba textu podrobného popisu spôsobov platby na stránke výberu spôsobov platby.',
    'TCKLARNA_BORDER_RADIUS_TOOLTIP'                    => 'Týmto nastavením môžete určiť mieru zaoblenia rámčeka, ktorý sa zobrazí v prednej časti obchodu po výbere platobnej metódy Klarna, a to v závislosti od rôznych dostupných podmožností.',

    'KLARNA_ONLY_FOR_KLARNA_PAYMENT'                    => 'Táto záložka sa týka iba objednávok cez Klarna',
    'KLARNA_CAPTURE_FULL_ORDER'                         => 'Zaznamenať celú objednávku',
    'KLARNA_CAPTURE_ID'                                 => 'ID transakcie',
    'KLARNA_CAPTURE_REFERENCE'                          => 'Referencia Klarna',
    'KLARNA_CAPTURE_AMOUNT'                             => 'Čiastka strhnutia',
    'KLARNA_CAPTURE_DATE'                               => 'Odúčtované dňa',
    'KLARNA_REFUND_AMOUNT'                              => 'Výška náhrady',
    'KLARNA_REFUND_DESCRIPTION'                         => 'Vrátenie peňazí – vysvetlenie',
    'KLARNA_REFUND_DATE'                                => 'Nahradené dňa',
    'KLARNA_CAPTURES'                                   => 'Odpočty',
    'KLARNA_REFUNDS'                                    => 'Vrátenie peňazí',
    'KLARNA_CANCEL_ORDER'                               => 'Zrušiť objednávku',
    'KLARNA_ORDER_IS_CANCELLED'                         => 'Objednávka bola zrušená. ',
    'KLARNA_SEE_ORDER_IN_PORTAL'                        => '<a href="%s" target="_blank" class="alert-link">Zobraziť túto objednávku na portáli Klarna</a>',
    'KLARNA_ORDER_NOT_IN_SYNC'                          => '<strong>Pozor!</strong> Údaje v tejto objednávke sa líšia od údajov uložených v systéme Klarna. ',
    'TCKLARNA_ORDER_UPDATE_CANT_BE_SENT_TO_KLARNA'      => 'Pozor! Vzhľadom na aktuálny stav objednávky nie je možné túto úpravu odoslať spoločnosti Klarna. V prípade potreby vykonajte príslušnú úpravu ručne priamo v portáli Klarna Merchant Portal.',
    'TCKLARNA_ORDER_UPDATE_REJECTED_BY_KLARNA'          => 'Pozor! Spoločnosť Klarna nemohla spracovať vaše posledné zmeny v tejto objednávke (dôvod: %s). Prosím, zrušte svoje nedávne zmeny v e-shope OXID alebo v prípade potreby vykonajte príslušnú úpravu ručne v portáli Klarna Merchant Portal.',
    'KLARNA_UNAUTHORIZED_REQUEST'                       => 'Neoprávnená žiadosť. Skontrolujte nastavenia modulu Klarna, ID obchodníka a príslušné heslo.',
    'KLARNA_ORDER_NOT_FOUND'                            => 'Túto objednávku sa v systéme spoločnosti Klarna nepodarilo nájsť. Zmeny v údajoch objednávky sa preto do systému spoločnosti Klarna neprevedú.',
    'KLARNA_MID_CHANGED_FOR_COUNTRY'                    => '<strong>Nesprávne prihlasovacie údaje!</strong> Táto objednávka bola zadaná s použitím ID predajcu <strong>%s</strong>. ID predajcu aktuálne nakonfigurované pre stránku <strong>%s</strong> je <strong>%s</strong>.',
    'TCKLARNA_PRODUCT_NAME'                             => 'Názov produktu',
    'TCKLARNA_ANONYMIZED_PRODUCT'                       => 'Anonymizovaný názov produktu:',
    'TCKLARNA_KP_INVOICE_MSG'                           => 'Platbu spracováva náš partner Klarna. Prosím, riaďte sa platobnými informáciami zaslanými spoločnosťou Klarna. Všetky svoje nákupy môžete spravovať prostredníctvom stránky Klarna.com alebo aplikácie Klarna a zaplatiť ich dokonca jediným kliknutím.',
    'TCKLARNA_VOUCHER_DISCOUNT'                         => 'Zľavový kupón',

    'TCKLARNA_GIFT_WRAPPING_TITLE'                      => 'Darčekové balenie',
    'TCKLARNA_GIFT_CARD_TITLE'                          => 'Blahoželanie',

    'TCKLARNA_ERROR_SHOP_SSL_NOT_CONFIGURED'            => 'Závažná chyba: Ak chcete aktivovať funkciu „%s“, je nutné v súbore config.inc.php vášho obchodu uviesť platnú adresu $this-&gt;sSSLShopURL chránenú protokolom SSL (https)!',
    'TCKLARNA_ERROR_WRONG_CREDS'                        => '<strong>Nesprávne prihlasovacie údaje!</strong>',

    'KLARNA_CAPTURE_SUCCESSFULL'                        => 'Suma bola úspešne strhnutá.',
    'TCKLARNA_CAPUTRE_FAIL_ORDER_CANCELLED'             => ' Platbu za objednávku nebolo možné strhnúť, pretože bola už zrušená.',
    'TCKLARNA_ANONYMIZED_PRODUCT_TOOLTIP'               => 'Zadajte sem reťazec, ktorý sa má odoslať spoločnosti Klarna namiesto skutočného názvu produktu.',
    'TCKLARNA_NO_REQUESTS_WILL_BE_SENT'                 => 'Vaše zmeny v tejto objednávke sa neprenesú do systému Klarna.',
    'TCKLARNA_USER_GUIDE'                               => 'Návod na použitie',
    'TCKLARNA_REGISTER_NOW_BUTTON'                      => 'Registrácia',
    'TCKLARNA_LEARN_MORE_BUTTON'                        => 'Zistiť viac',

    'TCKLARNA_CUSTOMER_TYPE'                            => 'Podporované typy zákazníkov',
    'TCKLARNA_CUSTOMER_TYPE_TOOLTIP'                    => 'Tu môžete nastaviť, či má obchod prijímať výlučne transakcie B2C (štandardné nastavenie), len transakcie B2B alebo transakcie B2C aj B2B.<br />  Poznámka: Po zmene typov zákazníkov je potrebné vymazať vyrovnávaciu pamäť relácie v prehliadači, aby bolo možné otestovať platbu.',
    'TCKLARNA_B2C'                                      => 'Iba zákazníci v segmente B2C',
    'TCKLARNA_B2B'                                      => 'Iba zákazníci z segmentu B2B',
    'TCKLARNA_B2B_B2C'                                  => 'Predovšetkým zákazníci z oblasti B2B, ale aj zákazníci z oblasti B2C',
    'TCKLARNA_B2C_B2B'                                  => 'Predovšetkým zákazníci z segmentu B2C, ale aj zákazníci z segmentu B2B',
    'TCKLARNA_NEED_SUPPORT'                             => 'Potrebujete pomoc s integráciou?',
    'TCKLARNA_REACH_SUPPORT'                            => 'Obráťte sa na zákaznícku podporu spoločnosti Klarna',

    'TCKLARNA_ON_SITE_MESSAGING'                        => 'Zasielanie správ priamo na mieste',
    'TCKLARNA_ON_SITE_MESSAGING_ADMIN_DESC'             => 'Tu môžete nakonfigurovať funkciu On-Site Messaging na použitie s modulom Klarna pre e-shop OXID.',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT'                 => 'Scenár',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT'                 => 'Stránka s podrobnosťami o produkte v rámci kampane na podporu úverov',
    'TCKLARNA_CREDIT_PROMOTION_BASKET'                  => 'Úverová akcia – Nákupný košík',
    'TCKLARNA_TOP_STRIP_PROMOTION'                      => 'Propagácia horného prúžku',
    'TCKLARNA_FOOTER_PROMOTION'                         => 'Propagácia v pätičke',
    'TCKLARNA_BANNER_PROMOTION'                         => 'Propagačný banner',
    'TCKLARNA_ON_SITE_MESSAGING_SCRIPT_TOOLTIP'         => 'Sem prosím vložte úryvok kódu knižnice JavaScript potrebný pre funkciu On-Site Messaging, ktorý získate v portáli Klarna Merchant Portal.',
    'TCKLARNA_CREDIT_PROMOTION_PRODUCT_TOOLTIP'         => 'Prosím, vložte sem umiestňovací tag, aby ste na stránke s podrobnosťami o produkte propagovali financovanie a nákup na splátky prostredníctvom Credit Promotions',
    'TCKLARNA_CREDIT_PROMOTION_BASKET_TOOLTIP'          => 'Prosím, vložte sem umiestňovací tag, aby ste na prehľade nákupného košíka propagovali financovanie a nákup na splátky prostredníctvom Credit Promotions',
    'TCKLARNA_TOP_STRIP_PROMOTION_TOOLTIP'              => 'Sem prosím vložte umiestňovací tag, aby ste na úvodnej stránke obchodu propagovali všeobecné informácie a informácie týkajúce sa konkrétnych spôsobov platby',
    'TCKLARNA_FOOTER_PROMOTION_TOOLTIP'                 => 'Prosím, vložte sem umiestňovací tag, aby sa v pätičke obchodu zobrazili dostupné spôsoby platby Klarna',
    'TCKLARNA_BANNER_PROMOTION_TOOLTIP'                 => 'Sem prosím vložte umiestňovací tag, aby ste mohli na úvodnú stránku svojho obchodu vložiť banner',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_TITLE'           => 'Čo je to On-Site Messaging?',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC'            => 'Zákazníci si nie vždy uvedomujú rôzne možnosti úverov a financovania, ktoré majú k dispozícii, ešte predtým, ako sa dostanú k pokladni. Možnosti financovania ponúknuté včas ovplyvňujú rozhodnutie o nákupe. 

Funkcia On-Site Messaging sa dá jednoducho a bezproblémovo integrovať a ponúka informácie na mieru, ktoré siahajú od všeobecných bannerov cez propagáciu vášho partnerstva so spoločnosťou Klarna a informácie o možnosti splátok až po personalizované úverové akcie na stránkach produktov alebo v košíku.',
    'TCKLARNA_ON_SITE_MESSAGING_HEADER_DESC_2'          => 'Ďalšie informácie o prvých krokoch <a class="cl-pink" href="https://developers.klarna.com/documentation/on-site-messaging/getting-started/" target="_blank">nájdete tu:</a><br /><br /> 
Prihláste sa do <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">portálu</a> <a class="cl-pink" href="https://merchants.klarna.com/" target="_blank">pre predajcov</a>, aby ste si vygenerovali svoj osobný kód JavaScript a kód umiestnenia. Funkcia On-Site-Messaging sa vo vašom obchode aktivuje hneď po uložení kódu JavaScript a zadaní aspoň jedného kódu umiestnenia.<br /> 
Kedykoľvek ju môžete deaktivovať odstránením týchto kódov.',
    'TCKLARNA_ON_SITE_MESSAGING_MERCHANT_BUTTON'        => 'Portál pre predajcov',
    'TCKLARNA_IS_ENABLED_HEADLINE'                      => 'Aktivovať službu Klarna Instant Shopping',
    'TCKLARNA_IS_ENABLED'                               => 'Aktívny',
    'TCKLARNA_IS_BUTTON_REPLACE'                        => 'Vymeniť tlačidlo Key',
    'TCKLARNA_IS_REPLACE'                               => 'Vytvoriť nové tlačidlo Key',
    'TCKLARNA_IS_BUTTON_REPLACE_TOOLTIP'                => 'Kľúč tlačidla môžete aktualizovať, ak je potrebné zmeniť konfiguračné alebo identifikačné údaje zo strany spoločnosti Klarna. Zvyčajne môžete raz vygenerovaný kľúč tlačidla používať tak dlho, ako budete chcieť.',
    'TCKLARNA_IS_ENABLED_TOOLTIP'                       => 'Tu aktivujte funkciu Klarna Instant Shopping. Tým sa automaticky vygeneruje tlačidlo na použitie v prednej časti obchodu.',
    'TCKLARNA_IS_BUTTON_APEARANCE_HEADLINE'             => 'Nastavenia štýlu tlačidiel',
    'TCKLARNA_IS_VARIATION_TOOLTIP'                     => 'Vyberte si, prosím, medzi tlačidlom s kompletným dizajnom v štýle Klarna a neutrálnejšou verziou „Light“.',
    'TCKLARNA_IS_TAGLINE_TOOLTIP'                       => 'Prosím, vyberte, či má byť farba písma sloganu pod tlačidlom svetlá alebo tmavá.',
    'TCKLARNA_IS_TYPE_TOOLTIP'                          => 'Vyberte, prosím, požadovaný nápis na tlačidle.',
    'TCKLARNA_IS_BUTTON_PREVIEW'                        => 'Náhľad tlačidla',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS'              => 'Zobraziť na stránke s podrobnosťami o produkte',
    'TCKLARNA_IS_BUTTON_PLACEMENT_DETAILS_TOOLTIP'      => 'Aktivujte túto funkciu, aby sa tlačidlo Klarna Instant Shopping zobrazovalo na všetkých stránkach s podrobnosťami o tovare vo vašom obchode.',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET'               => 'Zobraziť v prehľade nákupného košíka',
    'TCKLARNA_IS_BUTTON_PLACEMENT_BASKET_TOOLTIP'       => 'Aktivujte túto funkciu, aby sa v prehľade nákupného košíka vo vašom obchode zobrazil tlačidlo Klarna Instant Shopping.',
    'TCKLARNA_IS_BUTTON_SETTINGS_HEADLINE'              => 'Ďalšie nastavenia funkcie Instant Shopping',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS'=> 'Doručovacia adresa sa môže líšiť od fakturačnej adresy',
    'TCKLARNA_IS_SETTING_ALLOW_SEPARATE_SHIPPING_ADDRESS_TOOLTIP'=> 'Ak chcete umožniť doručenie na inú doručovaciu adresu, aktivujte toto políčko.',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY'       => 'Dátum narodenia ako povinné pole',
    'TCKLARNA_IS_SETTING_DATE_OF_BIRTH_MANDATORY_TOOLTIP'=> 'Ak chcete, aby bolo zadanie dátumu narodenia povinné, aktivujte toto políčko. V bežnom prípade nie je dátum narodenia pre Klarnu povinným poľom. Jeho zadanie je však potrebné na to, aby bolo možné uskutočniť nákup na faktúru alebo splátkový nákup.',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY'=> 'Národné identifikačné číslo ako povinné pole',
    'TCKLARNA_IS_SETTING_NATIONAL_IDENTIFICATION_NUMBER_MANDATORY_TOOLTIP'=> 'Prosím, vyberte, či má byť národné identifikačné číslo povinným poľom.',
    'TCKLARNA_IS_BUTTON_SETTINGS_VARIATION'             => 'Variácia',
    'TCKLARNA_IS_BUTTON_SETTINGS_TAGLINE'               => 'Slogan',
    'TCKLARNA_IS_BUTTON_SETTINGS_TYPE'                  => 'Typ',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY'               => 'Telefónne číslo je povinné pole',
    'TCKLARNA_IS_SETTING_PHONE_MANDATORY_TOOLTIP'       => 'Prosím, vyberte, či má byť telefónne číslo povinným poľom.',
    'TCKLARNA_IS_DEFAULT_COUNTRY_TIP'                   => 'Zoznamu prosím vyberte krajinu, ktorá sa má pri spustení služby Klarna Instant Shopping automaticky nastaviť ako predvolená, pokiaľ zákazník ešte neuviedol svoju krajinu.',
    'TCKLARNA_IS_TERMS_URI_TIP'                         => 'Zadajte sem URL adresu vašich všeobecných obchodných podmienok. Vyskytne sa odkaz na ne v pop-up okne služby Klarna Instant Shopping. Je potrebné zadať platnú URL adresu, ktorá začína https://.',

    'TCKLARNA_SHIPPING_SETTINGS'                        => 'Spôsoby doručenia',
    'TCKLARNA_COMPLETE_REFUND'                          => 'Pripísať celú objednávku na účet',
    'TCKLARNA_PACKSTATION_NO_SHIPPING_SET'              => 'Nenašli sa žiadne aktívne spôsoby doručenia',

    'TCKLARNA_AUTHPAYMENTMETHOD'                        => 'Použitý spôsob platby: ',
    'TCKLARNA_AUTHPAYMENTMETHOD_unknown'                => 'Klarna',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_by_card'            => 'Kreditná karta',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_debit'           => 'Inkaso',
    'TCKLARNA_AUTHPAYMENTMETHOD_direct_bank_transfer'   => 'Okamžitý prevod',
    'TCKLARNA_AUTHPAYMENTMETHOD_slice_it_by_card'       => '3 splátky bez úrokov',
    'TCKLARNA_AUTHPAYMENTMETHOD_fixed_sum_credit'       => 'Financovanie',
    'TCKLARNA_AUTHPAYMENTMETHOD_b2b_invoice'            => 'B2B faktúra (Billie)',
    'TCKLARNA_AUTHPAYMENTMETHOD_invoice'                => 'Faktúra',
    'TCKLARNA_AUTHPAYMENTMETHOD_pay_later_by_card'      => 'Platba kartou do 30 dní',
];
